### ISSUE TITLE
Text fuzzy on Windows with per-monitor scaling

### ISSUE THREAD

**Issue by brettcannon** [beeware/toga#1004]
**Describe the bug**
Text in the app is fuzzy compared to the title bar text

**To Reproduce**
1. Run any of the tutorial apps
2. Compare the crispness of the title bar text to the text of the menus

**Expected behavior**
Sharpness of the text of the menus and such to match that of the title bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/54418/88694980-2749e180-d0b6-11ea-8cf1-2d32ef36599c.png)

**Environment:**
 - Operating System: Windows 10
 - Python version: CPython 3.8.3
 - Software versions:
   - Briefcase:
   - Toga: 0.3.0dev22
   - ...

**Additional context**
Scaling of my screen is at 150%.

**Comment by mhsmith** [comment]
[Merged from #2135]

This area was last touched in #717, which added a call to `SetProcessDpiAwarenessContext(-2)`. -2 [is defined as](https://learn.microsoft.com/en-us/windows/win32/hidpi/dpi-awareness-context):

> DPI_AWARENESS_CONTEXT_SYSTEM_AWARE
> System DPI aware. This window does not scale for DPI changes. It will query for the DPI once and use that value for the lifetime of the process. If the DPI changes, the process will not adjust to the new DPI value. It will be automatically scaled up or down by the system when the DPI changes from the system value.

That sounds reasonable, but on Windows 10 22H2 the setting that I assume corresponds to the "system value" is hidden behind "Advanced scaling settings" and is marked "not recommended". This is the setting I used to use myself (having originally set it when the machine was on Windows 7), and it does work correctly with Toga, though you need to log out and log in again to change it.

However, the per-monitor scaling settings are much more prominent, and more convenient since they don't require logging out. So most users will use those settings and leave the "system value" at 100%. And this causes Toga apps to appear blurry, as shown in #704.

So we should probably switch to DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE or DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2, and do whatever's necessary to keep our internal idea of the DPI up to date.

Work in progress: #2155.
