### ISSUE TITLE
Support on_click and on_double_click in toga.Label

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#1022]
My use case is this:
When a user double-click a label, I want to switch this label with a text input so the user could edit the label. Once the user finished editing the text input, It should switch back to label.

The way I could do it is if `toga.Label` had `on_click` or `on_double_click` parameter in its constructor. I will use `on_double_click` and set it to a function that switches the label with a text input.

An alternative approach would be to use disabled `toga.TestInput` and make it enabled by double-clicking it. This approach requires us to add `on_click` or `on_double_click` to `toga.TextInput`.

What do you think is the right approach? Do you have another idea? Please let me know, and I'll implement it.

**Comment by freakboy3742** [comment]
My initial reaction is that this isn't a use case Toga should support out of the box, as I'm fairly sure it would violate most platform UX guides. If something is editable, it should appear to be editable (which means it's a text box); if it's *not* editable, it's a label. A widget that becomes editable on interaction feels like 'magic' UI to me - something that you will discover by accident, rather than being inherently obvious by looking at the UI. What is the visual cue to the user that a label is editable?

That said:

 1) I'm willing to be convinced - especially if you can provide examples of UIs where this sort of thing is common, or is "platform appropriate" native UX. I don't just mean that there are apps that use this metaphor - I know *those* exist - I mean examples where it is in apps that are officially supported by the platform (e.g., apps packaged with an operating system, or from OS vendors), or examples in documentation that suggest it *is* good practice.

 2) This is a good example of something that could happily live as an external widget definition. You should be able to define a single "EditableLabel" widget by writing a wrapper around toga.Label and toga.TextInput primitives and hooking up the "hide/swap" behavior you describe. If there's features missing from Toga that prevent your from building this as an external "composite" widget, then I would *definitely* consider those to be enhancements worth adding.

It would also be useful to have the start of an ecosystem of "non-official" widgets out there. From a project/community management point of view, I'd like start the trend of preserving the "toga" package namespace for officially supported external widgets (e.g., toga-chart), and encourage third-party widgets to use an external namespace (e.g, togax-editable-label). Having an example out there of a widget that "does it right" (including, potentially, documentation on how to do the platform specific stuff) would be a great start down this path.

**Comment by saroad2** [comment]
Here's my actual use case:

![records](https://user-images.githubusercontent.com/19425795/92754889-f686e880-f393-11ea-9d09-8d5584f46376.png)

This is a records window. After uploading a data file to *Eddington* you should be a able to open the records window, select or unselect records, and in the long-run: edit the records **from this window**.

By now I used `toga.Label`s and `toga.Selection`s and ordered them in `toga.Box`es instead of simply using `toga.Table` because the implementation of *Windows* does not support adding widgest as elements to the table, and I needed those `toga.Selection`s in order to select/unselect the records.

I could use `toga.Table` if we managed to add 2 features I'm missing:

1. Add a `checkboxes` parameter to the `toga.Table` constructor that adds a checkbox column to the left of the table (I've checked and this is something the Windows backends supports, we just need to add the ability to Toga)
2. Add the ability to edit rows in the table by double-clicking them. Didn't check on how to do that yet.

My idea was to double click the `toga.Label` and then turn it into `toga.TextInput` and in that way to achieve the "edit record" effect, but I'm aware that the right thing to do is to use `toga.Table` here once those features will be implemented.

What are your thoughts? Can I start work on implementing both those abilities?

**Comment by saroad2** [comment]
I now remember that we talked about it in #841 when we discussed about those checkboxes, but we didn't come into a conclusion on what we should do.

Please let me know if you have new thoughts about it.

**Comment by freakboy3742** [comment]
The use case you've described looks very much like a workaround to me, which means I'd be *very* hesitant to add it to Toga itself. As you say yourself - this widget *should* be a table; it's Toga's limitations that are bringing about the need for this behavior. 

Regarding #841 - my preference would be to allow "checkbox anywhere", but I'll update that ticket with some more notes.

**Comment by saroad2** [comment]
I see we both agree that the right thing to do is to make `toga.Table` work as expected. Therefore, closing this issue and keeping the conversation on the other issue.
