### ISSUE TITLE
Please, provide the reader with an example of Native layer for at least one plateform

### ISSUE THREAD

**Issue by MuhammadMouradG** [beeware/toga#1044]
When I am trying to understand the Toga Architecture, everything went well, but I was a little confused about the Native Layer, where is it executed and implemented? Is there an example for it that I can look at? Also, an important thing how the absence of this layer can effect the [Toga’s design philosophy](https://toga.readthedocs.io/en/latest/background/philosophy.html#abstract-broad-concepts)?

Could you please provide me answers for this questions with an example of one platform (Gtk is preferred)?

**Comment by freakboy3742** [comment]
Toga is comprised of three layers:

 * **The Interface Layer**. This is what is defined by toga-core. It's the public API for creating apps, windows, widgets etc. 
* **The Implementation Layer**. This is what is defined by toga-gtk or toga-cocoa. This is the layer that provides the implementation of the public API for a specific platform. It provides a private, internal API that the interface can use to create widgets.
* **The Native Layer**. This is the API for the underlying system widgets. This is usually provided by system-level APIs, not by Toga itself.

Mapping that onto a widget like "Button", there is:
 * `toga.Button` defined in toga-core. This is the public interface, and defines (amongst other things) that there is an `on_click` event handler on a Button.
* `toga-gtk.widgets.Button` defined in toga-gtk. This provides the implementation of toga.Button, describing how to create a button on GTK, and how to connect the GTK `clicked` signal to the `on_click` Toga handler.
* `Gtk.Button` the native [GTK-Python Widget API](https://python-gtk-3-tutorial.readthedocs.io/en/latest/button_widgets.html) that implements buttons on GTK. 

If you move the same widget to macOS:
* The toga-core API remains the same
* `toga-cocoa.widgets.Button` defines the interface. It satisfies the same *internal* API as `toga-gtk.widgets.Button`, but using macOS APIs rather than GTK APIs. It defines an `onPress:` message listener that connects to the `on_click` Toga handler.
* `NSButton`, the native macOS ObjectiveC API for creating a button. This is accessed using Rubicon, a library that gives access to the ObjectiveC runtime.

In this way, we can change the *implementation* of Button without changing the public API that end-users rely on. We're also able to provide `toga-dummy` - an implementation of the *internal* API that is completely platform independent that can be used for testing purposes.

Button is a simple example, because there's a single Interface widget, a single Native widget, and a single implementation that bridges between the two. A widget like like MultilineTextInput is more complex, because there's a single Interface widget, but *multiple* Native widgets (on GTK, a `Gtk.TextView` and a `Gtk.TextBuffer`. In that case, the implementation creates all the necessary native widgets, but provides a reliable *internal* API that manages the complexity.

I hope that clarifies things; Procedurally closing this ticket, but if you've got any follow up questions, I'm happy to answer them.

**Comment by MuhammadMouradG** [comment]
Thanks for your detailed explanation to the questions, I think all the picture is clear now.
