### ISSUE TITLE
Why the native layer of toga.Box represented as Gtk.Fixed?

### ISSUE THREAD

**Issue by MuhammadMouradG** [beeware/toga#1047]
I am trying to add some features and fix some errors with toga-gtk but I noticed a strange thing that add some complexity when try to add nested widgets and I am trying to figure out it. Why you are using Gtk.Fixed as a native layer to toga.Box; i.e. how you are seeing the relation between toga.Box interface and Gtk.Fixed native layer, I expect the toga.Box will have Gtk.Box as a native layer. In other words, because Gtk.Box Inherits from Gtk.Fixed then what are things that we do not want to inherit it from Gtk.Box when we are implement toga.Box interface.

**Comment by freakboy3742** [comment]
I don't know that I can give you a *good* answer, other than "well... it works" :-) `Gtk.Fixed` was used because it gives direct control over placement of children, which is necessary to support Toga's layout system; but it's entirely possible that there is a better approach in this case. 

In particular, I wouldn't be *entirely* surprised if having `toga.Box` backed by `Gtk.Box`, and then having a single `Gtk.Fixed` operating at the 'container' level (i.e., the thing that lays out widgets indide a window, or a top-level widget like a split pane) opens up some API possibilities that wouldn't otherwise be possible.

**Comment by MuhammadMouradG** [comment]
Well, I will work around similar idea that you mentioned, if I encounter a critical issue with the current implementation, or someone arises a critical issue with it, and as you say it is working now :-).

**Comment by SamSchott** [comment]
The current implementation does have the downside of really bad performance. Resizing a window with a larger number of widgets (for instance the table example) because unbearably laggy compared to macOS.

**Comment by freakboy3742** [comment]
@SamSchott That sounds like moving to a "container" model might be worthwhile then.

**Comment by SamSchott** [comment]
I suspect so, yes, but I'll have to admit that I don't really understand why the performance is so bad. The culprit seems to be `TogaBox.do_size_allocate` which regularly takes multiple milliseconds to complete. Having a container model and only updating the constraints, if such a concept exists at all in Gtk, should be faster.

I am generally wondering if the approach of calculating the new widget dimensions on the Python side (potentially multiple times while resizing a window through the GUI) provides the best performance. Alternatively, it might be better to translate the layout defined by Pack into a native layout and let the native layer handle resizing etc. This might of course not be possible on some backends and complicate the situation on others. I assume you had good reasons when choosing the current approach.

**Comment by freakboy3742** [comment]
The underlying reasoning behind handling layout on the Python side is that no two platforms have a completely consistent model for layout. For example - iOS native layout is constraint based; Winforms doesn't have a concept of constraint based layout. The only common layout language is "lay it all out yourself", so if we want to have "write once, same layout everywhere", the only real option is for Toga to define the layout completely. This has the added side effect that we can adopt CSS as a styling language, which is a generally understood language for layout (and happens to be the native layout language on the one platform that doesn't actually provide good tools for a "lay it out yourself" approach - web).

Could we move some of these calculation to native code for performance? Quite possibly; although I'd rather see how much we can squeeze out of Python first. Moving to a single "container", instead of having multiple Gtk.Fixed instances should improve matters considerably as the number of calculations should be a lot smaller. On top of that, distributing pure Python is a lot easier; and we've got some some legwork to do before we can use binary packages on iOS and Android.
