### ISSUE TITLE
Crash of ImageView example in Gtk

### ISSUE THREAD

**Issue by SamSchott** [beeware/toga#1062]
**Describe the bug**
The `imageview` example crashes on Gtk because `toga_gtk.ImageView.rehint()` is called before `toga_gtk.ImageView._pixbuf` has been set by the interface layer. The following traceback is produced:

```
Traceback (most recent call last):
  File "/home/samschott/.local/lib/python3.8/site-packages/toga_gtk/app.py", line 93, in gtk_startup
    self.interface.startup()
  File "/media/psf/Home/Python/toga/examples/imageview/imageview/app.py", line 18, in startup
    imageview_from_path = toga.ImageView(image_from_path)
  File "/home/samschott/.local/lib/python3.8/site-packages/toga/widgets/imageview.py", line 25, in __init__
    self._impl = self.factory.ImageView(interface=self)
  File "/home/samschott/.local/lib/python3.8/site-packages/toga_gtk/widgets/base.py", line 12, in __init__
    self.interface.style.reapply()
  File "/home/samschott/.local/lib/python3.8/site-packages/travertino/declaration.py", line 88, in reapply
    self.apply(style, getattr(self, style))
  File "/home/samschott/.local/lib/python3.8/site-packages/toga/style/pack.py", line 104, in apply
    self._applicator.set_font(
  File "/home/samschott/.local/lib/python3.8/site-packages/toga/style/applicator.py", line 25, in set_font
    self.widget._impl.rehint()
  File "/home/samschott/.local/lib/python3.8/site-packages/toga_gtk/widgets/imageview.py", line 20, in rehint
    original_height=self._pixbuf.get_height(),
AttributeError: 'NoneType' object has no attribute 'get_height'
```

**To Reproduce**
Run the imageview example:
```shell
python3 -m imageview
```

**Environment:**
 - Operating System: Ubuntu 20.04
 - Python version: Python 3.8
 - Software versions:
   - Toga: 0.3.0.dev23

**Additional context**
This is a tricky issue and I suspect it was introduced by a change to when the style is applied. Essentially, the interface does set image (pixbuf) during init. Nevertheless, the style is already applied during the init of `toga_gtk.base.Widget`, before setting the image (line 12):

https://github.com/beeware/toga/blob/f8bea583c87642ad102776e1b58fd8bb9265b135/src/gtk/toga_gtk/widgets/base.py#L5-L12

The quickest solution may be to guard against `pixbuf` not being set in the `rehint` implementation.

**Comment by SamSchott** [comment]
On the note of testing: I quite like your concept of using the examples as a visual test for the user interface. Would it make sense to also use them as a type of integration test and on the very basic level just assure that they start without crashes? This could be easily implemented in Github actions.

The second step, probably more useful, would be to find a way of defining and testing UI functionality and appearance of the examples. This of course is a difficult task...

**Comment by freakboy3742** [comment]
The catch is how to implement those tests. Even a "check that starting the app works" test poses problems:

1. CI runs in headless mode; this is probably OK with GTK (since worst case, you can run an Xvfb); but I don't know if Github Actions allows headless Cocoa/Windows/iOS/Android
2. It's not enough to just *start* the app... it needs to shut down, too. Otherwise, the test will hang looking for user input.

I've also toyed with the idea of writing tests using a GUI automation framework (like PyAutoGUI), or integrating some other automation tool.

I would *desperately* like to improve the testing story for the backends. We're seeing a regular stream of annoying regressions, and it's the absence of a comprehensive test framework that allows those regressions to slip in. But I'm drawing a blank on how to implement those tests in a cross platform way. But if we can find a way to solve this problem - Toga will be in a *much* stronger position.

**Comment by SamSchott** [comment]
I agree, a difficult problem. Regarding a simple implementation with just starting and stopping the app:

1. I think Xcode provides headless user interface tests but I don't know much about them or how they can be integrated with toga. Ideally, one would not want to write separate tests for every backend.
2. Fair point. Maybe starting a subprocess and sending SIGTERM if it hasn't crashed by itself is sufficient as a start.

A first step could be to write tests which run locally and not through CI. Or even more basic: have a meta-example which is a table with all examples. Double-clicking an entry will run the example in a subprocess. This would make it a lot more convenient to periodically try out all examples.
