### ISSUE TITLE
Access impl layer from the native layer

### ISSUE THREAD

**Issue by MuhammadMouradG** [beeware/toga#1079]
As I understand from the documentation, if I have a native layer the implementation widget can be access using `impl` attribute. But when I searched into the `toga` about `native._impl` using `grep -r native._impl ./toga`, I founded that:
```sh
./toga/src/cocoa/toga_cocoa/documents.py:        self.native._impl = self
./toga/src/cocoa/toga_cocoa/widgets/canvas.py:        self.native._impl = self
./toga/src/gtk/toga_gtk/window.py:        self.native._impl = self
./toga/src/iOS/toga_iOS/widgets/canvas.py:        self.native._impl = self
```
and when I tried that:
```python
print(self.native._impl)
```
for button widget for example, this raises an error: `AttributeError: 'Button' object has no attribute '_impl'`; although I have a native layer.

I expect we can access `_impl` layer from the `native` layer for each possible widget, as the documentation describe, is this an issue or I missed something?

**Comment by freakboy3742** [comment]
Access to the `_impl` from `native` is dependent on that reference being set up by the implementation layer. GTK/Cocoa/Winforms native widgets won't automatically get access to the Toga layer. Some widgets will have this set up because it was necessary to support the implementation; but simpler widgets (like Button) may not have this back-reference set up.

Conceptually, you should always be able to follow the link to `_impl` - so the omission of those links should be considered a bug (thankfully - one that is very simple to fix :-)

**Comment by MuhammadMouradG** [comment]
To be sure I have understood you right. In conceptual context, you must be able to access the `_impl` from the `native` for each widget, this may be useless for some widgets, like button, but this is our design philosophy.

So, we must have this line for each widget:
```python
self.native._impl = ...
```

**Comment by freakboy3742** [comment]
That's correct. It won't always be useful, but to avoid confusion, the `self.native.impl = self` assignment *should* exist.

**Comment by MuhammadMouradG** [comment]
I will make PR for fix this issue
