### ISSUE TITLE
Clarifying the `_handler` function formal parameter

### ISSUE THREAD

**Issue by MuhammadMouradG** [beeware/toga#1098]
This may be seem a bug. In line 49 of file `src/core/toga/handlers.py` in `_handler` function definition, in what the formal parameter `widget` is used? I can not find any object pass this parameter to itself? Could you please clarify the using?

This is the function definition:
```python
def _handler(widget, *args, **kwargs):
            if asyncio.iscoroutinefunction(handler):
                asyncio.ensure_future(
                    handler_with_cleanup(handler, cleanup, interface, *args, **kwargs)
                )
            else:
                result = handler(interface, *args, **kwargs)
                if inspect.isgenerator(result):
                    asyncio.ensure_future(
                        long_running_task(result, cleanup)
                    )
                else:
                    try:
                        if cleanup:
                            cleanup()
                        return result
                    except Exception as e:
                        print('Error in handler:', e, file=sys.stderr)
                        traceback.print_exc()
```

**Comment by MuhammadMouradG** [comment]
@freakboy3742 Could you please help me with this?

**Comment by freakboy3742** [comment]
To see what it's doing, you need to zoom out a bit.

As a user, you define a handler function:

```
def my_handler(widget, arg1, arg2):
   ...
```

This handler is then wrapped when it is used by a widget - see `toga.Button.on_press`, for example:
```
@on_press.setter
def on_press(self, handler):
    self._on_press = wrapped_handler(self, handler)
```

this means `my_handler` is passed into `wrapped_handler` as the `handler` argument.

`wrapped_handler` is then a function that defines and returns a function - `_handler()`. The end result is effectively the same as if you had written:

```
class Button:
    def _on_press(self, *args, **kwargs):
        ...
        # line 55 of handlers.py
        result = my_handler(self, *args, **kwargs):
        ...

```

The `interface` argument to `wrapped_handler` is the button instance - *but so is the widget argument to `_handler`* - it's just bound when the handler is invoked, rather than when the handler is wrapped.

So, it's not a *bug*. However, there is some possibility of cleanup. We could probably get away with dropping the `interface` argument to `wrapped_handler`, and replace the uses of `interface` in `_handler` with `widget`. This might save a *tiny* amount of memory (as there's one less variable in the closure); but perhaps the biggest reason would be that the implementation would be a little bit more obvious, so the next person looking at the code won't hit the same point of confusion.

**Comment by freakboy3742** [comment]
Closing as this is a question tied to a specific (now closed) enhancement proposal.
