### ISSUE TITLE
Update label text while in function?

### ISSUE THREAD

**Issue by tomnewg** [beeware/toga#1102]
Hi everyone,

thanks for beeware and toga such amazing tools. 

I built an app with multiple functions. All works fine. I would like to change the text of a label after a button was clicked to tell the user to wait until it is done. And at the end of the function the label text changes to "done". My problem is that when clicking the button the label text is not updated and only at the end of the function the label is updated. I tried refresh() but it doesn't seem to work. Any idea what to do? 

    def startup(self):
        self.output = toga.Label("")

    def calc(self, widget):
        self.output.text = "wait"
        self.output.refresh()
        # calculations
        self.output.text = "done"

App only shows "done" after the calculations but not "wait"

Many thanks for your help in advance

Tom

**Comment by freakboy3742** [comment]
To explain what's going on here, I need to give a little background on how native GUIs work behind the scenes.

GUIs operate on a event loop. Every time you click a button, you generate an event, and the GUI responds by invoking your event handler. However, another part of that event loop is a "redraw" cycle. When you make a change (like changing a label), the change doesn't *actually* take effect until the next redraw event occurs. 

If you're inside an event handler doing calculations (or anything else), the event loop isn't running; and as a result, redraws aren't happening, and any changes you make to the label won't be visible either. You can see this if you do something like "sleep(10)" in your button handler - you should see the OS complain that the app has become unresponsive, and you might notice that the GUI doesn't redraw itself if you drag other windows over the top of your app's window.

Calling refresh() won't do anything - that tells the GUI loop that something needs to be redrawn, but won't actually *do* the drawing.

However, if you add `yield 0.1` *instead* of `self.output.refresh()`, that should do the job. That tells the button handler to release control back to the event loop for a small time, which gives the GUI time to redraw the label. You can then proceed with your calculations - although, if the calculations are going to take any non-trivial amount of time, you may want to include additional `yield 0.1` calls so that the GUI gets an opportunity to redraw itself while you're calculating.

Interestingly, you *should* be able to use `yield 0`... however in my quick testing, that didn't actually work on macOS. I'm not 100% sure why - but it should probably be considered a bug.

**Comment by tomnewg** [comment]
Wow thank you so much for the explanation. That makes sense. And indeed the yield 0.1 does the job!

Many thanks for your help and have a great day

Tom

**Comment by freakboy3742** [comment]
Closing as the question has been answered.
