### ISSUE TITLE
I am getting an error in activity indicator

### ISSUE THREAD

**Issue by alok29awasthi** [beeware/toga#1124]
I used the code from this [link](https://github.com/beeware/toga/blob/master/examples/activityindicator/activityindicator/app.py).
I didn't change anything but got an error:
```
Traceback (most recent call last):
  File "c:\users\alok\beeware-tutorial\beeware-venv\lib\site-packages\toga_winforms\app.py", line 184, in run_app
    self.create()
  File "c:\users\alok\beeware-tutorial\beeware-venv\lib\site-packages\toga_winforms\app.py", line 81, in create
    self.interface.startup()
  File "C:\Users\Alok\beeware-tutorial\activityindicator\src\activityindicator\app.py", line 24, in startup
    self.spinner = toga.ActivityIndicator(style=Pack(padding_left=10, height=16))
  File "c:\users\alok\beeware-tutorial\beeware-venv\lib\site-packages\toga\widgets\activityindicator.py", line 23, in __init__
    self._impl = self.factory.ActivityIndicator(interface=self)
AttributeError: module 'toga_winforms.factory' has no attribute 'ActivityIndicator'
```

I am using windows for all this if you need that information. Please help me out. 
If you need any other info for resolving this please let me know.

**Comment by freakboy3742** [comment]
Thanks for the report; ActivityIndicator hasn't been implemented for Windows. This is on our todo list, but I can't give you a time when it will be done.

**Comment by johnzhou721** [comment]
Hi! Is there anywhere else where this is being tracked? Because we might be able to get away with ``ProgressBarStyle.Marquee`` and this could be a good exercise for me to start touching more parts of Toga.

**Comment by freakboy3742** [comment]
There's no specific issue for this; for the most part, we don't have an *issue* for missing widgets because an issue usually won't add any context that "NotImplemented" doesn't already answer.

`Marquee` isn't a good match here, though; the expectation is that an activity indicator is a "spinner" of some kind. If Winforms doesn't provide a native spinner widget, my guess would be that the best workaround implementation would be switching between an animated image and an empty image, using an image analogous to the "busy" spinner.

If we do go down the "spinner image" path, there's two things that need to be considered:
1. It needs to be visually consistent with Windows
2. We need to know the provenance of the image. We can't just download a random image off the internet; we need to either create the image ourselves, or know that the image has a license compatible with redistribution.

**Comment by johnzhou721** [comment]
@freakboy3742 Oh... so it has to be a spinner.

My search-ups for Winform spinner has failed me. However, if we want to go down the image path, https://stackoverflow.com/questions/37220327/show-transparent-loading-spinner-above-other-controls may be helpful.

**Comment by freakboy3742** [comment]
There might be some useful details in there, but be aware that the question being asked there is substantially different to the Toga use case. 

Toga won't ever have a "transparency through to other widget" problem - widgets are guaranteed by layout to *not* overlap. So we just need the ability to display a transparent PNG/GIF animation in a GUI - and from what I'm reading, animated images are a native capability of PictureBox.

**Comment by johnzhou721** [comment]
Hi! @freakboy3742 So I'm not that familiar with the WinForms stuff (clearly my main (but not super-) power is autoconf + some random iOS etc stuff) but maybe I could help design a spinning circles... What is the criteria for something to look visually consistent w/ Windows?

**Comment by freakboy3742** [comment]
In general, look for examples of apps on Windows that have a "spinner", and see what style they use. WinUI3 is a "newer" UI toolkit for Windows; their widget gallery [has an "Indeterminate ProgressRing"](https://learn.microsoft.com/en-us/windows/apps/design/controls/progress-controls) that seems as good as any.

However, more generally - if you don't have ready access to a Windows machine, or you're not familiar with Windows as a platform, the Winforms backend probably isn't the best place to contribute. If your primary developer machine is a Mac, you might want to start by looking at the DateInput and TimeInput widgets for macOS and iOS.

**Comment by johnzhou721** [comment]
Great! I will look into the macOS and iOS widgets.

So the idea for Indeterminate ProgressRing is that the segment on the
circle gets shorter first and then gets longer and rinse and repeat. I
might be able to animate that if I have time.

**Comment by johnzhou721** [comment]
I've made the animation attached below by myself. The going to the top
thing it gets longer faster and sort of jumps, not sure if this is
acceptable.  I might be able to write code but no guarantee.
[image: ezgif-3b5ef39edff582.gif]

**Comment by johnzhou721** [comment]
ezgif was for pdf to gif. I will upload the image properly tonight

**Comment by johnzhou721** [comment]
Two comments deleted because the ring I animated didn't get attached properly.

Anyway I fixed up the ring animation to make it look (hopefully) better now. Did a lot of math by hand and animated using LaTeX (sort of abuse since it's a tool for document preparation, using Tikz and preview package to crop out all the frames and made a Makefile to generate the gif), and the result is at https://github.com/johnzhou721/spinner-anim/releases/tag/initial -- sorry for all the magic numbers in the source!

Any suggestions and how can I contrib some code to make this a widget?

**Comment by freakboy3742** [comment]
> Two comments deleted because the ring I animated didn't get attached properly.

I think you've captured the general look and feel of the ring animation; however:

1. The spin period is *much* longer than the one on the MS sample page. I'd suggest a complete period of 1s would be plenty
2. The image itself probably doesn't need to be that large. 64x64 would be a *huge* spinner; the default size on most platforms is 32x32. 
3. The net result of those two is a file size of 121kb. That's... a lot for a spinner image.

> Any suggestions and how can I contrib some code to make this a widget?

I'm not sure what advice you're asking for here. You need to write an implementation of ActivityIndicator in the winforms backend, and an implementation of a testing probe for the same widget. I can't point you at a step-by-step set of documentation; it's a case of compare-and-contrast with other widgets on the same platform, and the same widget on other platforms.

**Comment by johnzhou721** [comment]
@freakboy3742 Thanks for the feedback! https://github.com/johnzhou721/spinner-anim/releases/tag/v2 is hopefully better...

Anyway this probably counts as abuse of LaTeX...

**Comment by johnzhou721** [comment]
OK so clearly I would need more experience w/ Toga before I can actually write code that gets this right.

Time to work on PAS...

**Comment by freakboy3742** [comment]
> [@freakboy3742](https://github.com/freakboy3742) Thanks for the feedback! https://github.com/johnzhou721/spinner-anim/releases/tag/v2 is hopefully better...

Yes - that's a lot better. The only other thing I've noticed is that the shade of blue isn't quite right. Based on the CSS on the same page, it should be rgb(0, 101, 179), not "blue".

> OK so clearly I would need more experience w/ Toga before I can actually write code that gets this right.

So... I have every confidence that someone who can work out an autoconf configuration for visionOS can work out how a Toga Winforms widget works 😄

**Comment by johnzhou721** [comment]
Thanks! Probably not within the next few weeks though... autoconf
configuration for visionOS is mostly just find and replace and looking at
code and looking at the corresponding shell script... some problem-solivng
but if you ask me to write a autoconf script I can't...

**Comment by johnzhou721** [comment]
@freakboy3742 OK so is the solution in the top answer of https://stackoverflow.com/questions/17545488/pause-a-gif-in-a-form acceptable? Also known as, can we use reflection?

The proper way is probably ImageAnimator but I'm not too familiar with that, and I could copy the ImageView code a lot by doing this. Another thing is -- I just realized I have no available testing machine; asked my mom and she said not to install any software on her ancient Windows laptop.

Since it's all Python, I'll try writing some tests (after I finish pages of Algebra homework and finish copying and changing code from ImageView etc), and you can test the appearance

**Comment by freakboy3742** [comment]
> [@freakboy3742](https://github.com/freakboy3742) OK so is the solution in the top answer of https://stackoverflow.com/questions/17545488/pause-a-gif-in-a-form acceptable? Also known as, can we use reflection?

I've never tried using System.Reflection, so I don't know; however, you may find that Python-level reflection is actually sufficient here.

That said... is reflection needed at all? We don't need to stop the animation... we need to *hide* the animation. I'm pretty sure on every other platform, when the progress indicator isn't running, it's hidden. Hiding the image shouldn't require anything fancy - you can remove the image from the layout.

**Comment by johnzhou721** [comment]
Oh so we just need it hidden... Neat!

FYI -- latest fixed version is at https://github.com/johnzhou721/spinner-anim/releases/tag/v3

**Comment by freakboy3742** [comment]
That image looks great; the 2x version is a little big; not sure if that can be optimised at all.

**Comment by johnzhou721** [comment]
@freakboy3742 Thanks! However, how would I embed this image resource into the Python package?

**Comment by johnzhou721** [comment]
@alok29awasthi FYI this is fixed now. See if the implementation works for you.
