### ISSUE TITLE
Just had a question

### ISSUE THREAD

**Issue by alok29awasthi** [beeware/toga#1125]
When will all the tools and widgets be available on the `widows` platform? I work on windows and found this very interesting but many components don't work on it. Also, availability in `android ` is even less. 
About `toga` it was written that we can make on one and use everywhere. I guess I can use mac os virtually and do it but I hope you guys add the features for other operating systems too. 
Just wanted to know if you have a specific timeline for this?

**Comment by freakboy3742** [comment]
BeeWare is a largely volunteer project, so it's almost impossible for us to give timelines for *anything* - because we're entirely dependent on what time volunteers are able to contribute. We *want* to get Windows to a point where it's equal to other platforms, but that's dependent on having resources to do so.
