### ISSUE TITLE
Not implemented: MultilineTextInput.set_placeholder()

### ISSUE THREAD

**Issue by frsnmk** [beeware/toga#1178]
**Describe the bug**
in windows when I make multiline text input and add placeholders, the placeholders don't work and in the console it's written
[Winforms] Not implemented: MultilineTextInput.set_placeholder()

**Environment:**
 - Operating System: Windows 10
 - Python version: 3.7.5
 - Software versions:
   - Briefcase: 0.3.3
   - Toga: 0.3.0 dev25
   - ...

**Comment by freakboy3742** [comment]
Thanks for the report! In this case, this is a known missing feature - that's why you got a message on the console.

From a project management point of view, we don't open tickets for every feature missing on a given platform, because we'd end up with an absurd number of open tickets, which won't actually help us manage the project as a whole.

If you want to tackle this problem and contribute a fix, you can submit a pull request without having a corresponding ticket.

**Comment by martinandersen3d** [comment]
How can I disable this message?


The Linux "philosophy" is that you can Pipe applications in the console like:

```
echo "John Doe" | toga_app | cat ./output.txt
```

right now the terminal output is just crazy:
![image](https://user-images.githubusercontent.com/19984581/128801431-482eb182-b778-42d4-b2bc-507b260330b9.png)



Can I please disable this behavior somehow?

**Comment by freakboy3742** [comment]
@martinandersen3d At present, no. And, in some respects, it's deliberately annoying - to encourage people to contribute the missing features :-) 

However, we'd also welcome an contribution that makes those messages easier to manage.

If you want to work on this patch, the code in question (for GTK) is [here](https://github.com/beeware/toga/blob/master/src/gtk/toga_gtk/factory.py#L33).

**Comment by martinandersen3d** [comment]
Thank you for pointing me in the right direction 🙏🙏🙏🙏🙏

I solved the problem for now, commented out the line 😁
