### ISSUE TITLE
custom fonts

### ISSUE THREAD

**Issue by canedha** [beeware/toga#1210]
Is it actually possible to use custom fonts?
with serif/sans_serif, i can change between those two, but when I for example try to use Arial (font_family="Arial") it gives me an error.
If possible, what happens when the font is not installed? Will it switch to system font?

**Comment by freakboy3742** [comment]
It *should* be possible to use custom fonts; however, at present, the the name you use will need to (a) be registered with the operating system, and (b) match what your OS calls the font. These names can be highly platform-dependent; "Arial" should be a pretty safe name, but depending on your operating system, you may not have Arial installed as a *system* font. 

There's been some recent (informal) discussion about adding an in-app API for registering new fonts; however, that API doesn't exist at present. 

If a font isn't available, it *should* fall back to the system font; if that's not happening, it's a bug.

**Comment by canedha** [comment]
thx for your quick answer! could you tell me how the code should look like e. g. for "Comic Sans"?
should be registered as system font, but can't get it to run (might be my fault, as I'm relatively new to python)

**Comment by freakboy3742** [comment]
Generally, I'd expect it to be "Comic Sans" - however, that may be highly platform dependent. 

You may also want to check whether the widget that you're trying to use actually supports custom fonts on your OS - font support isn't universally implemented at present, so some platforms and widgets don't necessarily support fonts (yet). 

If you can tell us which OS you're using, and which widgets you're trying to set the font, we can provide guidance on availability.

**Comment by canedha** [comment]
I'm using Win10 (up to date).
Currently I just want to see if I can use custom fonts (no matter which widget). Most likely it is an issue of me not using the correct syntax. It's still hard for me to get things correctly written, if I can't find examples/tutorials that more or less already do what I want.

I tried to simply make a label with custom font and used:

`name_label = toga.Label( 'Your name: ', style=Pack(font_size=50, font_family="Comic Sans")`

also tried:

`name_label = toga.Label()`
`name_label.font = Font(font_size=50, font_family="Comic Sans")`

but without success...

**Comment by freakboy3742** [comment]
Ok - so there's three problems at work here. 

The first is the name of the font. The official name for Comic Sans on Windows is "Comic Sans MS"; so you need to use that name to look the font up.

The second is the API. Your first example is correct, setting the font as part of the style object. There's no API to set the font directly on a widget as you are doing in the second example.

The final problem is a bug in Toga itself. On Windows, the code that is confirming whether a font is available is currently failing - the "font exists" check is checking the wrong attribute.

As an immediate workaround, you can use the font name of "cursive" to get Comic Sans specifically. The font names "serif", "sans serif", "fantasy" and "monospace" are also valid (these are names guaranteed to exist by CSS, and Toga has inherited that naming convention). 

Longer term, we need to fix the bug around line 54 of toga_winforms/libs/fonts.py which is checking the string name of the font against a collection of font objects, rather than checking against the *name* of each of those font objects.

**Comment by canedha** [comment]
Thanks for the clarification and the help! It's really appreaciated :)

As far as I understand Toga uses OS native possibilities to create the app, which means it always looks good and you can run it on multiple platforms easily. Another approach would be Kivy, which has its own style and is written to run on all plattforms.
(maybe not the best explaination ever)
I really like the Toga approach as, in my personal opinion, Kivy looks not very nice and you can't change the look.
But as nice as having it look like native OS might be, sometimes you wish to customize it at least a bit e.g. in this case fonts. Are there plan for future (the far maybe) to implement e.g. app native style options? In my case, I provide the font and its stored in the app files and used on whatever OS without installing it on the system itself?

**Comment by freakboy3742** [comment]
We definitely have plans to improve styling options - it's a matter of time and resources. Toga is currently at v0.3, which reflects the level of maturity in the APIs. There's a lot of work still to be done.
