### ISSUE TITLE
Displaying two images side by side

### ISSUE THREAD

**Issue by MMartin09** [beeware/toga#1211]
I want to display two images side by side. I think SplitContainer is well suited for this. 
It works fine but when I open the application the right image is much bigger than the left one. 
I want to have the same size for both images (or sides of the container). 

Is it possible to define the size of the content?

Ps. Maybe there is a generally better way to display two images but when I tried using two boxes I always only see one.

**Comment by freakboy3742** [comment]
Yes, it's possible to define the size of content - that's what the style language is for. If you set the width/height of the ImageView, that's how big the image will be. If you set both ImageViews to the same size... well, they'll be the same size.

SplitContainer is a structural element in your overall layout. It provides a user-configurable bar that can be moved left/right or up/down (depending on the direction of the split). You can, however, specify the initial "weight" of the split (e.g, do you want the split to be equal 50/50, or 20/80?) by specifying a weight along with the content when you define the content for the split container (e.g., `split_container.content = [image_a, image_b]` will let the system decide weighting; `split_container.content = [(image_a, 0.5), (image_b, 0.5)] will set an initial 50/50 split).

Without seeing your code, it's impossible to know why you were unable to display 2 images - but the `image` example shows that it is definitely possible to have 2 images on the same page. I suspect you may have had an error in your code that wasn't adding the second image, or wasn't adding it in the way you thought it was.

Closing this since the original question has been answered; if you would like additional details, feel free to continue the discussion or open a new ticket.

**Comment by MMartin09** [comment]
Thank you. This answers my question, yes, but it does not work for me. 

```
    def startup(self):
        self.main_window = toga.MainWindow(title="Test")

        image_a = toga.Image("./images/breno-machado-in9-n0JwgZ0-unsplash.jpg")
        image_b = toga.Image("./images/jonatan-pie-3l3RwQdHRHg-unsplash.jpg")

        imageview_a = toga.ImageView(image_a)
        imageview_b = toga.ImageView(image_b)

        split = toga.SplitContainer()
        split.content = [(imageview_a, 0.5), (imageview_b, 0.5)]

        self.main_window.content = split
        self.main_window.show()
```

The code sample shows my startup method. The result of it is shown below:

![image](https://user-images.githubusercontent.com/16896363/108956919-d3fe3880-7670-11eb-931f-a1e150ea9046.png)

If I set the size of the `ImageView`it is working. But setting the weight does not work.

**Comment by freakboy3742** [comment]
Interesting... that looks like it might be a bug, then. Weight *should* be implemented on Winforms SplitContainer.

**Comment by obulat** [comment]
@MMartin09 , I tested your code on Windows, and the split container is split evenly.

I also tried `split.content = [(imageview_a, 0.3), (imageview_b, 0.7)]` and it works as expected: the left image takes up 30% of the window width, and the right image takes up 70%.

Can you share the version of Toga you are using?

**Comment by MMartin09** [comment]
I am using Windows 10 and toga 0.3.0dev24

**Comment by MMartin09** [comment]
Okay, the upgrade to dev26 solved my problem. But working with boxes still doesn't work. 

```
    def startup(self):
        self.main_window = toga.MainWindow(title="Test")

        box = toga.Box()
        box.style.update(alignment=CENTER)
        box.style.update(direction=ROW)

        box_1 = toga.Box()
        box.style.update(direction=COLUMN)
        box_2 = toga.Box()
        box.style.update(direction=COLUMN)

        image_a = toga.Image("./images/breno-machado-in9-n0JwgZ0-unsplash.jpg")
        image_b = toga.Image("./images/jonatan-pie-3l3RwQdHRHg-unsplash.jpg")

        imageview_a = toga.ImageView(image_a)
        imageview_a.style.update(width=50)
        imageview_b = toga.ImageView(image_b)
        imageview_b.style.update(width=50)

        box_1.add(imageview_a)
        box_2.add(imageview_b)

        box.add(box_1)
        box.add(box_2)

        self.main_window.content = box

        self.main_window.show()
```

![image](https://user-images.githubusercontent.com/16896363/109463326-16ef5000-7a65-11eb-9e0d-d7857f3dd1ed.png)
