### ISSUE TITLE
A native application for X11

### ISSUE THREAD

**Issue by MuhammadMouradG** [beeware/toga#1225]
**Is your feature request related to a problem? Please describe.**
The toga philosophy provide us with a native user interface apps, this is good, but what about if I don't have a backend native interface, i.e. what if I use a Unix-like OS without any backend GUI like `Gtk3+` or `Qt` backends and just simply using `X11`. The current implementation does not provide us a backend for this need, i.e. backend that help me to build an app has a minimum requirements backend but provide me with an GUI app.

**Describe the solution you'd like**
I suggest adopting a backend for this purpose like `Tkinter` or something else that compatible with toga project.

**Additional context**
This will be helpful if I want an app and I want my machine as simple as possible.

**Comment by MuhammadMouradG** [comment]
May be the title is misleading but I can not find other.

**Comment by paulproteus** [comment]
Hi @MuhammadMouradG !

I'm hoping to get more info and keep this conversation moving. I'm just a contributor, not a core maintainer, so my opinion isn't authoritative.

I wanted to share two questions I have about a non-Gtk non-Qt X11 backend for Toga.

Would it implement a substantial number of [the Toga widgets?](https://toga.readthedocs.io/en/latest/reference/widgets_by_platform.html) If it doesn't, then I think it would frustrating rather than helpful to people who write Toga apps.

Would this backend create an app that looks, feels, and works like other apps on your system? The [Why Toga?](https://toga.readthedocs.io/en/latest/background/philosophy.html) page of the docs says, "You need to _feel_ like a native app." In X11 without Qt or Gtk, in my experience, there is no consistent look and feel. If there is no consistent look and feel that the Toga app blends in smoothly with, then I think Toga can't really accomplish its goal.

I would love to know what you think. I'm hoping that we can figure out if the idea of a non-Gtk non-Qt Toga backend for X11 makes sense, and if so, figure out what the next step should be. If it's not a good it for Toga, maybe it makes sense to develop outside Toga.

**Comment by freakboy3742** [comment]
Following on from @paulproteus - on Unix, there's *always* a widget toolkit, because X11 doesn't have a "native" concept of widgets - it's a base layer drawing toolkit. Tkinter, for example, *is* a widget toolkit - it's Tk.                          

I'm not fundamentally opposed to the idea of a `toga-tkinter` backend if someone is motivated to write and maintain it. However, it's worth pointing out that one of the reasons that Toga exists in the first place is that Tkinter proved insufficient for my app development needs; for example, adding a Tk-based web view will require *major* effort. And, at the end of the day, you're going to get an app that looks like Motif - a widget toolkit that would have been native-looking in the early 90s, but definitely isn't any more today.

**Comment by MuhammadMouradG** [comment]
Sorry for late response.

Thanks @paulproteus for your response and your questions, I think they will be put us on the right way whether adopting, improve or neglect the idea.

> Would it implement a substantial number of the Toga widgets?

I think there is no big technical issues to provide most of these widgets. If there is some widgets that can not be fully-featured implemented then this will be a cost of building applications on these minimal systems with few lines of python code (thanks toga).

> Would this backend create an app that looks, feels, and works like other apps on your system?

I think we have the same question in web applications that designed by `toga`, are all the web applications will be looks, feels and works like other web applications on your system? The answer is NO, but it is a toga backend although. However, we can, if we want, adopting some styles when we design apps for those `X11` systems.
We may argue on that the nature of web applications does not similar to the desktop applications, however, we can think in `X11` backend as a native to all GUIs and accepts all looks and feels although we can always adopting some styles in our implementation.

Finally, regards to the mentioned problem for web view by @freakboy3742,  I think [cefpython](https://github.com/cztomczak/cefpython) can help us for solving the proplem, this is just an example and we may don't depend on `tkinter` at the end. This makes me think why we rely on a single backend, i.e. `tkinter`, I think this will complicate the implementation if there is no reasons. In other words, are we able to use more than one backend like `tkinter` and `cefpython` or others? Also, this makes me suggest a name for this backend like `toga-lite` rather than `toga-tkinter`.

I attached a screenshot for a simple application building on my machine, working with `minimal-xorg` package , with `tkinter` with a simple style and I think it has a good look and we can describe it with more than `Motif`. 

Thanks for your time and I hope hearing form you @freakboy3742, @paulproteus.
![tkinter](https://user-images.githubusercontent.com/50509521/112102876-96c69100-8bb1-11eb-8bce-13ef3bd08108.png)

**Comment by freakboy3742** [comment]
It's true that web apps won't share the look and feel of your desktop apps - but then, if you're writing a web app, the desktop isn't the platform that is being targeted. Web apps are targetting the *web* - that means they need to expose a UI that is native for the *web*. This means we need to support web-native features like deep linking, URL-based navigation, and high-level theming through CSS. It doesn't mean we need to make a web app look and feel like an macOS or Windows desktop app.

The analogy between X11 and Web is also fair enough - they're both very low level drawing protocols. However, the Web *does* have the concept of native widgets. To be sure, there aren't many - but they do exist. There is a native concept of a "Button" in HTML. There is a basic concept of a windows, and panes within that window. And, of course, there's a native WebView widget... the web *is* a WebView widget :-)

X11 doesn't have those primitives. It's a canvas on which you can issue drawing instructions over a network layer. There's no such thing as an "X11 Button". There's a Motif button, or a Tk button, or a GTK button - but no X11 button.

So - if you wanted to propose adding 'toga-motif' or 'toga-tk', that would make sense; but 'toga-x11' doesn't make any sense.

I like your optimism that toga-tk would be "relatively little effort". My experience with Tkinter has been that it has a good, but not great spread of widgets; and when a widget is missing, you're pretty much out of luck, I wasn't aware of cefpython - that definitely looks promising on the webview front - but there are other widgets that Toga requires that I don't think you'll find analogs in Tk. I'm happy to be proven wrong, though.

Ultimately, if you're particularly motivated to write a toga-tk backend, I won't stand in your way, and I'm open to any API suggestions that make alternate widget toolkits more viable. However, I would ask... why? What is your use case here? What audience for an app are you anticipating that has access to a Linux X11 graphical desktop... and *doesn't* have a desktop environment that is based either in GTK ( Gnome, LXDE etc) or Qt (KDE)? You say you want an app that is "as simple as possible" - I'm not sure how introducing a widget toolkit that *isn't* the platform's native widget toolkit makes things simpler.

**Comment by MuhammadMouradG** [comment]
> What is your use case here? What audience for an app are you anticipating that has access to a Linux X11 graphical desktop... and doesn't have a desktop environment that is based either in GTK ( Gnome, LXDE etc) or Qt (KDE)?

You can describe this as another preferable use case for some users like the users that prefer using `Qt`. Some users prefer using [dwm](https://dwm.suckless.org/) and need their machine to be efficient, minimum and fast. In some cases you may need only one application (which we will be written by toga) and does not need all these stuff applications that `Qt` and `Gtk` download them automatically. In other cases, you may work in `raspberry pi` and you need every space and resources you have, so install `X11` and your application, that will be written by toga, will be a preferable rather than install some light-GUIs and then your application.

When I said "as simple as possible" I meant my machine is simple with only Linux `X11` graphical desktop.

Also, I want to refer to that when I said `Tkinter` that was an initial thought and at the end we may end up with using another backend like `wxPython` and I think this will need another topic to discuss it or in the phase of API proposal.

**Comment by freakboy3742** [comment]
It think you're missing my point.

If you use DWM, and you're using graphical apps, *you still have a widget toolkit* - possibly several. The Evince-lite package you reference has a widget toolkit - GTK. If you're using Raspberry Pi with Raspbian, you're using GTK. 

If you're using wxPython, then you're using GTK as well. wxPython is effectively a competitor to Toga. While we *could* layer Toga over wxPython, it wouldn't make a whole lot of sense to do so, as wxPython *is* a cross-platform GUI layer.

If you dig up software from 25 years ago, before GTK and Qt existed, you'll find that they all used Motif - that was the default widget toolkit of the late 80s/early 90s. So there's still a widget toolkit - it's just not GTK or Qt.

Tk has a mix. It contains "classic widgets", which are it's own widget implementations (making Tk a widget toolkit); and there are "themed widgets"; these fall back on a theme for drawing instructions, and that means falling back on Gtk or Qt (depending on how your Tk install is configured) for the underlying drawing. So, that means Tk is a weird hybrid, halfway between a widget toolkit (like GTK) and a cross-platform library (like wxWindows). However, it functionally presents as a widget toolkit, so it makes sense (conceptually, anyway), to define a toga-tk backend. 

If you truly *only* have X11, then you don't have *buttons*. You don't have *window chrome*. You don't have a "native look and feel" that an apps could adhere to. You have a canvas on which you can draw lines and text. So, unless you're proposing to develop an entire widget toolkit *from scratch* - effectively writing a competitor to GTK, Qt, and Tk - a "X11 only" backend *cannot exist*. It *must* have a dependency on a widget toolkit - the only question is which one. 

If your use case is "run on a minimal desktop" - that's a different problem to "run on X11-only", because once again, there's no such thing as "X11-only" if you're expecting to see widgets on the screen. You're still going to have a widget toolkit; so the question is really about asking what API features toga-gtk is using that are breaking on your "minimal desktop"?

**Comment by MuhammadMouradG** [comment]
Sorry for that, I missed some points and you clarified them in your last comment, thank you for clarification. I think my current use case is satisfied with current implementation. Thank you again for your time and clarification.
