### ISSUE TITLE
Webview Javascript autoexecute

### ISSUE THREAD

**Issue by thegame4craft** [beeware/toga#1260]
**Is your feature request related to a problem? Please describe.**
when i trys to port my website with javascript to an android app, i failed, because my website has a lot of js and i don't wanna to write it a 2nd time in the app. 

**Describe the solution you'd like**
I like to have a function to execute all javascript in html at once

**Describe alternatives you've considered**
It's ok if you made it like pyqt5 (for pyqt6 i haven't tryed)

**Additional context**

I have searched a lot on the internet and have no way found to execute all javascript in html.

**Comment by freakboy3742** [comment]
It's not clear to me what you're suggesting here. A Webview displays a web page. If that web page contains javascript, it will be loaded and executed in accordance with the rules followed by a web browser. There's nothing we can do to "execute all the javascript", or "auto execute" a particular block of javascript. 

If this is a feature that PyQt offers, then you're going to need to provide more details about what that feature is - either by describing the feature in more detail, or linking to the relevant Qt docs - because we're not Qt experts.
