### ISSUE TITLE
On Android, the application complains about `AttributeError: 'TextInput' object has no attribute '_validators'`

### ISSUE THREAD

**Issue by Dominik1123** [beeware/toga#1290]
**Describe the bug**

I use a `field = toga.TextInput()` and then use `field.validate()` inside the `on_change` callback method, in order to react accordingly. The application seems to work without problems, however when I check the logs via `adb logcat -s MainActivity:* stdio:* Python:*` then I see the following errors:

```
06-25 00:41:56.036 28676 28676 D Python  : Native invocation 511594544624 :: beforeTextChanged
06-25 00:41:56.036 28676 28676 D Python  : Native invocation done.
06-25 00:41:56.036 28676 28676 D Python  : Native invocation 511594544624 :: onTextChanged
06-25 00:41:56.037 28676 28676 D Python  : Native invocation done.
06-25 00:41:56.037 28676 28676 D Python  : Native invocation 511594544624 :: afterTextChanged
06-25 00:41:56.037 28676 28676 E Python  : Traceback (most recent call last):
06-25 00:41:56.037 28676 28676 E Python  :   File "/data/user/0/what.ever.acc_companion/files/python/user_code/app_packages/rubicon/java/api.py", line 45, in dispatch
06-25 00:41:56.037 28676 28676 E Python  :     val = getattr(pyinstance, method)(*args)
06-25 00:41:56.037 28676 28676 E Python  :   File "/data/user/0/what.ever.acc_companion/files/python/user_code/app_packages/toga_android/widgets/textinput.py", line 24, in afterTextChanged
06-25 00:41:56.037 28676 28676 E Python  :     self.interface.on_change(widget=self.interface)
06-25 00:41:56.037 28676 28676 E Python  :   File "/data/user/0/what.ever.acc_companion/files/python/user_code/app_packages/toga/handlers.py", line 55, in _handler
06-25 00:41:56.037 28676 28676 E Python  :     result = handler(interface, *args, **kwargs)
06-25 00:41:56.037 28676 28676 E Python  :   File "/data/user/0/what.ever.acc_companion/files/python/user_code/app/acc_companion/utils.py", line 34, in wrapper
06-25 00:41:56.037 28676 28676 E Python  :     return func(*args, **kwargs)
06-25 00:41:56.038 28676 28676 E Python  :   File "/data/user/0/what.ever.acc_companion/files/python/user_code/app/acc_companion/app.py", line 109, in energy_changed
06-25 00:41:56.038 28676 28676 E Python  :     if field.validate():
06-25 00:41:56.038 28676 28676 E Python  :   File "/data/user/0/what.ever.acc_companion/files/python/user_code/app_packages/toga/widgets/textinput.py", line 172, in validate
06-25 00:41:56.038 28676 28676 E Python  :     for validator in self.validators:
06-25 00:41:56.038 28676 28676 E Python  :   File "/data/user/0/what.ever.acc_companion/files/python/user_code/app_packages/toga/widgets/textinput.py", line 132, in validators
06-25 00:41:56.038 28676 28676 E Python  :     return self._validators
06-25 00:41:56.038 28676 28676 E Python  : AttributeError: 'TextInput' object has no attribute '_validators'
```

The problem seems to be that the `on_change` callback method is called *before* the [validators are set](https://github.com/beeware/toga/blob/8b5f4392e16f45240da1dcd25120238a38fb92b8/src/core/toga/widgets/textinput.py#L51). I suspect that this `on_change` callback happens as part of [`self._create()`](https://github.com/beeware/toga/blob/8b5f4392e16f45240da1dcd25120238a38fb92b8/src/core/toga/widgets/textinput.py#L43) but I don't see why that would happen or why it is necessary (on Linux I don't observe this behavior); hence I suspect it's a bug.

**To Reproduce**

1. Create a text input field `field = toga.TextInput(on_change=my_callback, validators=['x'.__eq__])` where `my_callback` is defined as: `def my_callback(field): print(field.validate())`.
2. The crucial point here is that `field.validate()` is called inside the `on_change` callback (which seems to be invoked when the object is created).

**Expected behavior**

The `on_change` callback should not be called when the text input object is created.

**Environment:**
 - Operating System: Ubuntu 20.04 / Android 10
 - Python version: 3.9
 - Software versions:

```
arrow==1.1.0
binaryornot==0.4.4
briefcase==0.3.5
certifi==2021.5.30
chardet==4.0.0
click==8.0.1
cookiecutter==1.7.3
gbulb==0.6.1
gitdb==4.0.7
GitPython==3.1.17
idna==2.10
Jinja2==2.11.3
jinja2-time==0.2.0
MarkupSafe==2.0.1
mypy-extensions==0.4.3
poyo==0.5.0
pycairo==1.20.1
PyGObject==3.40.1
python-dateutil==2.8.1
python-slugify==5.0.2
requests==2.25.1
six==1.16.0
smmap==4.0.0
text-unidecode==1.3
toga-core==0.3.0.dev27
toga-gtk==0.3.0.dev27
toml==0.10.2
travertino==0.1.3
typed-ast==1.4.1
typing-extensions==3.7.4.2
urllib3==1.26.5
```

**Comment by paulproteus** [comment]
@freakboy3742 I was able to reproduce this issue. The impact appears low: an exception is logged, but further validation appears to work properly. I'd love your input on if the validator should be called during `create()`? If so, changing 

## Big picture question

@Dominik1123 raises a good question: Should the validator be called during `create()`?

If so, I think we should move https://github.com/beeware/toga/blob/8b5f4392e16f45240da1dcd25120238a38fb92b8/src/core/toga/widgets/textinput.py#L51 so that it's before https://github.com/beeware/toga/blob/8b5f4392e16f45240da1dcd25120238a38fb92b8/src/core/toga/widgets/textinput.py#L43

## Android implementation & iOS comparison

In Android, we're doing something pretty simple - setting a `textChangedListener` in `create()`:

https://github.com/beeware/toga/blob/8b5f4392e16f45240da1dcd25120238a38fb92b8/src/android/toga_android/widgets/textinput.py#L33

The iOS code seems to do the same:

https://github.com/beeware/toga/blob/8b5f4392e16f45240da1dcd25120238a38fb92b8/src/iOS/toga_iOS/widgets/textinput.py#L27

I haven't confirmed that the validator runs on create with iOS. @freakboy3742 is that something you're willing to test? 

## Why this exception is unimportant in the Android case

The exception happens in a `afterTextChanged` callback. The Java `afterTextChanged` callback runs the user-provided Python code, which raises an exception. Control returns to Java peacefully. Further Python code runs properly. Therefore I think there's no substantial downside other than a sad message in the log.

Here's my log output.

```
06-29 22:18:03.341  5418  5418 D Python  : Native invocation 3412753292 :: afterTextChanged
06-29 22:18:03.342  5418  5418 E Python  : Traceback (most recent call last):
06-29 22:18:03.342  5418  5418 E Python  :   File "/data/user/0/com.example.repro.repro/files/python/user_code/app_packages/rubicon/java/api.py", line 45, in dispatch
06-29 22:18:03.342  5418  5418 E Python  :     val = getattr(pyinstance, method)(*args)
06-29 22:18:03.342  5418  5418 E Python  :   File "/data/user/0/com.example.repro.repro/files/python/user_code/app_packages/toga_android/widgets/textinput.py", line 24, in afterTextChanged
06-29 22:18:03.342  5418  5418 E Python  :     self.interface.on_change(widget=self.interface)
06-29 22:18:03.342  5418  5418 E Python  :   File "/data/user/0/com.example.repro.repro/files/python/user_code/app_packages/toga/handlers.py", line 55, in _handler
06-29 22:18:03.342  5418  5418 E Python  :     result = handler(interface, *args, **kwargs)
06-29 22:18:03.342  5418  5418 E Python  :   File "/data/user/0/com.example.repro.repro/files/python/user_code/app/repro/app.py", line 9, in my_callback
06-29 22:18:03.342  5418  5418 E Python  :     print(field.validate())
06-29 22:18:03.342  5418  5418 E Python  :   File "/data/user/0/com.example.repro.repro/files/python/user_code/app_packages/toga/widgets/textinput.py", line 172, in validate
06-29 22:18:03.342  5418  5418 E Python  :     for validator in self.validators:
06-29 22:18:03.342  5418  5418 E Python  :   File "/data/user/0/com.example.repro.repro/files/python/user_code/app_packages/toga/widgets/textinput.py", line 132, in validators
06-29 22:18:03.342  5418  5418 E Python  :     return self._validators
06-29 22:18:03.343  5418  5418 E Python  : AttributeError: 'TextInput' object has no attribute '_validators'
06-29 22:18:03.343  5418  5418 D Python  : Native invocation done.
06-29 22:18:03.344  5418  5418 I Python  : [Android] Not implemented: TextInput.set_error()
06-29 22:18:03.344  5418  5418 I Python  : [Android] Not implemented: TextInput.set_on_lose_focus()
06-29 22:18:03.344  5418  5418 I Python  : [Android] Not implemented: TextInput.set_on_gain_focus()
06-29 22:18:03.345  5418  5418 I Python  : [Android] Not implemented: Widget.set_hidden()
```

## Code sample

I wrote a sample app to repro this. You can run the sample app if you like.

```
git clone https://github.com/paulproteus/toga-issue-1290
python3.7 -m venv env
env/bin/pip install -r requirements.txt
cd repro
briefcase update android -d && briefcase build android && briefcase run android -d @beePhone
```

**Comment by freakboy3742** [comment]
`validators` are a static list, so from a purely configuration perspective, it shouldn't matter where they are set up. The only reason it *might* matter is because of what will actually be validated. What is the content being validated during initial setup? 

I'm wondering if this is actually masking a deeper problem - that we're seeing change/validation messages associated with setting up the widget. This class of validation shouldn't be performed for initial widget configuration, so the bug here is actually that the validator is being invoked at all, rather than the fact that the validators haven't been set yet.

**Comment by otaj** [comment]
Sorry to piggyback on the old issue, but it is obvious what is happening:
In here,
https://github.com/beeware/toga/blob/090370a943bdeefcdbe035b1621fbc7caeebdf1a/src/core/toga/widgets/textinput.py#L50-L53
you are setting an initial value - and that triggers
https://github.com/beeware/toga/blob/090370a943bdeefcdbe035b1621fbc7caeebdf1a/src/core/toga/widgets/textinput.py#L99-L105
regardless of the value. But by that time, validators are not set up yet.

So I would say there are two things that should be done:
* move setting initial value to the end of `__init__`, 
* in all the setters, I would completely ignore `None` (and not pass them to the implementation)
