### ISSUE TITLE
Documentation appears outdated

### ISSUE THREAD

**Issue by bergus** [beeware/toga#1358]
I'm not a frequent pythonista, and while the project's goals look favourable, I was trying to judge how alive the project before investing the time to try out and learn yet another GUI framework.
While the community appears healthy (but having more [unanswered questions](https://github.com/beeware/toga/discussions) than answered ones) and there are a lot of commits on Github, two things threw me off:
* [The docs pages](https://toga.readthedocs.io/en/latest/index.html) have "*© Copyright 2013*" in the footer. Looks like no update since then…
* [The release history](https://toga.readthedocs.io/en/latest/background/releases.html) has no dates either, making it hard to evaluate

Could you fix these please?

**Comment by freakboy3742** [comment]
Copyright is asserted by stating the date the content was first copyrighted. You can confirm this by looking at the copyright page of *any* book.

As for the other suggestions - are you volunteering to help? We're well aware there are many things that need to be addressed - documentation, features, and more. This is an open source project, run using the donated resources of volunteers. If you want to volunteer to help, please do so. 

If you're not offering to volunteer, and you're not happy with the quality of the project, then I'll gladly return 100% of your purchase price.

**Comment by bergus** [comment]
I guess books are quite different, as their content never changes. For dynamic web content, it seems customary to state something like "*© Copyright 2013 - 2021*".

As for the release notes, I'd be happy to open a pull request, but can you tell me where to find the dates of the releases?

And no, I'm not unhappy with the quality of the project, I'm trying to offer feedback for a project that seems worthy to support. If issue reports are not welcome, I'll stop writing them.

**Comment by freakboy3742** [comment]
You may have noticed that many people who write software are not copyright lawyers. "Convention" isn't worth a hill of beans, because the law doesn't care what the "convention" is. It cares what the law says. Every indication I've seen says that a starting date copyright assertion is sufficient, and doesn't require annual updates.

As for bug reports - they're definitely welcome - but they need to be *specific* and *actionable*.

"You should update the copyright header" is specific and actionable; but in this case, it's not required.

However, comments like "You should answer more questions" isn't actionable. There is no condition where we can clearly close the ticket, because there will always be more questions.

We're also resource constrained. The time I've needed to take to address this ticket is time that I'm not doing other things on the project - like answering questions on the discussion forum.

**Comment by SamSchott** [comment]
To chime on the copyright discussion, @bergus might actually have a point here. Copyright is of course independent of any formal notice which is given, it is automatically granted to the author and typically expires, depending on the jurisdiction, within a certain time after publication. If you do give a formal copyright notice, you would therefore want state the year of publication.

Since our documentation is regularly updated, part of it will have been published for the first time this year. 2021 therefore would be the official publication year which marks the start of the copyright for those parts. This is akin to a book which is republished and may state a copyright such as `(c) 2001, 2004, 2006–2007`.

Regarding release dates, @bergus, you can find those in the tags section at https://github.com/beeware/toga/tags.

**Comment by freakboy3742** [comment]
The reason for re-asserting copyright dates is to ensure longevity of the author's claim, especially when they've made updates to the text. However, copyright expiry is "life of author + 70 years" (depending on jurisdiction). The chances of this becoming an actual issue is.... small :-)

**Comment by SamSchott** [comment]
Indeed, I was just nitpicking :)
