### ISSUE TITLE
Add type information for mypy support

### ISSUE THREAD

**Issue by nth10sd** [beeware/toga#1422]
**Is your feature request related to a problem? Please describe.**
Python 3.6 is now EOL, so with the minimum supported Python version at 3.7, we can possibly use `from __future__ import annotations` and start adding type hints for `mypy` support.

**Describe the solution you'd like**
Add type information.

**Describe alternatives you've considered**
There is currently no type information.

**Additional context**
None.

**Comment by freakboy3742** [comment]
Type annotations have been legal syntax since Python 3.0, so the 3.6 lifespan isn't a consideration.

Regardless, type information isn't an inherent and universal good. It *can* be helpful as an enhancement to documentation, but it can also impede readability in some circumstances.

There is a broader conversation that needs to be had here, in the context of the entire project.

I'm closing this for now, on the basis that having the ticket open won't progress this feature at all. If you want to advocate for adding annotations, I suggest starting a discussion on the BeeWare Discord.
