### ISSUE TITLE
FOSS chat?

### ISSUE THREAD

**Issue by kj7rrv** [beeware/toga#1423]
Would it be possible to have the Discord chat bridged to a free and open protocol such as Matrix or IRC?

**Comment by freakboy3742** [comment]
Short answer: We're unlikely to do this.

As a project, we value practicality over purity. When it comes to chat clients, the practicality of using a closed source solution like Discord vastly exceeds the benefits of a "pure" FLOSS solution. 

We've recently migrated from a FOSS chat server (Gitter, which is now effectively Matrix) specifically because of the end-user experience of those tools (and especially the clients). Introducing a bridge would require time to set up and maintain; and, at the end of the day, won't result in a seamless experience, because there are a lot of features of Discord that have no analog in IRC.

**Comment by kj7rrv** [comment]
Okay. I can't commit to this, but if I hosted the bridge on my own server and took on the responsibility for maintaining it, would you consider allowing that?

**Comment by freakboy3742** [comment]
I guess what I'm not understanding is why this is needed at all. Discord works. It's available to use at no cost. It's used by a large number of open source communities, and there haven't been any particular reasons (that I've heard of) to question the operation of the Discord company. They are paying attention to issues like community moderation, and they've got a clear non-advertising financial model for providing the technical support necessary for the service they provide, so there's no immediate risk of them selling personal data.

Why would we want to add to this an ad-hoc, self hosted bridge to an IRC experience that badly mirrors part of the feature set of the Discord server?

**Comment by kj7rrv** [comment]
My concern is because Discord's official clients are closed source, and they do not allow the development of third-party clients. The terms of service say this:

"You agree not to (and not to attempt to) (i) use the Service for any use or purpose other than as expressly permitted by these Terms;(ii) copy, adapt, modify, prepare derivative works based upon, distribute, license, sell, transfer, publicly display, publicly perform, transmit, stream, broadcast, attempt to discover any source code, reverse engineer, decompile, disassemble, or otherwise exploit the Service or any portion of the Service, except as expressly permitted in these Terms; "

While I would prefer the server and official clients to be open source, my concern is that discord does not allow open source clients to be created.

I would probably bridge it to Matrix, not IRC. As far as I know, Matrix has a similar feature set to Discord.

**Comment by freakboy3742** [comment]
I can certainly understand the desire to be able to pick your own client; if nothing else, it would be nice to demonstrate one written in Toga. 

What I need to see to be convinced is the user experience. I'm on a Discord that is bridged from Slack (for reasons), and while the feature sets of Discord and Slack are nominally equivalent, the end-user experience is awful. There are all sorts of features that don't make the bridge, and every message that a bridged user posts is labelled as a bot on Slack... because from the perspective of Slack, it is.

While I'm sympathetic to the BYO-client request, I'm not eager to support that requirement to the detriment of the experience of every other user on the Discord. Can you point me at an example of a Discord that is bridged to Matrix so that I can see what we'd end up with?

**Comment by kj7rrv** [comment]
The Pine64 chats are bridged to Discord, Matrix, IRC, and Telegram. http://wiki.pine64.org/ the messages do show as coming from a bot.
