### ISSUE TITLE
BoxGrid Container

### ISSUE THREAD

**Issue by nuclearfall** [beeware/toga#1434]
I'd love to see a Grid Container that accepts rows and columns as arguments and generates a Grid of row, column indexed Boxes.

I can always create a Grid but it does seem like it could be a useful widget to come stock.

Basically: Yo dawg, I heard you like boxes, so I got you some boxes for your boxes so you can put boxes in your boxes.

**Comment by freakboy3742** [comment]
@nuclearfall Thanks for the suggestion; however, we're unlikely to adopt this approach as suggested.

However, an approach we *are* likely to adopt is CSS3-like grid layout. 

Toga's layout is intentionally "CSS Like", for the same reason that HTML is - separating content from presentation.

The style language that is built in (Pack) is a kind of "CSS lite". The long game is to replace Toga's builtin style language with a full CSS implementation (see [Colosseum](https://github.com/beeware/colosseum)). The hope is that eventually, we'll support the full specification of Flex and Grid layouts.

As an interim measure, I'd definitely be interested in seeing "Grid lite" added to Pack, if it can be accommodated easily.

**Comment by nuclearfall** [comment]
Oh, I'd definitely rather see CSS styling. So, any work that might be put into an interim solution, I think is better spent on implementation of CSS styling.

This is a newbish question, but is it possible to add row col attributes to Widgets and Canvas contexts, or do I need to subclass?

**Comment by freakboy3742** [comment]
It's not garbage - but it's such a simple implementation I don't really see why we would add it as a built-in widget. This whole implementation can be replaced with:
```
def createGrid(rows, cols):
    return toga.Box(children=[
        toga.Box(children=[toga.Box() for c in range(cols)])
        for r in range(rows)
    ])
```

Your Grid "class" isn't really doing anything more than being a container for a factory method. It isn't a widget because because it's not descended from toga.Widget or toga.Box - so you've got a "Grid"-factory that sits in parallel to the widget layout.

You could possibly make the changes needed to make Grid a widget, and then add some accessors like `__getitem__`; but even if you did that, by itself, this won't build a grid. It will build multiple rows of boxes. It will only be a grid if each of the innermost child boxes has the same width enforced. Without `width` or `flex` definitions, there's nothing about the "grid" that will render as "grid-like".

So - 

If you're interested in adding Grid capabilities to the Pack style engine, the entire implementation is [here](https://github.com/beeware/toga/blob/master/src/core/toga/style/pack.py), with tests [here](https://github.com/beeware/toga/blob/master/src/core/tests/style/test_pack.py). A primer on CSS3 Grids can be found [here](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout) - but I wouldn't a "Pack grid" to be a full implementation of that specification.

**Comment by nuclearfall** [comment]
Yes, my current implementation is definitely pseudo-grid. I will use Pack to create a grid and see if I can contribute anything useful in that respect.

**Comment by freakboy3742** [comment]
Closing on the basis that the real fix here is building out Colosseum.
