### ISSUE TITLE
I'm not sure if this is a bug

### ISSUE THREAD

**Issue by xiaoqiangclub** [beeware/toga#1480]
## Briefcase BUG ?
- Today, I used briefcase to package the application, but the packaged MSI application cannot be used normally, and an error was reported when I used [briefcase run] to start the application: [Unable to start app autotasks].   However, using the [briefcase dev] can start the program normally
- After a bit of experimentation, I found that it was because I had imported Tkinter and win32con win32gui into my code. Of course, I had added Tkinter and PyWin32 to the pyproject.toml file.  Now I am not sure whether this is a BUG of Briefcase or something wrong with my own operation.  So, request answer here, thank you!

**Comment by freakboy3742** [comment]
This report deals with Briefcase, not Toga, so you've opened an issue in the wrong repository

However, that doesn't really matter, because tkinter isn't a GUI platform that Briefcase currently supports. Your app works under `briefcase dev` because that uses your development environment's Python; the app packaged by Briefcase (which is what runs as `briefcase run` uses a standalone Python that doesn't support tkinter.

It would be, in principle, possible to extend Briefcase to support tkinter; however, that's not something that is currently on our roadmap.

**Comment by xiaoqiangclub** [comment]
OK, but it's not good to import win32gui and win32con, which are both modules of pywin32. Using the command briefcase dev can be used normally, but using the command briefcase run will report an error

**Comment by xiaoqiangclub** [comment]
> 

OK, but it's not good to import win32gui and win32con, which are both modules of pywin32. Using the command briefcase dev can be used normally, but using the command briefcase run will report an error...
