### ISSUE TITLE
open_file_dialog return object instead path string 

### ISSUE THREAD

**Issue by matteotanghe** [beeware/toga#1483]
**Describe the bug**
If I want to have a path with the function  `open_file_dialog` or `select_folder_dialog` it returns to me, the object.

**To Reproduce**
When I call `open_file_dialog(),` in my case, it return something like `<toga_gtk.dialogs.OpenFileDialog object at 0x7f5e96c373c8>`
Do I made something wrong ?
I make the function call like that :
`self.filename = self.main_window.open_file_dialog("title", initial_directory=None, multiselect=True, file_types=['png', 'jpg'])
 print(self.filename)`

**Expected behavior**
If I read the doc, normally the function `open_file_dialog(title, initial_directory=None, file_types=None, multiselect=False, on_result=None)`returns a string, in this case, the path. And this is what I need.

**Environment:**
 - Operating System: Linux Ubuntu 
 - Python version: Python 3.6.9
 - Software versions: 
   - Briefcase: 0.3.6

It's little bit strange, maybe I made something wrong, but normally I easy the retrieve a path and I don't understand why it doesn't return me the same thing that the documentation.

**Comment by samschott** [comment]
@matteotanghe, you are not doing anything wrong, this is a shortcoming of the current documentation. The dialog methods all create the dialog and then immediately return a dialog object, such as `<toga_gtk.dialogs.OpenFileDialog object ...>` on Gtk. This means: they return *before* the user actual interacts with the dialog to select a file, click a button, etc., so that the method does not block the execution of the program.

You can await the returned object to get the actual result, in your case a string -- if you created the dialog inside a function defined with `async def`. For example:
```Python
async def select_file(self):
    path = await self.open_file_dialog()
    print("User selected:", path)
```
See https://docs.python.org/3/library/asyncio.html if you're not yet familiar with async programming in Python.

Alternatively, you can provide a function which will be called with the resulting path once the user has selected a file:
```Python
def print_path(window, path):
    print("User selected:", path)

def select_file(self):
    self.open_file_dialog(on_return= print_path)
```

@freakboy3742, I was expecting exactly such reports to come up after reading through #1464 :)

**Comment by matteotanghe** [comment]
> 

Thank you, @samschott, I understand better now, how it's works and why :) . 
Have a good day

**Comment by freakboy3742** [comment]
@samschott Yeah - it was somewhat inevitable; but also an unavoidable consequence of moving to async dialogs. 

@matteotanghe Thanks for the report; I'll leave this ticket open as a marker that the docstrings need to be updated.
