### ISSUE TITLE
Improve horizontal alignment options

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#1544]
[Moved to #1194]

**Comment by freakboy3742** [comment]
To be clear - while we might be able to repurpose `text_align` to perform centering, I'm not 100% sure `text_align` is the right fix here. 

Convergence on a subset of CSS is definitely the preferred solution, though; the current formal specification of the Pack algorithm would be much better as a specification of the subset of CSS flags we honour, and the conditions under which we honour them. The Pack specification should be *mostly* this at present (it should *mostly* map to CSS3 flexbox, with the removal of any line splitting rules) - but there are clearly areas that we are missing, because horizontal centering can be handled by flexbox.

**Comment by shape-warrior-t** [comment]
My understanding is that currently, the final width of a row box with children is always the sum of its children's full widths, and same thing with the column boxes in the other dimension.

In other words, right now, every row box is _always_ left, center, _and_ right aligned already, and same with the column boxes and vertical alignment.

So in order to implement this, we'll probably have to change how we determine the final width of a parent element. A change that may or may not be backwards-compatible, depending on how we go about it.

And if we change how the final width of a parent element is determined, we might also want to do the same thing with the final height. Right now, as far as I can tell, the final height of a row box is always the maximum of its children's full heights, and same with column boxes and width. I don't think the behaviour described in https://github.com/beeware/toga/issues/1194#issuecomment-1196333463 is actually a bug under current specifications -- if you have a row box with one child, then the final height of the row box will always be the same as the child's full height, so the row box will _always_ already be top, center, and bottom aligned.

(I just noticed -- the documented Pack algorithm doesn't actually say what the final height of a parent row box / final width of a parent column box is! So... maybe it actually _is_ a bug...?)

My brain currently needs a break from thinking, so I'm not going to propose anything right now. Maybe later. Just wanted to bring this issue up, because I think it's probably important.

**Comment by shape-warrior-t** [comment]
OK, one potential idea: CSS uses `align-items` for cross axis alignment and `justify-content` for main axis alignment, so maybe we could copy them with `alignment` (existing) and `justify` or `justification` or something along those lines (new property).

**Comment by freakboy3742** [comment]
As I said in my previous comment, my preferred approach here is *not* to introduce new properties, or custom interpretations - but to converge on a true "minimal CSS" interpretation - that is, a set of rules that are 100% consistent with true CSS, or have a 1-1 mapping with true CSS. Essentially, I would like to be able to answer any "is this a bug in Pack?" questions with "what does a HTML render of the same code do?".
