### ISSUE TITLE
Visible property for windows

### ISSUE THREAD

**Issue by notzippy** [beeware/toga#1553]
In order to implement `hide to systray` a window needs to have the ability to be hidden

I've implemented my own solution for windows, mac, linux like this (assuming self is the toga.app), obviously reaching into the protected attributes is not natural but this could be useful as a high level toga.window property and implemented correctly at each implementation.
```
    @property
    def visible(self):
        return self._visible

    @visible.setter
    def visible(self, value):
        if value != self._visible:
            self._visible = value
            system = str(platform.system()).lower()
            if system == 'darwin':
                self.main_window._impl.native.setIsVisible(value)
            elif system == 'win32':
                if value:
                    self.main_window._impl.native.Show()
                else:
                    self.main_window._impl.native.Hide()
            elif system == 'linux':
                if value:
                    self.main_window._impl.native.show()
                else:
                    self.main_window._impl.native.hide()
```

I've considered moving the window off screen and such but it becomes a bit of a kluge fix. I've also considered hijacking the main_loop and implementing something custom which doesn't show the main window (made things worse)

This could also be ported to a mobile device by transferring to a run in the background.

**Comment by freakboy3742** [comment]
Thanks for the suggestion. System tray widgets are a long standing wishlist item (#97); we definitely want to address that.

This proposal isn't *directly* about tray widgets though; it's about window visibility. I'm in favour of the general idea you're proposing around visibility; but I'd suggest a 3 small changes to the design:
1. I'd argue visibility is a feature of a *window*, not the *app*. 
2. You're using a proxied attribute on the app to store window visibility state. Our preference is to use "ground truth" wherever possible - i.e., ask the native platform what *it* thinks the visibility state is, rather than storing an attribute describing what the Python app thinks the visibility state is (which could get out of sync with reality). This is usually abstracted behind a "get_" method on the backend that calls on native APIs (e.g., `window.visible` on macOS).
3. You've used a `visible = True/False` property setter to control window visibility. We already have a `show()` method; a `hide()` would be the obvious candidate name for the complementary behavior. That said, since we're going to have a `visible` getter property, I guess there's no harm in having a `setter` that is effectively an "if True: show() else: hide()" implementation.

There is one other detail that I'd raise in the context of systray widgets specifically. The idea of a "systray app" is a common one, but that isn't currently served well by Toga. Toga currently has 2 base app classes:
1. `toga.App`, which *must* have a main window, and may have additional windows; the application exits when the main window is closed
2. `toga.DocumentApp`, which has one window per "document" being opened. On macOS, this results in a single app instance that opens multiple document windows; on Linux/Windows, each app instance manages a single document.

To support systray apps, we may need to add a `toga.WindowlessApp` - an app that doesn't require a main window at all  (I'm open to suggestions on a better name). That will require a separate way to manage app lifecycle, and may need some additional tooling to hide the app's "main" icon (e.g., macOS apps will appear on the Dock even if they don't have a window). A systray representation is then a feature that can be added to *any* app, in the same way that a toolbar can be added.

**Comment by notzippy** [comment]
Yes, I agree that the two subjects' visibility and systray app is best to keep separate. I was presenting the reasoning behind my need for it - I had looked over the issue #97 and it is a complex issue depending on the system.

Maybe break this ticket into two separate features -

1) Window visibility. Definitely agree this would be a function of the Window class with an option to disable this feature from the main. I wasn't sure if the `window.show` function is 100% compatible with the `window.visible = True` command. Natively it appears the former does extra work. 

2) I would go for a name like `toga.ServiceApp` apps running in the background only are typically labeled as a service (and possible it would tweak me less :-D ) Overall that would be an great starting point as well. Maybe break this into two tickets to address each feature. The service would need a thread model that has the ability to create a new window without locking it up. (I ran into an issue on windows where I had a different thread update a text field and it locked the entire UI.)

**Comment by freakboy3742** [comment]
Agreed this is 2 underlying issues; let's keep this ticket for the visibility API discussion, and systray stuff on #97.

The "extra" work being done by show is mostly about forcing a relayout of the window; that's likely a no-op (or close to it) if the window has already been displayed and hidden, but it can't hurt to do another relayout. If the layout hasn't changed, the layout calculations should essentially be a no-op.

The threading issue is something that is Windows specific. The lifecycle of Windows apps is a little odd, as there's a bunch of stuff that doesn't happen (especially in asyncio support) until there's a Form present to handle window events; and even then, you can't post GUI events from a non-GUI thread. That's a fairly common restriction for GUIs; and there are some patterns you can use to address it.

**Comment by saroad2** [comment]
I'm on it.
