### ISSUE TITLE
App don't crash with uncaught exception

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#1580]
**Describe the bug**
When I raise an exception on `Button.on_press` method on Windows, a stack trace is printed but the application does not crash.
This is a little bit confusing: Who's catching this exception? why I can press the other buttons and the application is just fine?

**To Reproduce**
1. Go to the button example
2. Replace `App.callback_text` method implementation with a simple `raise ValueError()` statement
3. Run the app
4. Click the "change text" button
5. See that a stack trace is printed to the console
6. Try to press any other button and see that it works just fine.

**Expected behavior**
I think that once an except is raised and is uncaught, it should crash the app, maybe with an error dialog.
Whatever we choose, this behavior should be consistent in all platforms.

**Environment:**
 - Operating System: Windows
 - Python version: 3.10
 - Software versions:
   - Briefcase: Latest
   - Toga: Latest
   - ...

**Comment by freakboy3742** [comment]
This is expected behaviour (and, AFAIK, is consistent across platforms; if it isn't, *that* is a bug). Part of the exception handling is being done [here](https://github.com/beeware/toga/blob/main/src/core/toga/handlers.py#L76) - although, it's also partially handled by the widget framework itself, which treats errors in event handlers as "soft" errors.

The intention behind this behavior is to make the app resilient to problems that are at recoverable. A hard app crash is the least desirable outcome for any problem; by logging the problem but preserving the app, it's possible to provide diagnostic information, but leave the app in a "working" state (or as close to working as possible).
