### ISSUE TITLE
Implement Brython as js transpilation backend in Toga

### ISSUE THREAD

**Issue by olemis** [beeware/toga#159]
... as an alternative to [Batavia](https://github.com/pybee/batavia) and also for devices implementing JS APIs like [Tizen OS](https://www.tizen.org/) , etc ... long list indeed

**Comment by freakboy3742** [comment]
"Brython" isn't really a backend in the context of Toga, because it's not a platform. The Web is a platform (rendered as Django, Flask, etc); we'll obviously need some way to get client-side python code to run, but that's an internal detail for the web backend, rather than being a whole new backend.
