### ISSUE TITLE
toga.ImageView doesn't show anything when it is not a child of the top container(i.e. toga.MainWindow.Content)

### ISSUE THREAD

**Issue by raj248** [beeware/toga#1745]
### Describe the bug

There is no image showing Even if it takes the space of ImageView 

### Steps to reproduce

    import toga
    from toga.style import Pack
    
    class Image(toga.App):
	    def startup(self):
		    self.main_window = toga.MainWindow(title="Image")
		    content_box = toga.Box()
    
		    image = toga.ImageView(toga.Image('./swallow_image.jpg'),style=Pack(height=80)),
		    in_box = toga.Box()
		    in_box.add(image[0])
		    content_box.add(in_box)
    
		    self.main_window.content = content_box
		    self.main_window.show()
		    pass
    
  
          Image("Image","implement.image").main_loop()

### Expected behavior

It should show the Image I'm trying to display

### Screenshots

![image](https://user-images.githubusercontent.com/65160099/213136147-cced89ea-474e-4192-ad4b-97036568ed7a.png)

### Environment

- Operating System: Ubuntu 20.04.5 LTS
- Python version: Python 3.8.10
- Software versions:
  - Briefcase: Not installed
  - Toga:Version: 0.3.0.dev39

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report. It's no immediately clear if this is an issue with Image, or an edge case in the Pack layout algorithm.

The current problem is that you've got a row box in a row box. Row boxes collapse to be as thin as possible, and because you haven't specified a width, that's collapsing the inner box to a width of 0. In the absence of an explicit width, it *should* be fixing a minimum width - but for some reason, that's not being honored.

There are 2 immediate workarounds:
1. Add a explicit `width` to the image; or
2. Modify `content_box` to be a column box (i.e., `content_box = toga.Box(style=Pack(direction=COLUMN))`)

(Unrelated: you might also want to remove the stray comma from the end of the line defining the image - that's the reason you need to use `image[0]` when adding it to the box).
