### ISSUE TITLE
Android `intent_result` is not documented

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#1798]
#1217 added an Android-specific `intent_result` method, but it isn't documented. Normally we wouldn't document anything that uses a private, underscore-prefixed API, but in this case we can't simply tell people "call the standard Android APIs via Chaquopy", because the API for calling Intents is bound up with Toga's Activity class.

The documentation should be something like this:

Once you've created an Intent object, you should `await self._impl.intent_result(intent)`, where `self` is your `App` object.  That will return a dict with two keys: `resultCode` and `resultData`, which correspond to the arguments of the [`onActivityResult`](https://developer.android.com/reference/android/app/Activity#onActivityResult(int,%20int,%20android.content.Intent)) method.

For a complete example, see https://github.com/beeware/toga/pull/1158#issuecomment-1446196973.

**Comment by freakboy3742** [comment]
The fact that it's not documented is at least *partially* intentional; it's an internal API, and most users shouldn't have any need to use it. 

However, it's definitely a detail of the internal implementation that warrants documentation, as anyone wanting to build new Android features needs to know how the MainActivity maps to the Toga implementation.
