### ISSUE TITLE
Android can create multiple `toga.App` object instances in the same process

### ISSUE THREAD

**Issue by proneon267** [beeware/toga#1803]
### Describe the bug

`Toga.App` object's startup method is invoked multiple times automatically in specific cases

### Steps to reproduce

1. Create a default briefcase project
2. Change the app.py file's contents to:
```
"""
My first application
"""
import toga
from toga.style import Pack

startup_counter = 0

class HelloWorld(toga.App):
	
	def startup(self):
		"""
		Construct and show the Toga application.
		
		Usually, you would add your application to a main content box.
		We then create a main window (with a name matching the app), and
		show the main window.
		"""
		
		global startup_counter
		startup_counter += 1
		
		main_box = toga.Box(style=Pack(flex=1,direction="column"))
		startup_label = toga.Label(text=f"Startup Counter: {str(startup_counter)}",style=Pack(font_size=24))
		h_box = toga.Box(style=Pack(flex=1,direction="row"))
		h_box.add(toga.Box(style=Pack(flex=1)),startup_label,toga.Box(style=Pack(flex=1)))
		main_box.add(toga.Box(style=Pack(flex=1)),h_box,toga.Box(style=Pack(flex=1)))
		self.main_window = toga.MainWindow(title=self.formal_name)
		self.main_window.content = main_box
		self.main_window.show()


def main():
	return HelloWorld()
```
3. Now do `briefcase create android` and `briefcase build android`.
4. Run the generated `app-debug.apk` in the following cases:

Physical Device: `Android 10`:

https://user-images.githubusercontent.com/45512885/222951617-fca8a50a-5833-4d96-a39e-89e0a56abff4.mp4

<br>

Windows Subsystem For Android: `Android 13`:

https://user-images.githubusercontent.com/45512885/222950957-9bdd07ab-a6a4-4bf5-a23a-6c0319f89bc1.mp4

<br>

5. The `startup_counter` increases, indicating `startup()` method of `toga.App` object is being invoked.
<br>

However, I was not able to reproduce this behavior when I ran the app in Android emulator:<br>

Android_sdk emulator: `Android 12`

https://user-images.githubusercontent.com/45512885/222952777-5a3aa6bf-4ef1-478f-889c-078bbaf08b78.mp4

<br>

Also this behavior is not reproducible in `Windows` and `Linux`. So it seems to be an `Android` issue only.

### Expected behavior

The `startup_counter` should remain at `1`, but it increases. Hence, indicating `startup()` of `toga.App` object method is being invoked. This can lead to problems, as the code present in `startup()` method will run again. 

For example, if there is http server startup code in `startup()` of  `toga.App` object method, then multiple instances of the server will be created, which is not what the programmer expects.

### Environment

- Operating System: `Android 10, 12, 13` and Host OS: `Windows` for `WSA`, `Android 10` for `Physical Device`, `Linux` for `Android 12 Emulator`
- Python version: `3.8.16`
- Software versions:
  - Briefcase: `0.3.12`
  - Toga: `0.3`

### Logs

```

```

**Comment by proneon267** [comment]
On further inspection and changing the code to also display class instance counter, it is found that `toga.App` object's `startup()` method is not invoked, rather multiple instance of the Class are being created.

Change code in `app.py`:
```
"""
My first application
"""
import toga
from toga.style import Pack

startup_counter = 0

class HelloWorld(toga.App):
	# Define a class-level variable to keep track of the number of instances
	instance_counter = 0

	def __init__(self, *args, **kwargs):
		# Increment the instance counter each time a new instance is created
		HelloWorld.instance_counter += 1
		super().__init__(*args, **kwargs)

	def startup(self):
		"""
		Construct and show the Toga application.
		
		Usually, you would add your application to a main content box.
		We then create a main window (with a name matching the app), and
		show the main window.
		"""
		global startup_counter
		startup_counter += 1
		main_box = toga.Box(style=Pack(flex=1,direction="column"))
		startup_label = toga.Label(text=f"Startup Counter: {str(startup_counter)}",style=Pack(font_size=24))
		instance_label = toga.Label(text=f"Instance Counter: {str(HelloWorld.instance_counter)}",style=Pack(font_size=24))
		startup_box = toga.Box(style=Pack(flex=1,direction="row"))
		startup_box.add(toga.Box(style=Pack(flex=1)),startup_label,toga.Box(style=Pack(flex=1)))
		instance_box = toga.Box(style=Pack(flex=1,direction="row"))
		instance_box.add(toga.Box(style=Pack(flex=1)),instance_label,toga.Box(style=Pack(flex=1)))
		
		main_box.add(toga.Box(style=Pack(flex=1)),startup_box,instance_box,toga.Box(style=Pack(flex=1)))
		self.main_window = toga.MainWindow(title=self.formal_name)
		self.main_window.content = main_box
		self.main_window.show()


def main():
	return HelloWorld()

```

The behavior remains same as before in all test benches. 
Physical Device: `Android 10`

https://user-images.githubusercontent.com/45512885/222958551-69726267-1128-4da0-a163-0e0308f3ec39.mp4

**Comment by proneon267** [comment]
I tried adding `android:launchMode="singleInstance"` to `AndroidManifest.xml` but it doesn't seem to change anything.

This issue might be arising due to issue #1623. But, I am not entirely sure as it seems to work fine on the `Android 12` Android_sdk emulator.

**Comment by mhsmith** [comment]
In older Android versions (e.g. 24), it would terminate a top-level activity when you pressed the back button, whereas if you left the activity in any other way, it would keep running in the background. I guess they decided this distinction was confusing, because in newer Android versions (e.g. 33), pressing the back button keeps the activity running in the background as well. 

Notes:
* This only applies to top-level activities. Activities which are stacked on other ones will always be terminated when you press back, on all Android versions. But that doesn't currently apply to any Toga apps.
* in all of the above cases, even if the activity is terminated, the OS process continues running until the system decides to kill it to free up memory, and it may be reused if the activity is launched again. This is where Android differs from the other platforms.
* However, if you close the app within the app switcher, the OS process terminates, at least on the emulator.

In the current version of Toga, the lifetime of the App object is tied to that of the Android Activity, and it really has to be this way, because the App `startup` method is responsible for creating the Activity's user interface.

So if your app has resources other than your UI, you have two choices:
* If you want them to persist across multiple Activity instances, store them in global variables.
* If you want them to be tied to the Activity lifetime (which is probably better), you could store them in instance variables and clean them up with the `on_exit` handler – except unfortunately that handler isn't implemented on Android yet. I'll add a note about that to [#1623](https://github.com/beeware/toga/issues/1623).

**Comment by mhsmith** [comment]
> I tried adding `android:launchMode="singleInstance"` to `AndroidManifest.xml` but it doesn't seem to change anything.

That's because `singleInstance` ensures that there's only one instance of the activity *at a time* – which would be the case anyway, in a Toga app.

**Comment by proneon267** [comment]
Thanks for helping! :)
