### ISSUE TITLE
More options for formatting buttons/labels/switches

### ISSUE THREAD

**Issue by Obliman** [beeware/toga#2010]
### What is the problem or limitation you are having?

It's subtle, but I noticed that the buttons I create have slightly rounded corners while the labels have square corners (on both Linux and Android). It would be nice to have some control over this if possible (i.e. size of corner radius).

I've also noticed that the switches seem to ignore my color choices entirely (color and background_color), defaulting to some system-specific color.

Am I missing something in the style settings, or are these features not available (yet)?

### Describe the solution you'd like

- Control of button and label corner shape
- Control of switch colors

### Describe alternatives you've considered

Just accept a lack of control over some elements and try to design around it.

**Comment by freakboy3742** [comment]
A Toga app tries to look like native app. It allows for *limited* customization, but "I want my buttons to look like X" is explicitly contrary to the design goals of Toga. Some inconsistencies between platforms is to be expected, because widgets on different platforms look different. If you don't like the appearance of buttons on your operating system of choice, take that up with the maker of your operating system :-)

Regarding `color` and `background_color` specifically - this is one of the areas where some customisation is possible. Ensuring these APIs work is area where we've been focussing recently, as part of a comprehensive audit of widget functionality and test coverage. However, some widgets *don't* allow for color customisation, and some *platforms* don't allow for color customisation. Switch is a good example of this - macOS doesn't allow any color changes on switch; GTK allows customisation of the switch *label*, but not of the switch "gadget" itself.
