### ISSUE TITLE
toga-android requires Android SDK 24 while it uses a class added in SDK 29

### ISSUE THREAD

**Issue by BishrGhalil** [beeware/toga#2032]
### Describe the bug

toga-android requires API Level 24 as it has been mentioned [here](https://toga.readthedocs.io/en/latest/reference/platforms/android.html)
> toga-android requires Android SDK 24 (Android 7 / Nougat) or newer.

However, I am getting the following error
 `E/AndroidRuntime: Caused by: java.lang.NoClassDefFoundError: android.graphics.text.LineBreaker`
  whenever I try to run the beeware app on an Android device with API Level <29, After some search I found out that the `LineBreaker` class was introduced in API Level 29 as it's mentioned [here](https://developer.android.com/reference/android/graphics/text/LineBreaker)

Additionally, how can I update the toga-android used in my app as soon as the bug is fixed?

### Steps to reproduce

1. Try to run a toga-app on Android <=9

### Expected behavior

toga-android should not contain features from Android SDK 29 while it says it requires Android SDK 24. And apps should just run when there is no errors.

### Environment

- Operating System: Windows
- Python version: 3.10.6
- Software versions:
  - Briefcase: 0.3.15
  - Toga: 0.3.1
  - ...

### Logs

```

```

**Comment by mhsmith** [comment]
This has already been fixed in the development version. See #1878, and in future please search for existing issues before creating new ones.

The fix will be released with the next Toga version, probably in August or September. After that, you can update your app by changing the `toga-android` version in your pyproject.toml file.

Meanwhile, I think the bug was introduced in Toga 0.3.1, so you can avoid it by going back to Toga 0.3.0.

**Comment by mhsmith** [comment]
To use the development version, edit your pyproject.toml file to replace `toga-android` with the following:
```
    "git+https://github.com/beeware/toga#subdirectory=core",
    "git+https://github.com/beeware/toga#subdirectory=android",
```

Then run `briefcase run android -ur`.

On other platforms, replace "android" with the name of the Toga backend or Briefcase platform you're using.
