### ISSUE TITLE
[BUG] AttributeError: 'NoneType' object has no attribute '_impl' on Windows

### ISSUE THREAD

**Issue by DebankaWorld2020** [beeware/toga#2036]
### Describe the bug

I am developing a Toga-based application that involves recording audio on multiple platforms. I encountered an error when trying to run it on a Windows system. The issue appears to be specific to the Windows platform.

I want to use the on_result handler for Toga's dialogs, we need to define a callback function that will be called when the dialog is closed and the result is available. The on_result handler is used with async dialogs, and it allows us to perform actions after the dialog is closed and a result is available. So I use this code:
```
async def on_record_button_press(self, widget):
        # Handle record button press
        self.recording_directory = await self.main_window.select_folder_dialog(title='Select Recording Directory')
```

**But it shows following error:**
```
C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\toga_winforms\app.py:126: RuntimeWarning: coroutine 'MainApp.startup' was never awaited
  self.interface.startup()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "e:\VS_Code\Python\test_.py", line 121, in <module>
    app.main_loop()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\toga\app.py", line 563, in main_loop
    self._impl.main_loop()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\toga_winforms\app.py", line 260, in main_loop
    raise self._exception
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\toga_winforms\app.py", line 235, in run_app
    self.create()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\toga_winforms\app.py", line 127, in create
    self.create_menus()
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\toga_winforms\app.py", line 161, in create_menus
    self.interface.main_window._impl.native.Controls.Add(menubar)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_impl'
```

### Steps to reproduce

1. Install the Toga library and its dependencies.
2. Run the Toga application on a Windows system using Python.
3. Click on the button that triggers the on_record_button_press method, which is intended to open a file save dialog and start recording audio.
this the full code:
```
import datetime
import pyaudio
import wave
import threading
import toga
from toga.style import Pack
from toga.style.pack import COLUMN
import os

class MainApp(toga.App):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.recording_count = 0
        self.audio = None
        self.stream = None
        self.frames = []
        self.is_recording = False
        self.lock = threading.Lock()
        self.recording_directory = None  # Default to None, will be set by the user

    async def startup(self):
        # Create a main box layout
        main_box = toga.Box(style=Pack(direction=COLUMN))

        # Create a button for recording
        record_button = toga.Button('Record', on_press=self.on_record_button_press)
        main_box.add(record_button)

        # Create a button for stopping recording
        stop_button = toga.Button('Stop Recording', on_press=self.on_stop_button_press)
        main_box.add(stop_button)

        # Create the main window
        self.main_window = toga.MainWindow(title=self.formal_name, size=(400, 200))

        # Set the content of the main window
        self.main_window.content = main_box

        # Show the main window
        self.main_window.show()

    def on_record_button_press(self, widget):
        # Handle record button press
        self.main_window.select_folder_dialog(title='Select Recording Directory', on_result=self.on_folder_dialog_result)

    def on_folder_dialog_result(self, widget, folder):
        # Callback function for folder dialog result
        if folder:
            self.recording_directory = folder
            self.main_window.save_file_dialog(
                title="Save Recording",
                default_extension="wav",
                file_types=["Wave File (*.wav)"],
                on_result=self.on_file_dialog_result
            )

    def on_file_dialog_result(self, widget, file_path):
        # Callback function for file dialog result
        if file_path:
            self.recording_directory = file_path
            self.start_recording()

    def start_recording(self):
        # Handle record button press
        self.recording_count += 1
        # Generate a unique name for the recording based on the current time and recording count
        recording_name = f'recording_{datetime.datetime.now().strftime("%Y%m%d%H%M%S")}_{self.recording_count}.wav'
        recording_location = os.path.join(self.recording_directory, recording_name)

        # Initialize PyAudio
        self.audio = pyaudio.PyAudio()

        # Set recording parameters
        format = pyaudio.paInt16
        channels = 1
        sample_rate = 44100
        frames_per_buffer = 1024

        # Open the audio stream
        self.stream = self.audio.open(format=format,
                                      channels=channels,
                                      rate=sample_rate,
                                      input=True,
                                      frames_per_buffer=frames_per_buffer)

        print(f'Recording {recording_name} started...')
        self.is_recording = True
        threading.Thread(target=self.record).start()

    def record(self):
        while self.is_recording:
            with self.lock:
                data = self.stream.read(1024)
                self.frames.append(data)

    def on_stop_button_press(self, widget):
        # Handle stop button press
        if self.stream is not None and self.is_recording:
            self.is_recording = False
            # Stop the recording stream
            self.stream.stop_stream()
            self.stream.close()

            # Terminate PyAudio
            self.audio.terminate()

            # Save the recorded audio to the specified location
            recording_name = f'recording_{datetime.datetime.now().strftime("%Y%m%d%H%M%S")}_{self.recording_count}.wav'
            recording_location = os.path.join(self.recording_directory, recording_name)
            with wave.open(recording_location, 'wb') as wave_file:
                wave_file.setnchannels(1)
                wave_file.setsampwidth(self.audio.get_sample_size(pyaudio.paInt16))
                wave_file.setframerate(44100)
                wave_file.writeframes(b''.join(self.frames))

            print(f'Recording {recording_name} stopped and saved.')

        else:
            print('No recording in progress.')

if __name__ == '__main__':
    app = MainApp('Recording App', 'com.example.recording')
    app.main_loop()

if __name__ == '__main__':
    app = MainApp('Recording App', 'com.example.recording')
    app.main_loop()

```

4. Observe the error in the console.

### Expected behavior

it will select the desired folder from the pop up window of choosing recording save folder and that loction the recording will be saved. It will be helpful to see this problem and suggest some way explaination. 

### Environment

- Operating System: windows 10 pro
- Python version: 3.11.4
- Software versions:
  - Briefcase:0.3.15
  - Toga:0.3.1
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment]
Thanks for the report. At first inspection, the problem appears to be a problem with your code. You've declared `startup()` as an async method; that isn't currently supported (and may not ever be - the startup method is an entry point where certain guarantees need to be made about code execution). As a result, your startup method isn't a *function*, it's a co-routine - and the co-routine is never scheduled for execution, so the main window is never created. I'm honestly a little surprised you're seeing a main window *at all* - that's likely a platform specific side effect.

The good news is that as far as I can make out, it isn't *required*, either. There's no `await` calls in your startup method - in fact, there's no await calls in your entire app. Yes, you're using dialogs; but you're not *awaiting* the result of those dialogs - you're using the synchronous result callback method. I suspect that if you drop the async declaration on your startup method, the problem will resolve itself.

As an aside - while it's great that you've provided a sample program that reproduces the problem, it's helpful if you reduce the example to a *minimal* example - that is, just the code that is necessary to demonstrate the problem. AFAICT, the problem you're seeing has nothing to do with the interaction with wave or pyaudio - but in order to run your example program, I need to have both those libraries installed (and work out exactly which versions you have installed, as you haven't provided those details either). Reducing example cases to minimal examples is really helpful for us as maintainers, because we don't need to work out what pieces of the problem are your code, and which parts are our code - and, as a diagnostic tool, the act of simplifying an example often leads to insights as to the cause of a problem. I'm not sure that would have happened here, but from my own experience, it's not uncommon for the process of simplifying an example of for a bug report leads to a 🤦 moment when I realise I'm using an API the wrong way, or one of my assumptions isn't actually true.

**Comment by DebankaWorld2020** [comment]
Sorry, For labelling as a Bug report. Currently I am learner in Both App Building and GitHub. So I did some mistake. And Thanks for helping me out for finding the problem and give you valuable time. But the problem is not solved yet. I start looking for the code throughly, but i could not find the desired result. A new problem is shown
"Error in async handler: Window.save_file_dialog() got an unexpected keyword argument 'default_extension".

I could not find the way out. That is why i post it. Thinking that it is bug, and it should be informed. 


Basic thing is that , when i try to save recording to the user defined directory, a window start and when im select the desired directory, it shows this result now. 
![Screenshot (80)](https://github.com/beeware/toga/assets/114228435/7cb87ce5-9538-48ec-baea-154dcb850718)
![Screenshot (81)](https://github.com/beeware/toga/assets/114228435/f5806f2f-d513-4e31-8c98-84c10e0ba94e)
[Test_py.txt](https://github.com/beeware/toga/files/12137094/Test_py.txt)


I am running the code in VS studio.
By the way, It is good app building API. As a python user , i am really enjoying.
Thank You.

**Comment by freakboy3742** [comment]
This is a different problem to the one you were originally reporting; and, as far as I can see, it's another example of user error - and the error message is telling you the exact problem. `save_file_dialog() got an unexpected keyword argument "default_extension"... because "default_extension" isn't a valid argument for `save_file_dialog()`. I don't know what gave you the impression that it is, but the valid arguments for `save_file_dialog` are [documented](https://toga.readthedocs.io/en/stable/reference/api/window.html#toga.window.Window.save_file_dialog), and "default_extension" isn't one of them. 

I'm going to close this ticket on the basis that both problems have been user error. If you have a further problems, can I suggest you start a [discussion](https://github.com/beeware/toga/discussions), or ask on the [BeeWare Discord](https://beeware.org/bee/chat/), rather than opening a bug.
