### ISSUE TITLE
Add an embedded window widget

### ISSUE THREAD

**Issue by leaffeather** [beeware/toga#2078]
### What is the problem or limitation you are having?

Such as matplotlib, VTK, and so on, these libraries usually open an independent window to realize visualization. Sometimes, when writing some programs, I want to bring some existed programs to handle some basic functions without opening separately. It should be pointed out that in the latter, I might use the part of the whole interface. However, I wish there could be a widget to take over such windows and be able to interact normally.

### Describe the solution you'd like

There is currently no alternative method.

### Describe alternatives you've considered

Like iframe in HTML, I wish that toga can add a widget to make the window from other programs embedded in and response the operations normally.

**Comment by freakboy3742** [comment]
Sure. I'd also like it to rain chocolate buttons and snow marshmallows. :-)

Yes, it would be wonderful to be able to embed windows from one app into another app... But that's not how apps *work*. It's *definitely* not possible in a cross-platform way - because there is no "generic" cross-platform API representing a sub-unit of a GUI app. 

FWIW: Matplotlib *doesn't* require anything like this. Matplotlib has rendering backends; [Toga-chart](https://github.com/beeware/toga-chart) is a Matplotlib rendering backend that uses Toga's native canvas API. 

I haven't used VTK, so I can't comment on what it can do. If VTK works cross-platform, it *might* be possible to use VTK as a library, and embed a VTK rendering into a Toga GUI - but that would be a VTK specific widget, based on VTK's specific API, and would require a separate implementation on every platform. It *wouldn't* be a generic Toga capability that could work on the content of an arbitrary app. It also wouldn't be something I'd suggest is appropriate for Toga's core - it could (and should) live as an external library.

Closing on the basis that the idea is fundamentally implausible.
