### ISSUE TITLE
Crash on Android when using lambda expression and list to get the result of confirm_dialog and question_dialog 

### ISSUE THREAD

**Issue by leaffeather** [beeware/toga#2080]
### Describe the bug

As the title says, I would like to reduce the redundancy of the codes about confirm dialogs and question dialogs by lambda expression. The following code runs perfectly on Windows but crashes on Android. 

I also find that the program does not wait my decision on the dialog and continue to execute on Android. However, when I use the provided example, i.e. async and await, it will raise exception and the dialog will not appear on both Windows and Android:
RuntimeWarning: coroutine 'wordgets.cbDeleteWordList' was never awaited Coroutine created at (most recent call last)
....
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

PS. I must use partial/lambda to deliver some parameters to a button's callback as buttons are batch generated, and each button handles different objects, and there is the problematic question dialog in the async callback function.

PPS. 
asyncio.run not work
asyncio.create_task only work at first time, then crash at the next time 
nest_asyncio.apply not work

### Steps to reproduce

**Current solution but not a reasonable one: The callback function uses async keyword. The required parameters deliver through widget.id as a string and the string is parsed back into the required parameters in the callback function**

```
lsQuestionDialogResult = []
self.main_window.question_dialog(title = g_strQuestionDialogTitle, message = g_strQuestionDialogMsg_Delete,\
                             on_result = lambda _wnd, _bQuestionResult: lsQuestionDialogResult.append(_bQuestionResult))
if lsQuestionDialogResult[0] == None or lsQuestionDialogResult[0] == False:
    return
```

### Expected behavior

Please check it.

### Environment

- Operating System: Windows 11
- Python version:3.8.17
- Software versions:
  - Briefcase:
  - Toga:0.3.11
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment]
From what I can make out, based on the code sample you've provided, this appears to be user error, not a bug.

You're invoking a dialog, and then querying a variable that is being set in the on_result handler. That's not how question dialog works - question_dialog is a non-blocking method that *shows* the dialog. If you want to do something *after* the the user has selected an answer in the dialog, that logic either needs to be *entirely* in the `on_result` handler, or you need to `await` the question dialog from inside an asynchronous context (i.e., a handler that is declared `async def`, not `def`). If you want an example of how to use dialogs in practice, see the [dialogs](https://github.com/beeware/toga/blob/main/examples/dialogs/dialogs/app.py#L18) example.

The approach you've taken here *may* work on Windows - but if it does, that's entirely an implementation detail on Windows, and it is an unintentional side effect, not intended behavior. I would also be unsurprised if this behaviour changes as a result of the changes coming soon with #2058.

You've also provided 1 line of a stack trace, describing a co-routine "wordgets.cbDeleteWordList"... but there's no variable named that in your reproduction code, and there's no attempt to await anything in your reproduction code, so it couldn't possibly be generating that error. You're clearly doing something else to generate this error, but it's impossible to say what because you haven't provided a reproduction case that includes asynchronous behavior or a `cbDeleteWordList` variable. The best I can guess is that you *tried* to use `await` with question_dialog, but did in a way that didn't result in the dialog being awaited - but without example code it's impossible to say for certain.

I have no idea what you're trying to convey with your PS and PPS comments. The use of lambda as a callback is entirely unremarkable. As for "asyncio.run not work"... why should it? You shouldn't *ever* need to call `asyncio.run`, because the app is already running in an async context. 

If you have questions about usage of dialogs, might I suggest opening a [discussion](https://github.com/beeware/toga/discussions), rather than an issue ticket. If you believe you've genuinely found a bug, we need a *full* reproduction case, along with the exception that you're seeing *that the code you've provided generates*.
