### ISSUE TITLE
Bypassing SSL/TLS Certification, Check Internet Connectivity and Manipulate html after page load

### ISSUE THREAD

**Issue by DDuttaGit** [beeware/toga#2120]
### What is the problem or limitation you are having?

The feature of Bypassing SSL TLS Certification error is, I guess, a necessity now. MWE is attached below which is returning an error like Unacceptable TLS Certification. The same url when opened (get) through `requests` it is showing ` '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)' `. But a fix over there is to set `verify` as False while making the `get` request.

Another thing is how to obtain what is returned by the WebView like on Internet turned off it is flashing some error message. How to get and store that message.

The next is on loading a page I want to modify the html content or change the layout. How to obtain such behaviour?

```import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW
class APPMAIL(toga.App):
    def startup(self):
        main_box = toga.Box(style=Pack(flex=1, direction="column"))
        webview = toga.WebView(user_agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36")
        webview.url = "https://url.com"
        main_box.add(webview)        
        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()
def main():
    return APPMAIL()```

### Describe the solution you'd like

A parameter within the `toga.WebView` like `verify=False` is of utmost need.

The tools to handle return messages might not be implemented. It is important to come in action.

### Describe alternatives you've considered

Android WebView also provide such tweaks as explained https://youtu.be/JNtFTwZyy-4 . 

### Additional context

_No response_

**Comment by freakboy3742** [comment]
An unconditional *NO*. Under no circumstances will we add this feature.

If you are having problems getting through your front door because the key gets stuck in the lock, you don't fix the problem by breaking a window and calling that the new door to your house. Similarly, if you are getting certificate errors with requests and WebView... then you have a problem with your certificates. That is what you should fix.

The remainder of your post appears to be 2 similar questions of usage. In both cases the content of the webpage isn't directly available as a Python attribute because it can be dynamic; however, you can use the `evaluate_javascript()` method to run a Javascript snippet on the webpage that manipulates the page and/or returns some detail about the page.

As an aside - it's generally a better idea to stick "one idea per ticket". This ticket has 3 ideas in it - a feature request, and 2 questions. If I close this ticket because the feature request has been denied, that means the 2 questions could be ignored. If there are answers to 2 questions, it can be difficult to track which response to the ticket is answering which questions. On top of that, an issue ticket isn't the best place to as questions - we have a discussion forum for open ended questions, as well as a Discord group.

I'm going to close ticket on the basis that the feature requested will not be implemented.

**Comment by mhsmith** [comment]
Related: [StackOverflow question](https://stackoverflow.com/questions/77103115)

**Comment by DDuttaGit** [comment]
As Malcolm Smith has correctly detected the issue and reported in
Comments <https://stackoverflow.com/a/77103308/22557870> Toga WebView has
most likely some bug. As I am testing the same code with Toga 0.3.1 in
Ubuntu 22.04 python 3.10, the response is still 'Unacceptable TLS Error'.

Point to note Browser is not flashing any such error message even if I
didn't tell it explicitly to trust the website or something like that. I
tested on freshly installed Brave and Chrome browser.

**Comment by mhsmith** [comment]
From StackOverflow:

> I am using named domain address while building the App. But didn't name it here. 

You'll need to tell us the address so we can verify whether it's a bug in Toga or an actual problem with the certificate. If you don't want to make it public, you can message one of us on [Discord](https://beeware.org/community/getting-help/).

**Comment by mhsmith** [comment]
Does it work with other HTTPS URLs, or do they all fail in the same way?

**Comment by mhsmith** [comment]
For example, try https://google.com/

**Comment by DDuttaGit** [comment]
Yes I have tried with https://google.com/ and many well known URLS . It is
working fine with them. But not with the particular URL that I want using
Ubuntu 22, Toga 0.3.1 python 3.10.
