### ISSUE TITLE
Complete implementation and testing of DocumentApp

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#2209]
### What is the problem or limitation you are having?

DocumentApp is currently implemented on Cocoa and GTK, but not covered by the testbed. On WinForms it's not really implemented at all.

### Describe the solution you'd like

All three platforms should implement the API, with as much automated testbed coverage as possible.

**Comment by freakboy3742** [comment]
In case anyone wants to look into this: testing will almost certainly require a second testbed app, or at least a significant workflow change in the existing testbed app that creates a second app after the first one has exited. If a second app is used, there needs to be a way to merge coverage between two apps - which isn't a problem on desktop platforms, but will be complicated on mobile.

In terms of functionality - this works well on Cocoa, but it's a little hazy on GTK because it's not clear whether a single app instance can/should be allowed to open multiple documents. It's currently documented as "one app, one doc"; but the implementation has some edge cases that allow for multiple documents to be opened (Start the document app without nominating a document - you get a file dialog. This lets you open a document... but also preserves the original window so you can open another one. Both windows honor CTRL-O, which opens a new window). Part of the work to be done here is to resolve what the correct native interpretation of a document-based app should be on GTK (and, for that matter, Windows).
