### ISSUE TITLE
Remove usage of setup.py in packaging configurations

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#2226]
### What is the problem or limitation you are having?

The various Toga subprojects all use `setup.py`; this configuration method has been deprecated, and is now causing [complications with other tooling](https://github.com/beeware/toga/issues/2224). We should complete the removal of `setup.py` from packaging configurations.

### Describe the solution you'd like

The use of `setup.py` should be replaced in favor of a "pure" `setup.cfg` configuration.

The complication is that the dependencies for platforms have a version requirement that is dynamic - toga-cocoa vX depends on toga-core vX - and I'm not aware of any way to define dynamic version dependencies.

We *could* drop this as a requirement, and just rely on the end-user pinning versions appropriately. This would have the benefit of:
1. Silencing the errors we see in Briefcase when the venv has one version of Toga installed, but the pyproject.toml specifies a different version. This is particularly common when the local version is a development version.
2. Deliberately allowing for toga-core to be updated when a toga-backend isn't. It's unclear if this would be a good idea, but it would at least be *possible*.

Alternatively, we could introduce a runtime check to validate that the toga-core version is equivalent to the toga-backend version at the time the factory is constructed.  

### Describe alternatives you've considered

We could move to a pure `pyproject.toml` configuration, removing the need for setup.cfg as well. This would be a bigger migration. The use of `pyproject.toml` for setuptools and setuptools_scm configuration has only recently moved out of `beta` status, so it's not clear if we'll hit problems in the migration; and some of our tools tools aren't compatible with `pyproject.toml` configuration (most notably, [flake8](https://github.com/PyCQA/flake8/issues/234)).

Alternatively, we could move to a completely different build tool (hatch would seem the most likely candidate).

**Comment by mhsmith** [comment]
For dependabot this only affects the `dev` requirements of toga-core. Since toga-core doesn't have the issue with matching versions, its setup.py could be removed right now, assuming setuptools-scm can be migrated.

> Silencing the errors we see in Briefcase when the venv has one version of Toga installed, but the pyproject.toml specifies a different version. 

Just linking to the relevant Briefcase issue: 
* https://github.com/beeware/briefcase/issues/768

**Comment by freakboy3742** [comment]
Via Mastodon: [this suggestion](https://chaos.social/@rami/111407725294047645) provides a fairly simple and elegant way to fix the dynamic dependency problem.

**Comment by ofek** [comment]
Maintainer of Hatch and Hatchling here! Let me know if I can be of assistance 🙂

**Comment by freakboy3742** [comment]
@ofek Thanks, as the closed ticket indicates, we've already been able to resolve this issue.

However, if Hatch has a built-in solution for the dynamic dependency problem, it might be worth exploring porting from setuptools.

**Comment by ofek** [comment]
> I'll point out that you came to us, commenting on a ticket that was closed over a week ago, fixed to the satisfaction of the project with no hacky workarounds or off-label usage

I did come here but as a result of your comment in the OP: "we could move to a completely different build tool (hatch would seem the most likely candidate)"

I try to search for keywords on issues every few weeks to see if I can help folks.

> In your response, you also reference an upcoming document detailing why I have no idea if that document ever emerged, but if it did, didn't hit my personal radar. If it does exist, I'd suggest it should be prominently linked from the Hatch homepage, because for me, "why hatch and not setuptools" is a big missing piece of the puzzle.

Thank you for your feedback! I de-prioritized that page due to time constraints (I was focusing on features) but I will do that tonight before I cut the next release.

> "Reproducible builds" and "environment management". These are both features of `build` AFAICT.

This is very far off actually. The tool you mention is for executing builds which then triggers the logic of a build backend which is the thing that actually produces the archive(s). Hatchling produces reproducible builds for wheels and source distributions whereas setuptools just does the former (although I don't know that it guarantees reproducibility for wheels for sure).

By your environment management comment, I think I understand the ultimate confusion here and that is the fact that Hatch is a CLI similar to Cargo or NPM while Hatchling is the sister project only in charge of builds and is comparable to setuptools and flit.

You can mix and match features because the defaults are all based on standards e.g. using just the build backend.

Environment management refers to tox-like functionality that is built-in to Hatch.

The main benefit is that, if a user wishes, they can get rid of the majority of their tooling (tox/nox, twine, bumpversion/versioneer, pyenv, etc.) by switching to Hatch.

**Comment by freakboy3742** [comment]
> > I'll point out that you came to us, commenting on a ticket that was closed over a week ago, fixed to the satisfaction of the project with no hacky workarounds or off-label usage
> 
> I did come here but as a result of your comment in the OP: "we could move to a completely different build tool (hatch would seem the most likely candidate)"
> 
> I try to search for keywords on issues every few weeks to see if I can help folks.

Ah - that at least explains why you've joined us :-)

FWIW: The "maybe Hatch?" comment was presented for completeness as one possible option, if we couldn't do what we needed with setuptools. As it turns out, we *could* do what we needed to do, so the move to Hatch wasn't required.

> > "Reproducible builds" and "environment management". These are both features of `build` AFAICT.
> 
> This is very far off actually. The tool you mention is for executing builds which then triggers the logic of a build backend which is the thing that actually produces the archive(s). Hatchling produces reproducible builds for wheels and source distributions whereas setuptools just does the former (although I don't know that it guarantees reproducibility for wheels for sure).

I'm not sure I understand how a source distribution *can't* be reproducible... it's a tarball of files. What *can't* be reliably reproduced?

> By your environment management comment, I think I understand the ultimate confusion here and that is the fact that Hatch is a CLI similar to Cargo or NPM while Hatchling is the sister project only in charge of builds and is comparable to setuptools and flit.

That is firmly in the category of "things that aren't even remotely explained on the homepage". :-) The PyPI page for hatchling points at the same landing page as hatch, and the only mention of hatchling I can find is the "history" mention, which gives the release history of 2 independent tools, but doesn't explain how they relate. My read of the information available was that hatchling was the the tool used to package hatch, because of some bootstrapping limitation.
 
> Environment management refers to tox-like functionality that is built-in to Hatch.
> 
> The main benefit is that, if a user wishes, they can get rid of the majority of their tooling (tox/nox, twine, bumpversion/versioneer, pyenv, etc.) by switching to Hatch.

Hrm. I'll have to take a closer look then. The "replace all your tooling" aspect definitely missed my radar.

**Comment by ofek** [comment]
> I'm not sure I understand how a source distribution can't be reproducible... it's a tarball of files. What can't be reliably reproduced?

Bits that represent file permissions and timestamps, normalization of new line characters for metadata, etc. there is a lot that goes into it tbh

**Comment by ofek** [comment]
The first part of the value proposition page is complete https://hatch.pypa.io/dev/why/

I'm going to add other sections to that page tonight.
