### ISSUE TITLE
Leitura de arquivo com pandas no Beeware

### ISSUE THREAD

**Issue by Mayck20** [beeware/toga#2561]
### Describe the bug

Estou com problema para utilizar o pandas no meu projeto. O Projeto roda normalmente no modo desenvolvedor com maquina virtual, porem quando eu faço a instalação do aplicativo apresenta erro de importação do pandas. falta só resolver esse problema para finalizar meu aplicativo.

### Expected behavior

Preciso que ele faça a leitura de um arquivo excel que será usado com um banco de dados. o pandas vai fazer a leitura e ajudará na escrita e atualização do arquivo.

### Screenshots

![erro](https://github.com/beeware/toga/assets/154385206/53e35f08-4a63-4c88-b69c-2d8cdf941f1a)

### Environment

- Operating System:
- Python version:
- Software versions:
  - Briefcase:
  - Toga:
  - ...

### Logs

```

```

**Comment by freakboy3742** [comment]
You are seeing this error because you have not added `pandas` as a dependency in the `requires` definition of your `pyproject.toml`. 

This is covered in step 7 of the the BeeWare tutorial: https://docs.beeware.org/en/latest/tutorial/tutorial-7.html
---
Google Translate:

Você está vendo este erro porque não adicionou `pandas` como uma dependência na definição `requires` do seu `pyproject.toml`.

Isto é abordado no passo 7 do tutorial BeeWare: https://docs.beeware.org/pt/latest/tutorial/tutorial-7.html
