### ISSUE TITLE
On Windows, the creation of `MainWindow` renders it in the display without calling `show()`

### ISSUE THREAD

**Issue by rmartin16** [beeware/toga#2653]
### Describe the bug

On Windows, the `MainWindow` for an app is shown when it is instantiated instead of when `show()` is called.

### Steps to reproduce

MRE:
```python
import toga


class MyApp(toga.App):
    def startup(self):
        self.main_window = toga.MainWindow(title=self.formal_name)


MyApp("MyApp", "www.example.org").main_loop()
```

### Expected behavior

The window should be shown only after `show()` is called; at least, this is the behavior on Linux, so everything should at least be consistent.

### Environment

- Operating System: Windows 11
- Python version: 3.10.14
- Software versions:
  - Briefcase: 0.3.19
  - Toga: `0.4.5.dev159+g0d736a41c`

**Comment by freakboy3742** [comment]
It looks like displaying the form is a side effect of setting the MainForm of the ApplicationContext (see `App.set_main_window()`). 

This was historically required because the Winforms async proactor was bound to the main form; however, this hasn't been true since we merged #2112. I'm in the process of reworking main window handling as allowing background and session-based apps (#2651); I'll fix it there.
