### ISSUE TITLE
gtk.Label not placeced correctly until window resize

### ISSUE THREAD

**Issue by Ocupe** [beeware/toga#270]
Labels on the gtk backend stay on the top left corner only after resizing the window the label jump at the correct position. I think some update method is not called.

**Comment by freakboy3742** [comment]
This bug is vaguely familiar, and I think it's the opposite to @Ocupe's intuition - IIRC, the update method *is* being called, but because of *when* it's being called, the layout geometry is being evaluated to a position of (0, 0), and then that position "sticks" for some reason. 

That said, I could be completely wrong. I'm just recording this in case it helps the debugging process.

**Comment by DariusMontez** [comment]
This issue has been resolved (I think in #317) and can be closed. I verified that the labels behave correctly in the Table and Tree example apps.
