### ISSUE TITLE
On GTK, OptionContainer current_tab returns wrong index

### ISSUE THREAD

**Issue by steve725** [beeware/toga#2703]
### Describe the bug

The property "current_tab" of an OptionContainer-Object returns the wrong index of the current tab.
This happens because the first click on a tab is obviously not registered.
As a consequence the previous index is returned.

### Steps to reproduce

1. Go to 'examples/optioncontainer/optioncontainer'
2. Run 'python app.py' or 'python -m app'
3. Click on one of the three tabs ('Option 0, Option 1, Option 2) of the OptionContainer
4. See output above the tabs

### Expected behavior

OptionContainer.current_tab.index should return the current index of the clicked tab not the previous index

### Environment

- Operating System: OpenSuse Tumbleweed 20240704; KDE Plasma 6.1.2
- Python version: 3.12.4 (miniforge; conda version : 23.11.0)
- Software versions:
  - Briefcase:
  - Toga: 0.4.5

### Logs

```

```

**Comment by mhsmith** [comment]
I can't reproduce this with the Toga main branch on Cocoa, so I assume it's specific to GTK. But I can't currently run Toga on GTK because my Linux distribution is too old. @freakboy3742: Can you reproduce it on GTK?

**Comment by steve725** [comment]
Yes, it seems to be a GTK specific issue, on Windows the OptionContainer works correct.
Maybe it's due to that I didn't create a MainWindow in my app and therefore Gtk.Notebook() [toga-main/gtk/src/toga_gtk/widgets/optioncontainer.py] does not show at startup?
I don't use a MainWindow because I want to avoid the native menu on Linux and Windows.

**Comment by mhsmith** [comment]
> Maybe it's due to that I didn't create a MainWindow in my app

You said it happens with examples/optioncontainer, which does create a MainWindow.

**Comment by steve725** [comment]
I'm using toga 0.4.5 so I adapted the example using only the Window-class instead of MainWindow.
Trying to install the main-branch always gives me an error:

`pip install https://github.com/beeware/toga/archive/refs/heads/main.zip ->
error: Multiple top-level packages discovered in a flat-layout: ['gtk', 'iOS', 'web', 'core', 'demo', 'toga', 'cocoa', 'dummy', 'android', 'changes', 'testbed', 'textual', 'winforms']`

Maybe I need to change pyproject.toml.

**Comment by mhsmith** [comment]
Toga 0.4.5 is the current stable version, which requires every app to have a MainWindow. We've removed this restriction on the main branch. To use it, edit your pyproject.toml file to replace  the`toga-gtk` line with the following:
```
"git+https://github.com/beeware/toga#subdirectory=core",
"git+https://github.com/beeware/toga#subdirectory=gtk",
```

And similarly for the other `toga` packages if you want to run your app on other platforms.

I think it's unlikely that the window type will make any difference to the OptionContainer behavior, but it would be easy enough for you to check.

**Comment by steve725** [comment]
I checked the example with the code of the main branch and the problem still remains. So you are right: the OptionContainer behavior does not depend on the window type.
Maybe someone else can reproduce the wrong behavior on a Linux system.

**Comment by freakboy3742** [comment]
I can confirm I'm seeing this on GTK with main - the callback appears to be invoked with the "old" index, not the newly selected index.

The issue is event timing. When the GTK `switch-page` event is fired, it provided the index of the newly selected page; but whatever is returned by `current_page()` hasn't been updated yet. As a result, the `on_select` handler of the example program is returning the "old" tab index.

Unfortunately, there doesn't appear to be a "switch has completed" event - the only event that seems to do anything in response to a tab change is "switch-page".

One workaround is to defer the firing of the on_select event; if that event is put onto the event loop, rather than firing immediately, the "switch-page" event completes, and `current_page()` returns the updated index. 

Another workaround would be to avoid `current_page()` entirely, and internally reproduce that functionality.
