### ISSUE TITLE
Hide non-default readthedocs versions from search engines

### ISSUE THREAD

**Issue by mhsmith** [beeware/toga#2708]
#2706 was apparently caused by a user trying to follow the "latest" documentation while using the stable version. This has happened a few times. 

Even though the "stable" version is set as the default on readthedocs, I've noticed that the "latest" version still often appears in Google search results. Older versions sometimes show up as well.

It looks like we could avoid this by adding [robots.txt rules](https://docs.readthedocs.io/en/stable/reference/robots.html) for `latest` and `v*`.

**Comment by freakboy3742** [comment]
RTD's own docs [have section on SEO](https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html), which directly suggests [adding a `robots.txt` file](https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html#use-a-robots-txt-file), as well as a sitemap and meta tags, so that definitely seems like the way forward.
