### ISSUE TITLE
Window does not maintain size after being minimized on Windows

### ISSUE THREAD

**Issue by ProgrammingGoat** [beeware/toga#2729]
### Describe the bug

Platform tested: Windows
When a window gets minimized and restored, it will be restored to the smallest possible size given its contents, rather than the size it was when minimized.

### Steps to reproduce

1. Create a new briefcase project
2. Insert a label into the main box
```
main_box = toga.Box()
label = toga.Label("Hello World")
main_box.add(label)
```
3. Run `briefcase dev` (or `briefcase run`)
4. Minimize the window
5. Restore the window
6. The window has now been resized to the smallest possible size.

### Expected behavior

Window gets restored to the original size before minimizing.

### Screenshots

Before:
![Default sized window](https://github.com/user-attachments/assets/8eada3f3-16a9-4c16-8d24-b868235c448f)

After:
![Tiny window](https://github.com/user-attachments/assets/15252ae3-4e1b-432a-8177-bfafe3884ec8)

### Environment

- Operating System: Windows 10
- Python version: 3.12
- Software versions:
  - Briefcase: 0.3.19
  - Toga: 0.4.5

**Comment by freakboy3742** [comment]
Thanks for the report.

Some further clarifications:
* This only affects Windows; GTK and macOS don't have the same behavior.
* It doesn't affect *maximizing* - only minimising.

Based on some preliminary analysis, I think I've worked out what is happening. The Winforms toga.Window class has a listener on window resizes. When you resize the window, this causes a re-evaluation of the layout; the maximum of the current layout size and the minimum possible layout size is applied as the actual size (effectively imposing a minimum size on the window that matches the minimum possible layout size).

However, on Winforms, minimizing triggers a resize event, with a window size of 0,0. This causes the window size to be set to the minimum possible size of the window content, resulting in the behavior seen here. 

From a quick inspection, I think the fix is to check the current window state when the resize event occurs. We don't need to process resize events when the window is minimized; so a `if self.native.WindowState != Winforms.FormWindowState.Minimized` check in the `toga_winforms.Window.winforms_Resize` handler should be all that is needed.

By way of testing, there is an existing testbed test that validates window minimisation (`tests/window/test_window.py::test_visibility`); this check validates the *initial* size of the window being minimized as part of a check of window resizing, but doesn't validate the size of the window after minimization. An assertion for post-unminimise window size should be sufficient validation.

**Comment by yashathwani** [comment]
@freakboy3742  would like to work on this issue could you please assign me this issue to me!!

**Comment by freakboy3742** [comment]
@yashathwani We don't formally "assign" issues; dropping a comment that you're working on the topic (as you have already done) is more than enough. I look forward to seeing a PR!

**Comment by yashathwani** [comment]
I have made some changes in windows.py . Could you please guide me on how to test these changes to ensure they are working correctly with the Toga framework? Like how to run the application what requirements are required
Thankyou

**Comment by freakboy3742** [comment]
@yashathwani The Toga docs have a [contribution guide](https://toga.readthedocs.io/en/stable/how-to/contribute/code.html) that details how to set up a development environment, and how Toga is tested.

My [original reply](https://github.com/beeware/toga/issues/2729#issuecomment-2246527245) to this ticket details the extra assertion in the testbed that is required to validate this change. 

If you need any additional pointers, let us know!
