### ISSUE TITLE
Button example not running

### ISSUE THREAD

**Issue by samredway** [beeware/toga#277]
The button example is broken - it has these lines:
```
       # Button with label and RGB color
       button6 = toga.Button('RGB : Fashion', background_color=(50,200,200))

        # Button with label and string color
        button7 = toga.Button('String : Fashion', background_color='yellow')
```
This stuff breaks as background_color is not a legal parameter. This was taken out some months ago (I believe switching to the newer core interface approach). 

It is trivial of course to remove the illegal param, but what do we want to do re background color? Was it deliberately removed functionality (perhaps being able to set background colour is not a universal property of buttons, or maybe it was decided this should be a CSS property) or should this be re-implemented as was?

**Comment by Ocupe** [comment]
@samredway thank you for the report. This could be my fault I possibly mist to move it into the restructured version of Toga. But there could be also other reasons/decisions that I don't know about.

I think we should make background_colour a CSS property and remove it from the example for now. If I remember right background colour was never fully integrated on all backends. This could lead to a lot of frustration for people on different platforms. And a simple button example should work always! This being said. 
There more issues with the example app. A lot of the advertised functionality is not working. If you would like to invest some minutes into creating a little (working) example app I would like to merge it ;)

**Comment by samredway** [comment]
Have been thinking about this somewhat and it seems to me that being able to colour widgets is fairly important functionality. It would be nice to pass that information in with the CSS() object - but at the moment there doesn't seem to be any plan to implement this so maybe we should just put back the functionality as was?

I imagine that most of the platforms will support button colour, and for those that don't we can always raise a NotImplementedError and then wrap the call to toga.Button in a try .. except ... in the example. ie:
    
    try:
        # Button with label and RGB color
        button6 = toga.Button('RGB : Fashion', background_color=(50,200,200))
    
        # Button with label and string color
        button7 = toga.Button('String : Fashion', background_color='yellow')
    except NotImplementedError:
        print('This platform does not support coloured buttons or the functionality has not yet been implemented')

If we plan to implement colouring in some other way perhaps this should be raised as an issue?

**Comment by freakboy3742** [comment]
@samredway I agree that colouring widgets is important significant functionality (possibly not as important has *having* widgets to color, though - which is why it hasn't been addressed yet 😄). 

The problem we've got at the moment is that we're in a cleaning phase. I wrote a bunch of APIs in a hurry as a proof of concept; we're now going back and revisiting things. So, on the one hand, the widget interfaces have been modified to remove styling-related methods (like setting colours); but on the other hand, Colosseum doesn't have full support for colours (yet - initial color support *has* been added to the development branch, but the development branch also regresses some other behaviours).

As for whether this should be opened as an issue - we're still at the point in the process where I'm not entirely convinced issues will help do anything other than create paperwork. "Toga is missing most of it's functionality" isn't an issue - it's what we're trying to do 😄 

But what is the path forward? There are several possibilities that I can see:

1. Introduce set_color et al to any widget that might make use of it, but be clear (through docs, etc) that it's a temporary measure that will be replaced with CSS styling.

2. Introduce set_color et al as a *permanent* measure, designed to live in parallel to the styling API.

3. Don't introduce set_color, and just wait until we can introduce full CSS styling.

I'm not wild about 1; it feels like a bad stop-gap measure.

I'm not *fundamentally* opposed to Option 2 - however, if we go down that path, it opens up all sorts of questions. If you specify both a CSS color and a "direct on the widget" color, which takes precedence? And if you can set the color directly on the widget, why not the font face or size for a label? Or text alignment? Or margins and borders? Once you open this floodgate, it's easy to end up with a widget API that doesn't retain *any* CSS characteristics.

Option 3 seems "purest" - and it also allows for a future where someone wants to define a styling mechanism that *isn't* CSS (say - an implementation of constraint-based layout, with some custom language for describing colors etc). My only concern with this is whether this purity gets in the way of practicality.

Regardless of which of these approaches is taken, there *will* be a need for set_color et al at the *interface* level, because we'll need a mechanism on the underlying platform for setting a button a particular color. *This* is a task that can be tackled right now; and, if an end user *really* needs to set a color before the CSS components are fully ready, they can always call `button._impl.set_color()` to set the color directly. And, on platforms that don't allow for buttons to change color, we can make the implementation a no-op.

**Comment by samredway** [comment]
Thanks for the detailed explanation - that makes a lot of sense and yes unless practicality gets in the way option 3 definitely sounds like the best choice from the end users perspective. I will take a look at implementing button color at the interface level for now - if nothing else it gives me a chance to better understand how the widgets are being rendered.

**Comment by freakboy3742** [comment]
The button example now works, and supports colors in most cases; we can open new tickets for cases where color isn't working.
