### ISSUE TITLE
Callbacks into Toga invoked from .NET do not respect failure modes

### ISSUE THREAD

**Issue by rmartin16** [beeware/toga#2779]
### Describe the bug

While investigating https://github.com/beeware/toga/issues/2752, I discovered that the `RuntimeError` being raised because the WebView failed to initialize was swallowed and suppressed. Even running `sys.exit(1)` did not cause a visible error to be raised.

As such, developers and end-users are not informed of critical runtime errors.

### Steps to reproduce

It's probably easiest to just force it; that is, just update `winforms_initialization_completed` to always raise an Exception and run an app using the WebView.

### Expected behavior

Errors detected in such callbacks are reported to users.

### Environment

- Operating System: Windows 11
- Python version: 3.12
- Software versions:
  - Briefcase: `0.3.20.dev96+g23d1ed34`
  - Toga: ` 0.4.6.dev321+g79719fce4`

### Logs

[briefcase.2024_08_19-16_36_06.dev.log](https://github.com/user-attachments/files/16665285/briefcase.2024_08_19-16_36_06.dev.log)

**Comment by freakboy3742** [comment]
As a workaround, would it make sense to actually *write* the error message to the console, in addition to raising the `RuntimeError` and assuming it will be seen/surfaced? I agree this would be less than ideal, but it would be better to output *something* that indicates there's a problem rather than fail silently when we know there's been a problem.
