### ISSUE TITLE
Restructure widget initialization

### ISSUE THREAD

**Issue by HalfWhitt** [beeware/toga#2937]
### What is the problem or limitation you are having?

The order in which widgets currently initialize means they try (and fail) to apply their styles before their implementations are available. The style isn't actually applied until the end of the constructor for the *implementation*, meaning it's repeated in every single implementation class. The creation and assignment of the implementation also has common logic that can be pushed from the individual widget subclasses into the base.

### Describe the solution you'd like

Rearranging things as described in https://github.com/beeware/travertino/pull/224#issuecomment-2428140351

### Describe alternatives you've considered

Do nothing. Everything currently works as-is, it's just not as sensible and efficient as it could be.

### Additional context

Originally stemming from the mysterious errors I saw in #2916 (which had previously been there, but were always suppressed until I made a change in Travertino), I went down the rabbit hole. The Travertino half of the restructuring is in https://github.com/beeware/travertino/pull/224, which is backwards compatible with the current development and stable versions of Toga.

I plan to tackle this, but I think I'd like to finish Travertino's composite property first, so I thought it'd be a good idea to post this as an issue for now.

**Comment by mhsmith** [comment]
I haven't been following this discussion too closely, but is it possiible this could be fixed in a way that also fixes the "redundant rendering pass" issue mentioned https://github.com/beeware/toga/pull/1794#issuecomment-1453096289? Except for Winforms, none of the native platforms make any changes visible until the next main loop iteration. So if we delay actually applying the styles until the end of the current iteration:

* Multiple assignments to the same style within a single main loop iteration would only have the final value passed to the native widget.
* More importantly, multiple changes to style or content which would only require a single layout pass. Right now, if you have N labels and you change the font on all of them, we'll perform N layout passes, which will cost O(N ** 2) time.

**Comment by HalfWhitt** [comment]
Hm. My off-the-cuff guess is that fixing that would better be done within the apply and/or refresh methods. Perhaps instead of performing their work immediately, calls could place themselves as a task in a one-slot queue of sorts, or staging area, and at a defined point the end of the event loop, only the most recent request is submitted to the interface.

However, I haven't even read those methods yet and I'm currently on my phone, so who knows!

**Comment by mhsmith** [comment]
OK, then I'll create a separate issue for that – #2938.
