### ISSUE TITLE
missing info in tutorial

### ISSUE THREAD

**Issue by DigitalK** [beeware/toga#335]
## issues
1. In  http://toga.readthedocs.io/en/latest/tutorial/tutorial-0.html
It shoes you the code and says 'Save the script and that's it' but it isn't!

You actually need to first set up a virtual environment.
So, it needs to explain how to do this.

2. You need to make sure you have the correct version of Python 3 as your default for it to work. (I tried to install toga but I had Python 2 as my default for some reason). So make this clear.

3.  In the Minimum requirements, it is confusing as the first dot point is for Mac OS, the second one is for Linux but the third one is also only for Linux and this is not clear.

**Comment by danyeaw** [comment]
@DigitalK Thanks for reporting the issue. Some of the information is in the (Setting up your environment)[https://pybee.org/contributing/how/first-time/setup/] section, but it is more aimed at developers.

Could you submit a pull request with your suggested updates?

**Comment by freakboy3742** [comment]
@danyeaw Some context here - I was working with @DigitalK in an informal linux.conf.au sprint. I encouraged her to open a report because she hit a bunch of problems coming into the tutorial. 

I was fairly sure that this information was already there - but it definitely wasn't in the workflow for someone coming to the tutorial for the first time.

**Comment by danyeaw** [comment]
@freakboy3742 Got it! I think adding better step by step instructions for first time users is a great idea.

**Comment by ArchKudo** [comment]
Would it make sense for toga's documentation to have a Getting Started page, which mentions all the prerequisites for running a toga app? Or should this be added to tutorial-0 itself?

**Comment by freakboy3742** [comment]
Based on the feedback we've been getting by way of bug reports, I've been contemplating a wholesale rework of our tutorials. 

Having separate tutorials for each individual component of BeeWare (Briefcase, Toga, etc) means there are lots of places we need to keep in sync. What we really need is a single point of entry that shows how all the pieces fit together. The individual projects will still need their docs; but we don't need a "getting started with Toga" tutorial, because you will usually need briefcase, and vice versa. 

This would also provide a better entry point for funnelling people based on platform - so, if they're on windows, we can warn them that there will be problems etc.

**Comment by Munnu** [comment]
This is officially done and should be closed.
