### ISSUE TITLE
Webview doesn't handle urls with scheme absent

### ISSUE THREAD

**Issue by ArchKudo** [beeware/toga#387]
## Steps to reproduce

1. Run examples/example4
2. Type the url 'google.com' and click 'Go'
3. No change
4. Type 'https://google.com' and click 'Go'
5. Takes me to Google's homepage

## Expected Behavior

Typing in 'google.com' and hitting 'Go' should change the url to 'https://google.com' and take me to the Google homepage

## Cause

Currently the `WebView.set_url` function only checks whether value is `None` and loads the url

## Proposed Change
1. Either we could change `set_url` signature to include scheme with default as `http` or,
2. We could make `set_url` check whether passed value is valid url
3. Or add elementary substitution logic inside `set_url` method  

Thoughts?

## Your Environment

* Python Version (list the specific version number)
```bash
$ python --version
Python 3.6.4
```
* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

 - [x] Linux
```bash
$ uname -a
Linux hbar 4.15.4-1-ARCH #1 SMP PREEMPT Sat Feb 17 16:01:38 UTC 2018 x86_64 GNU/Linux
```

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [x] gtk (gtk3 3.22.28-1)
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Agreed - there's no validation of the content passed to the `url` property of WebView. If what is passed in isn't a URL, then that's an error.

"google.com" isn't a URL. It's generally fairly easy to work out what URL the user intended - and many browsers will make that jump - but that's an application level distinction. For example, should "google.com" be interpreted as `http://` or `https://`? Rather than enforce that decision for the user at a the widget level, I'd rather raise an error if the url provided isn't actually a full URL.

And - to be clear, the fix is in `toga/core`, on the `url` property; not in `set_url()` on an implementation backend. set_url() should be able to assume that it's getting a valid, fully qualified URL appropriate for loading as a web page.

**Comment by ArchKudo** [comment]
Thanks for replying! We could have default as `https://` but can fallback to `http://` but then the scheme could be completely different like `file://`, so I think it is is more of a design decision, but until then as you said we could just raise an error, something along these lines?:
```python
from urllib.parse import urlparse

if urlparse(url).scheme is '':
    raise ValueError('Incorrect URL')
```

**Comment by freakboy3742** [comment]
Yes - something like that would seem appropriate (although the error message should be a little more verbose - it's not "incorrect", it's not a URL *at all*. Something like "Must provide a fully qualified URL" would be a better error message).

**Comment by ArchKudo** [comment]
I think I might have been a little naive, because just checking for scheme leads to false negatives, like what if url entered was an IP address, or `localhost`, and also false positives like what if url is `https://www.google`?
 What should we do then? Should implementation handle such cases?

**Comment by freakboy3742** [comment]
Closing on the basis that the original bug report wasn't valid, and the proposed fixes are either incomplete or invalid.
