### ISSUE TITLE
Add support for interactive graphs

### ISSUE THREAD

**Issue by gappleto97** [beeware/toga#545]
This would be particularly nice if it could be used with matplotlib, or a similar API.

Plenty of apps use such a graph, but as near as I can tell there is no support for this in toga.

Also, I apologize if there is a template. For some reason they do not show up in this app (even though they used to)

**Comment by freakboy3742** [comment]
Sure - a graphing/charting API would be great; integration with matplotlib would be one option, but I'm sure there are others.

We're still building up the basic set of widgets - buttons, comboboxes and so on - a charting library is certainly *on* the list, but it's a bit further down the priority list. However, we've got a drawing canvas library almost ready for GTK (see #383); once that lands, a charting library shouldn't be *too* hard to put together.

If you're motivated to work on a charting library, we'd certainly welcome any contributions!

**Comment by gappleto97** [comment]
Im not entirely sure what would be involved with that, but at the very least I would be happy to help test on Android and Linux.

Are there any resources that you could point me to, as far as what things I would need to know to make such a thing?

**Comment by freakboy3742** [comment]
I don't know enough about the internals of matplotlib to comment; I suppose finding out how matplotlib backends work would be the first thing to dig into.

**Comment by bryall** [comment]
I also have a interest in this feature and have begun to implement it using the matplotlib library.

right now, I have plot text displaying on a toga Canvas. I noticed there is no support for angle text writing, which we will need. Have a feeling there will be more of these that pop up later.

I am new to community projects, do I set up a pull request to get feedback and discussion going while developing or when I feel I have the feature completed?

**Comment by freakboy3742** [comment]
@bryall Thanks for taking a look at this! 

Regarding the process - it depends how "big" or "controversial" you feel your changes will be. Small changes won't have much to discuss, so working code will explain your ideas better than a long explanation. A larger change, however, might involve some design tradeoffs, limitations and so on, and some discussion may be required first. In that case, submitting a ticket (or PR with some initial code) as a place to stimulate discussion would be the right way to go.

So, if adding angled text turns out to just be a matter of adding an "angle=123" argument to the text writing API, then just submit a PR. However, if you need to make more substantial changes to the Canvas API, then a discussion will be required.

Regarding the API itself; we're trying to use the HTML5 Canvas API as a model, so if that API has allowances for text angle, that would be the direction we'd prefer to take things.

**Comment by freakboy3742** [comment]
I'm going to close this as a feature request; we now have an [external implementation of a matplot rendering widget](https://github.com/beeware/toga_chart).
