### ISSUE TITLE
AttributeError: module 'toga' has no attribute 'OptionContainer'

### ISSUE THREAD

**Issue by jjisnow** [beeware/toga#565]
## Expected Behavior
I'm expecting to see a toga_demo window pop up

## Current Behavior
  File "C:\Users\JJ\Miniconda3\lib\site-packages\toga_winforms\app.py", line 41, in _st
artup
    self.startup()
  File "C:\Users\JJ\Miniconda3\lib\site-packages\toga_demo\app.py", line 15, in startup

    left_container = toga.OptionContainer()
AttributeError: module 'toga' has no attribute 'OptionContainer'

## Steps to reproduce
1. pip install toga-demo

2. toga-demo

3. view error

## Your Environment
* Python Version (list the specific version number)
3.6

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [x ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ x] win32
  - [ ] Other (please specify)

**Comment by russ-hensel** [comment]
I see the same thing, Running win10 py 3.6, anaconda setup, and a virtual environment.  This is my introduction to toga, so not the ideal first impression.  Since I believe I am running a script *.exe I do not see any simple way to look into it. 
Running 
pip install toga-win32 toga-cassowary cassowary
did not help.
Some web page I found mentioned a dependency on some microsoft net component, but I cannot find the page.
Will try to go into spyder and get something else to run.

**Comment by jjisnow** [comment]
sure!

**Comment by starlord1311** [comment]
@jjisnow can you tell me what i am supposed to do?

**Comment by starlord1311** [comment]
@jjisnow ?

**Comment by starlord1311** [comment]
@jjisnow how to proceed with this issue?

**Comment by jjisnow** [comment]
Maybe you could look at the source code and fix it?

**Comment by freakboy3742** [comment]
@jjisnow I can appreciate that you're frustrated, but please keep an eye on your tone. The BeeWare project aims to foster an inclusive and friendly community. Sarcastic and dismissive comments don't reflect that. 

@starlord1311 Tone notwithstanding, @jjisnow has a point. Saying "how to proceed" isn't especially helpful to everyone else, because it isn't clear what help you need. Are you looking for debugging help? Clarification around our engineering procedures? Design advice? Or something else? 

We're happy to provide *some* assistance, but you need to help us to help you. We also need you to do some exploration of the problem, rather than just asking to be told what to do. 

If you don't feel confident doing that on your own, we've laid out [some specific tasks for first-timers](https://pybee.org/contributing/how/first-time/), which might be a better place for you to start contributing.

**Comment by jjisnow** [comment]
Thanks Russell,
      I was a little confused about being asked how to proceed when I was
the one who submitted the issue. Although I could look into the fix for it,
I don't as of this moment have expertise in doing so and would need to
learn a lot for the project. Thanks for the response, and if I have the
energy and time to do so , I'll look into helping out with the project!

J

**Comment by zodman** [comment]
same here

```
C:\Users\zodma>toga-demo
Traceback (most recent call last):
  File "c:\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python3\Scripts\toga-demo.exe\__main__.py", line 9, in <module>
  File "c:\python3\lib\site-packages\toga_demo\__main__.py", line 5, in run
    main().main_loop()
  File "c:\python3\lib\site-packages\toga_winforms\app.py", line 49, in main_loop
    self._startup()
  File "c:\python3\lib\site-packages\toga_winforms\app.py", line 41, in _startup
    self.startup()
  File "c:\python3\lib\site-packages\toga_demo\app.py", line 15, in startup
    left_container = toga.OptionContainer()
AttributeError: module 'toga' has no attribute 'OptionContainer'
```

**Comment by freakboy3742** [comment]
@moltob Broadly speaking there *aren't* any instructions necessary; one of the key design decisions behind Toga is that you should be able to `pip install toga`, and it should run. 

However, there's a very big caveat on that: The windows backend isn't especially complete. I know for certain the current stable version of toga (0.2.15) can't run toga-demo; Off the top of my head, I can't remember whether the current state of development (0.3.0.dev9) can run the demo - I thought it could, but it possibly can't. If it *does* work, you'll need to use `pip install --pre toga-demo` to force the installation of the pre-release version.

There's no real secret to the error message: when it says "toga has no attribute OptionContainer", it means the OptionContainer widget hasn't been implemented yet. There's lots of work still to be done, and unfortunately, Windows and Android are the platforms lagging behind - while they may have the largest market share, they're not the platforms I personally use on a daily basis, and they're the platforms we've had the least help implementing. They're also the hardest platforms to integrate with, because they don't provide a well integrated Python API for access, and a bridge isn't easy to create.

If you're motivated to see Toga working on Windows, we'd appreciate any help you can provide; however, in the meantime, you'll need to wait until we can flesh out the remaining widgets and provide full Windows support.

**Comment by nagexiucai** [comment]
`0.3.0.dev11` is ok, but on windows 10, when click any "hello world" button, it comes:

```
Python.Runtime.PythonException: RuntimeError : There is no current event loop in thread 'Dummy-1'.
   在 Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by obulat** [comment]
The OptionContainer on Windows has been implemented for quite some time, and the event loop problems have been solved, so I'm closing this issue.
