### ISSUE TITLE
Can't install toga-demo 

### ISSUE THREAD

**Issue by Sajo8** [beeware/toga#665]
## Expected Behavior

I run the install command, and it should install correctly.

(Doesn't seem to be a duplicate of #328)

## Current Behavior

The installation fails:

https://pastebin.com/ikJeRZE6

(This is my 2nd/3rd time attempting to install it. This time I used `pipenv run pip install toga-demo`, the other times i ran `pipenv install toga-demo`.)

## Steps to reproduce

Run the command `pipenv install toga-demo` (`pip install toga-demo` might also fail)

## Your Environment

Newly made virtualenv with pipenv.

* Python Version (list the specific version number)

Python 3.7.2

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [x] Windows 10 Pro Version 1809
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms 
  - [ ] win32
  - [x] Other: Just running the demo

**Comment by freakboy3742** [comment]
This is a known problem that has been fixed.

The current "stable" version of Toga (0.2.15) is missing some key features, so toga-demo doesn't run. 

The development version (currently 0.3.0.dev11) addresses these problems; but isn't installed by default.

If you run `pip install --pre toga-demo` that will allow pip to install the development version.

However, I have no idea how that will interact with pipenv. I'm guessing you won't be able to just run toga-demo; you'll need to use a `run` command of some kind.

Closing on the basis that the problem has been fixed in master.
