### ISSUE TITLE
when there are two boxes contained in another box that has its direction set as row, and the first box has a direction column and contains both a textinput and a MultilineTextInput widgets the second box does not show

### ISSUE THREAD

**Issue by Joetib** [beeware/toga#666]
## Steps to reproduce

1.

2.

3.

## Your Environment

* Python Version (list the specific version number)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version: 
  - [ ] Linux - distro:   - version:
  - [x] Windows - version:
  - [ ] Other - name:  - version:

* Toga Target (the type of app you are trying to generate)
 
  - [ ] android
  - [ ] cocoa
  - [ ] django 
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] winforms 
  - [ ] win32
  - [ ] Other (please specify)

**Comment by Joetib** [comment]
this is an example

box = toga.Box()

first_box = toga.Box()
first_box.style.update(direction=COLUMN)

text_input = toga.TextInput()
multilineTextInput = toga.MultilineTextInput()

first_box.add(text_input)
first_box.add(multilineTextInput)

button = toga.Button("Click Me")

second_box = toga.Box()
second_box.add(button)

box.add(first_box)
box.add(second_box)




###the second box refuses to show on run

**Comment by sasilva1998** [comment]
Something alike is happening to me with the following project:
https://github.com/FunPythonEC/uPy_IDE

It was coded in linux, where it works perfectly and looks like the following:
![test in linux](https://raw.githubusercontent.com/FunPythonEC/uPy_IDE/master/tests/linux/testlinux.png)

When I run it in Mac it looks like the following:
![test in mac first](https://raw.githubusercontent.com/FunPythonEC/uPy_IDE/master/tests/mac/mactest2.png)
The second column does not appear and the rest of the buttons are screenwide.
Also when I click somewhere in the screen, the upper area disappears.
![test in mac first](https://raw.githubusercontent.com/FunPythonEC/uPy_IDE/master/tests/mac/testmac1.png)

**Comment by freakboy3742** [comment]
Interesting ... I can't think of any obvious cause for those problems; I'm guessing you've (both) found a bug. 

The problem exists in one of four possible areas:
1. An error in hinting the size of widgets to the layout
2.. an error evaluating the layout for the widgets
3. an error applying the layout to widgets 
4. an error updating the layout of existing widgets when a change occurs.

(or possibly a combination of multiple factors).

The fact that @sasilva1998's example layout works on GTK, but not on macOS suggests that it's not (2). (1) or (2) is a good candidate for the initial layout failure; (4) is a good candidate for the "resize on click" problem. 

@Joetib's layout problem, on the other hand, is more likely to be (1) or (2) (although I could be wrong on that - reproducing that layout on a different platform would be helpful in eliminating 3/4 as a source of the problem)

One helpful piece of debugging information is whether the layout "fixes" itself if you resize the window. Window resizes force a re-evaluation of window layouts, which can help identify if the problem is 2 or 3.

Another source of debugging information is edit toga/core/style/applicator.py, and uncomment the debug print statement in set_bounds(). That will output the evaluated position of the widgets to be displayed, giving you a way to narrow down the source of the problem.

The other thing that is helpful is to narrow down the problem to the smallest example that demonstrates the problem you've found. @Joetib's example is the sort of thing I'm talking about - While @sasilva1998's example is clearly a problem, it's difficult to know *what* is the underlying source of the problem. Is it a text box? A layout box? a button? the combination of a layout box and a button? Narrowing down the example to the simplest possible reproduction case can help identify the source of the underlying issue.

**Comment by obulat** [comment]
I've checked the first example on Windows. The layout doesn't fix itself when you resize the window. The second box is actually placed to the right of the window, its position is {Width=75, Height=24} @ {X=640,Y=0} in the beginning.

**Comment by obulat** [comment]
In `style\pack.py`, in the second pass when laying out row children (lines 184-217), the comments state 
```
# Pass 2: Lay out children with an intrinsic flexible width,
# or no width specification at all.
```
However, only two conditions are handled:    if `child.style.width` and `elif child.style.flex`. So, in this example, child doesn't have width and doesn't have flex, and it nothing is done in Pass 2.

**Comment by CarlosFFM** [comment]
@freakboy3742 , I have worked on @sasilva1998 's code and the second box does show properly when it is the only box in the main box. Reversely, the first box is not shown when it is added as the second children. This makes me think that it might be a problem on the way it "gives weight" to the children, since there seems to be no problem with the children themselves. Any ideas?

**Comment by HK416A5** [comment]
@Joetib  Hi！Change your code `box = toga.Box()` to this:`box = toga.Box(style=Pack(direction=COLUMN))`,you will find the button(second box) under the first box. I hope this can help you.
