### ISSUE TITLE
Tutorial 3 - right pane scrolling issue

### ISSUE THREAD

**Issue by maramaraz** [beeware/toga#721]
## Expected Behavior
I expect right pane of tutorial 3 window to be scrollable since we have line 
```right_container = toga.ScrollContainer(horizontal=False)```

## Current Behavior
Vertical scrollbar is invisible and window is short thus not showing all of the action buttons on the right pane. Instead of showing 10 buttons, only 4 are visible unless the window is stretched manually by dragging the bottom line of the window.

## Your Environment
I am running Toga on Ubuntu 16.04 with Anaconda Python. Virtual environment is made with ```conda``` instead of ```virtualenv```.

* Python Version - ```3.6.8``` from ```--conda-forge``` channel

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)
  - [ ] Linux - distro:   - version: Ubuntu 16.04

* Toga Target (the type of app you are trying to generate)
   - [ ] gtk

**Comment by freakboy3742** [comment]
Confirming I can reproduce this; thanks for the report. 

This is a problem that surfaces occasionally - and it's a bit of a pain to diagnose and fix. It's also a pain because we don't currently have a test suite that can confirm these problems don't resurface. 

It usually relates to the information being provided to the layout hinting process - the math inside the widget layout algorithm needs to determine the size of the scroll box, and the size of the content *inside* the scroll box. For whatever reason, the internal size is being truncated, and so, no scroll occurs.

**Comment by CliveBuxton** [comment]
I am currently deep into an investigation of this and similar problems (re #721) and it is a bit of a 'layers of the onion' issue as I am convinced that there is more than one bug in play here. I am happy to discuss what I have found so far. One thing that certainly appears to be a bug appears in all containers (with the exception of box) is, I believe an oversight in the following code:-
def add_content(self, label, widget):
""" Adds a new option to the option container.
Args:
label (str): The label for the option container
widget: The widget or widget tree that belongs to the label.
"""
widget.viewport = CocoaViewport(widget.native)

    for child in widget.interface.children:
        child._impl.container = widget

    item = NSTabViewItem.alloc().initWithIdentifier(len(self.interface.content) - 1)
    item.label = label

    # Turn the autoresizing mask on the widget widget
    # into constraints. This makes the widget fill the
    # available space inside the OptionContainer.
    widget.native.translatesAutoresizingMaskIntoConstraints = True

    item.view = widget.native
    self.native.addTabViewItem(item)
The code correctly attempts to run through the widget.interface.children of the current widget being added. However, if the widget being added is an option, scroll or split container then it cannot, by definition, have any children. Instead these containers have a content widget list instead of a children widget list consequently the container widget and any children that it may have do not get updated. As a test I have modified the code in these container to the following:-

    for child in widget.interface.children:
        child._impl.container = widget

    # TODO TOGAFIX The widget itself may be a container
    if hasattr(widget.interface, '_content'):
        for content_item in widget.interface._content:
            content_item._impl.container = widget
I am not suggesting that this is the correct solution but it has allowed me to progress further. There are still some anomalies in play that I am currently working on. If anyone wants to discuss this further it may be easier to chat directly and swap ideas rather than clutter up this board because, believe me, it does run deep and get very involved! By way of example I have a SplitContainer which in its right hand panel has an OptionContainer containing a Box. (We can ignore the SplitContainers left hand panel for now). That Box has three Label widgets added to it at different point in the code. The sequence is as follows:
1) Create a Box
2) Add a Label to the Box
3) Add the box to an OptionContainer
4) Add a second Label to the Box
5) Add the OptionContainer to the main window
6) Show the main window
7) On pressing a button (detail not given here) add a third Label to the box

Without the code modifications highlight above only Label 1 is ever displayed. Labels 2 and 3 are in the node tree and have what seems like a valid layout but do not appear in the window. Label_1's container is the Box (as I would expect), Label_2 has its container set to None and Label_3s container is the SplitContainer. I would expect Label_2 and Label_3 to have the same container as Label_1 since they are added directly to it.

With the code modifications in place then all three Labels are displayed but not as expected. Upon investigation Label_1's container is the Box as expected while Label_2 and Label_3's container are both set to the SplitContainer. The net effect is that I now get multiple split containers on the display each one containing one of the labels.

**Comment by freakboy3742** [comment]
This appears to have been resolved.
