### ISSUE TITLE
Canvas documentation error? (no attribute 'translate')

### ISSUE THREAD

**Issue by bittner** [beeware/toga#730]
## Expected Behavior

I'm trying to run the code samples from the [Canvas documentation](https://toga.readthedocs.io/en/latest/reference/api/widgets/canvas.html). They should run flawlessly.

## Current Behavior

Code sample 3 ("example with a platformer game") fails with an `AttributeError`:

```python
AttributeError: 'Context' object has no attribute 'translate'
```
The affected line is:
```python
hero.translate(10, 0)
```

## Steps to reproduce

1. Generate a briefcase cross-platform app
2. Add code sample 3 from the Toga Canvas docs
3. Run `python3 setup.py linux -s`

## Your Environment

* Python Version: 3.6.8

* Operating System and Version:

  - [ ] macOS - version:
  - [x] Linux - distro: Ubuntu  - version: 18.04.3 LTS Bionic
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version: 0.3.0.dev12

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [x] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Thanks for the report.

No idea what's gone wrong here; @danyeaw Can you shed light on the problem?

**Comment by Bobw147** [comment]
I personally feel that 2 is the only realistic option. On MacOs at least it is recommended practice to use a canvas context rather than write to the canvas directly as this brings a host of other benefits with it . It follows that the  lack of a translate function at the context level would be a serious omission.

**Comment by hodgestar** [comment]
I need `context.translate` for a small app I am writing. I could perhaps implement it. Do I only need to add support to https://github.com/beeware/toga/blob/main/core/src/toga/widgets/canvas.py? Or will I need to delve into individual implementations too? Or unclear?

Would it be sane to maintain a `Translate` object at the start of the objects to draw and update that as needed? Or a separate Translate on each context instance?

**Comment by freakboy3742** [comment]
As a guide - broadly speaking, the Canvas API is trying to follow the HTML5 Canvas API, with the conceit that the JS APIs to save/restore context are converted into a context manager in Python. 

I'd need to dig into the code to be sure about the translate call specifically, but I suspect this will require changes to both the core API, and the platform implementations - but I could be wrong on that. 

The good news is that we're nearing the completion of an audit of all the widgets, and I should be looking at Canvas in a week or two. I'll make sure this issue is on the list to be looked at; but, of course, if you want to take a look at it before I get there, be my guest :-)
