### ISSUE TITLE
Error setting CSS direction='column' 

### ISSUE THREAD

**Issue by BrendanSimon** [beeware/toga#761]
## Expected Behavior

I'm trying to set the direction of a box to `column` (vertical stacking for the children).  A simple layout with 3 boxes that have horizontal (direction=`row`) stacking, inside a main box that has vertical stacking (direction=`column`).

## Current Behavior

Get an error telling me the allowed values for CSS direction are `ltr` and `rtl`, but the docs say that `row` and `column` are allowed values for `toga.Box` direction.

$ briefcase dev

```
[sggc_live] Starting in dev mode...
Traceback (most recent call last):
  File "/Users/brendan/Sandbox/sggc_live/venv/lib/python3.7/site-packages/colosseum/declaration.py", line 52, in setter
    value = choices.validate(value)
  File "/Users/brendan/Sandbox/sggc_live/venv/lib/python3.7/site-packages/colosseum/constants.py", line 54, in validate
    raise ValueError()
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/brendan/Sandbox/sggc_live/sggc_live/src/sggc_live/__main__.py", line 4, in <module>
    main().main_loop()
  File "/Users/brendan/Sandbox/sggc_live/venv/lib/python3.7/site-packages/toga/app.py", line 189, in main_loop
    self._impl.main_loop()
  File "/Users/brendan/Sandbox/sggc_live/venv/lib/python3.7/site-packages/toga_cocoa/app.py", line 185, in main_loop
    self.create()
  File "/Users/brendan/Sandbox/sggc_live/venv/lib/python3.7/site-packages/toga_cocoa/app.py", line 125, in create
    self.interface.startup()
  File "/Users/brendan/Sandbox/sggc_live/sggc_live/src/sggc_live/app.py", line 40, in startup
    style=CSS( direction='column' ),
  File "/Users/brendan/Sandbox/sggc_live/venv/lib/python3.7/site-packages/colosseum/declaration.py", line 131, in __init__
    self.set(**style)
  File "/Users/brendan/Sandbox/sggc_live/venv/lib/python3.7/site-packages/colosseum/declaration.py", line 446, in set
    setattr(self, name, value)
  File "/Users/brendan/Sandbox/sggc_live/venv/lib/python3.7/site-packages/colosseum/declaration.py", line 55, in setter
    value, name, choices
ValueError: Invalid value 'column' for CSS property 'direction'; Valid values are: ltr, rtl

Unable to start application 'sggc_live'
```

## Your Environment

* Python Version 3.7.6

* macOS Catlina

* Toga Version
    * beeware==0.3.0.dev1
    * briefcase==0.3.0.dev1
    * toga==0.3.0.dev15
    * toga-cocoa==0.3.0.dev15
    * toga-core==0.3.0.dev15
    * toga-iOS==0.3.0.dev15
    * colosseum==0.2.0

* Toga Target (the type of app you are trying to generate)
    * macOS
    * iOS

Here is my code (o
```python
import toga
from colosseum import CSS
#from toga.style import Pack
#from toga.constants import COLUMN

class SGGC_Live( toga.App ) :

    def startup( self ) :
        #! Create the main window
        self.main_window = toga.MainWindow( self.name )

        head_box = toga.Box( id='head_box', style=None, children=None )
        body_box = toga.Box( id='body_box', style=None, children=None )
        tail_box = toga.Box( id='tail_box', style=None, children=None )

        main_box = toga.Box( 'main_box',
                             style=CSS( direction='column' ),
                             children=[ head_box, body_box, tail_box ]
                             )

        self.main_window.content = main_box

        #! populate boxes with widgets
        head_text = toga.Label( 'the head' )
        head_box.add( head_text )

        body_text = toga.Label( 'the body' )
        body_box.add( body_text )

        tail_text = toga.Label( 'the tail' )
        tail_box.add( tail_text )

        #! Show the main window
        self.main_window.show()

def main() :
    return SGGC_Live( 'SGGC Live', 'au.com.etrix.sggc_live' )
```

Am I doing something wrong?

**Comment by BrendanSimon** [comment]
I also tried setting the style post instantiation and get errors too, as mentioned in the docs.

https://toga.readthedocs.io/en/latest/reference/api/containers/box.html

```python
main_box.style.set( flex_direction='column', padding_top=10 )
```

```
$ briefcase dev

[sggc_live] Starting in dev mode...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/brendan/Sandbox/sggc_live/sggc_live/src/sggc_live/__main__.py", line 4, in <module>
    main().main_loop()
  File "/Users/brendan/Sandbox/sggc_live/venv/lib/python3.7/site-packages/toga/app.py", line 189, in main_loop
    self._impl.main_loop()
  File "/Users/brendan/Sandbox/sggc_live/venv/lib/python3.7/site-packages/toga_cocoa/app.py", line 185, in main_loop
    self.create()
  File "/Users/brendan/Sandbox/sggc_live/venv/lib/python3.7/site-packages/toga_cocoa/app.py", line 125, in create
    self.interface.startup()
  File "/Users/brendan/Sandbox/sggc_live/sggc_live/src/sggc_live/app.py", line 44, in startup
    main_box.style.set( flex_direction='column', padding_top=10 )
AttributeError: 'Pack' object has no attribute 'set'

Unable to start application 'sggc_live'
```

**Comment by freakboy3742** [comment]
Looks like there's a couple of competing bugs here.

The first is definitely a documentation error. The `style.set()` API is an error on our part; it should read `style.update()`. I'll make that change ASAP; thanks for the report.

The other problem is a source of confusion. You've opted into using Colosseum for style properties, rather than using the built-in default "Pack" engine that ships with Toga. Colosseum is designed to be a fully standard-compliant CSS style engine; however, it's still very much a work in progress. In CSS, the `direction` property is used to control RTL/LTR; you'd be looking for `flex_direction`, but Colosseum doesn't support the `flex_direction` property yet.

Pack is a simplified version of CSS, unique to Toga; *most* of the properties are the same, but a couple are slightly different. One of those properties is `direction`. So, `column` is a valid value for direction in *Pack*, but not in CSS. 

Toga 0.2 used Colosseum; for 0.3, we decided that it was going to take too long to get a fully flex and grid compliant CSS box model implemented, so we adopted a simpler layout engine (Pack) as a transition measure. 

Unfortunately, in addition to the `style.set()`/`style.update()` bug, the documentation for Box also mentions Colosseum. So - this one is on us as well; the docs for Box pointed you in the wrong direction. Apologies for the confusion on this; I'll update this aspect of the docs as well.

The good news is that the two style engines *should* be compatible, and adopting Pack now won't lead to you being abandoned in future. One of the intentional goals of the transition was to abstract the styling away from the widget itself. In theory, it should even be possible to *mix* Pack and CSS styling (although some of the interactions could get interesting). It should also be possible to implement completely different layout mechanisms (e.g., constraint-based layout).

So - if you want to use Colosseum for your app, you can do so; however, you're probably going to hit some edge cases. Alternatively, you can use Pack; If you change your sample code to instantiate Pack rather than CSS on your `main_box`, your app should run.

**Comment by BrendanSimon** [comment]
From my perspective I want to use what ever is easiest, and best supported.  Sounds like `Pack` is the way to go, and that `CSS` might be a longer term goal that can be migrated to sometime in the future if/when there is a need.

**Comment by BrendanSimon** [comment]
Ok, so using Pack seems to improve things, but the text in the boxes seems to be truncated for some boxes, and which boxes get truncated changes depending on the text contents.

```python
        #! populate boxes with widgets
        head_text = toga.Label( 'the head' )
        head_box.add( head_text )

        body_text = toga.Label( 'the body' )
        body_box.add( body_text )

        tail_text = toga.Label( 'the tail' )
        tail_box.add( tail_text )
```

results in:

<img width="245" alt="Screen Shot 2019-12-22 at 3 21 05 pm" src="https://user-images.githubusercontent.com/472245/71317104-a39c9680-24cf-11ea-81fa-c298896276b0.png">

and ...

```python
        #! populate boxes with widgets
        head_text = toga.Label( 'the head 123' )
        head_box.add( head_text )

        body_text = toga.Label( 'the body 456' )
        body_box.add( body_text )

        tail_text = toga.Label( 'the tail 789' )
        tail_box.add( tail_text )
```

<img width="253" alt="Screen Shot 2019-12-22 at 3 20 07 pm" src="https://user-images.githubusercontent.com/472245/71317111-ca5acd00-24cf-11ea-8ec3-8c31abc705f8.png">

**Comment by BrendanSimon** [comment]
Also setting `Pack( flex=1 )` to both `body_box` and `main_box` doesn't seem to do anything.

I was expecting that setting `flex=1` for `body_box` would mean that the `body_box` would expand and fill up all the space between `head_box` and `tail_box`.  But no change.

I though maybe `main_box` needed to expand to, so I set `flex=1` for `main_box` too, but still no change.

How do I tell a box to expand it both directions?

In wxWidgets there is a `proportion` setting (similar to `flex`) and an expand setting for the other direction.  It's not the easiest API to understand, but is there something similar in Toga?

**Comment by freakboy3742** [comment]
The trimmed text is definitely odd... and definitely a bug. My initial guess would be that for some reason, the size being allocated to the label is slightly too small to fit the actual text, and it's not displaying the content that doesn't fit. I'll have to investigate further.

`flex=1` by itself may not affect the layout. You also need to specify the direction in which the flex applies. This will default to ROW. There's also the question of whether you want the *box* or the *label* to be flexible. Without knowing what your goal layout is, it's difficult to provide specific suggestions.

There essentially isn't an "expand in both directions" option. This is something common with HTML layout.

**Comment by BrendanSimon** [comment]
I was just applying the Pack to the box, as in:

```python
        body_box = toga.Box( id='body_box', style=Pack( flex=1, padding=20 ) )

        main_box = toga.Box( 'main_box',
                             style=Pack( direction=COLUMN, flex=1 ),
                             children=[ head_box, body_box, tail_box ]
                             )
```

My goal at this stage is just trying to understand how the layout engine works - it doesn't seem to different to wxWidgets which uses "sizers" (which are effectively "boxes").

Short term my target would be a mobile app (ios and android).  I'm trying to limit myself to widgets supported on both those targets, which is quite a narrow selection at this stage.

My test layout is:
* a horizontal (row) header at the top (not sure what will go in it - possibly icons or text for navigation?)
* a horizontal (row) footer at the bottom (not sure what will got in it - possibly icons or text)
* a body (or main pane) which will have relevant content depending on selections in header and footer.

At the moment I'm just starting with static text (and maybe make it "fancy" by changing the alignment).

BTW, is there a "grid" type of box layout?  e.g. N x M rows/columns, with flex settings for each row or column?

**Comment by BrendanSimon** [comment]
This may be a clue (or a red herring?), but if I change the spaces in the text to underscores, then I get better results.  More of the text is displayed, although the first row had one character truncated.

Using a dash `-` gave a odd results.  some text displayed better, and some worse (less characters shown).

I tried passing bytes instead of strings (`b'some bytes to show'` but that actually display the `b` and the text enclosed in single quotes (just a `repr()` would display).  e.g. `b'some bytes to show'` was actually displayed on screen.  This was very unexpected.

**Comment by BrendanSimon** [comment]
Actually, using the `text_align` attribute for labels works better than the `alignment` attribute.  The padding seems to be working better now.  I thought the padding applied between children but it just applies to the perimeter of the children.

**Comment by freakboy3742** [comment]
I don't know if you've come across this, but Pack is documented [here](https://toga.readthedocs.io/en/latest/reference/style/pack.html); the full algorithm is described at the bottom of that page.

We don't currently have a grid layout; however, adding something akin to CSS3 grid layouts is on the list of things we want to add.

**Comment by BrendanSimon** [comment]
Yep, that's what I'm working from with a bit of trial and error.
The text rendering thing is the biggest issue at the moment.  It just does crazy things depending on the text content (even the same length text but different chars).  e.g. if you have a leading space, then sometimes NOTHING gets shown.  changing one char (e.g. the first char) can lead to the last char being displayed or not).

The data looks ok, it's just the rendering.  I think it's the label object.  I've tried 3 labels in a box and all three labels do the same thing, with the same text.

The grid layout would be a very useful addition - to display data in a tabular format ;-)

**Comment by BrendanSimon** [comment]
BTW, I see quite a open few pull requests.  Are any of them likely to help or be merged soon?

**Comment by freakboy3742** [comment]
I'm not aware of any outstanding PRs that relate to the layout algorithm specifically. I need to do some housekeeping in the Toga PR inbox though - briefcase has been getting most of my attention recently.

There are two places to start digging if you're in a debugging mood:

 1. The [hints provided for the Label widget](https://github.com/beeware/toga/blob/master/src/cocoa/toga_cocoa/widgets/label.py#L36). This is the hint provided by the widget to the layout algorithm. This is the "wishlist" size; in the case of label, it's specified as a minimum size on the width. The layout algorithm will use this hint to evaluate the actual, final size.
 2. The [point at which the style is applied](https://github.com/beeware/toga/blob/master/src/core/toga/style/applicator.py). This is the final computed size and position of the widget.

My guess is that either (1) is returning something smaller than it should for Labels, (2) the layout algorithm is deciding space is at a premium and isn't allocating enough space, or (3) there's something undocumented about punctuation or spacing on labels on Cocoa that isn't being allowed for.

The other thing that is worth checking is whether the behavior is reproducible on other platforms. If it works on Linux/Windows, but not on macOS, then that points to a problem with the Cocoa backend, rather than the Pack algorithm itself.

**Comment by BrendanSimon** [comment]
Ran it on Linux (Ubuntu 18.04 LTS) and it seems to be fine, so looks like it might be a Cocoa specific issue.

I will try on iOS as that's what intend to target first anyway.

**Comment by BrendanSimon** [comment]
Also renders ok ion iOS simulator.

NOTE: I had to build/update/run the simulator twice to get any changes to occur.  It as if the app does not get updated on the first run (either during build/update or the install into the sim).

i.e. I have to run this set of commands twice.

```
$ briefcase build ios -d "iPhone 8" && briefcase update ios && briefcase run ios -d "iPhone 8"
```

**Comment by freakboy3742** [comment]
Regarding the Briefcase commands - if I'm reading that right, I *think* it's behaving as intended.

`briefcase build` will compile the code that is already there. `briefcase update` will ensure the user-space code that is in the project is up to date. So - if you had previously run `create` or `run`, the first `build` command would have been re-compiling what was already installed. When you ran `update`, that will have refreshed the code; and the run would have then compiled and executed the new version of the code.

This is a sufficiently common usage pattern that we've added a shortcut - if you pass `-u` to briefcase run, it will update and run in a single command. So - if you're rapidly iterating on a design, running `briefcase run -u -d "iphone 8"` should be sufficient to update, recompile and re-run the code.

**Comment by BrendanSimon** [comment]
Thanks.  Maybe I had the `build` and `update` in reverse order?

`briefcase run ios -u -d "iPhone 8"` worked perfectly.  Much more productive :)
