### ISSUE TITLE
Horizontal line widget?

### ISSUE THREAD

**Issue by SamSchott** [beeware/toga#776]
Some platforms show horizontal lines to visually separate content (as seen in many macOS preference panes).

On macOS, this is typically a NSBox with type NSBoxSeparator. On iOS, this could be a UIView with a 1 pixel hight. I have no idea about other platforms.

Would it make sense to ass this as a Widget?

**Comment by freakboy3742** [comment]
Hi @SamSchott - thanks for the suggestion!

I agree that a separator is a reasonably common widget to see on many platforms.

It's worth noting that not *all* platforms have separators - mobile platforms tend to use other layout metaphors to achieve visual separation. However, they're definitely common to desktop platforms, so adding a separator widget would make sense.

Since it's a widget with no data or interaction component, it should be a relatively simple widget to implement. You should be able to use Button as a starting point for an implementation, if you're inclined to try your hand at a contribution!

**Comment by SamSchott** [comment]
I agree about mobile platforms, having explicit separators there is much less common. But some platforms do support them, for instance SwiftUI has the concept of "Divider" across all apple platforms.

I have gone ahead and added a `Divider` widget with an implementation for macOS, but I have almost no experience with AppKit. At the moment, it only allows for horizontal lines but ideally, it would create a horizontal or a vertical line, depending on the style `direction`. Maybe you know you how to achieve that?

In the meantime, I'll create a pull request with what I have...

PS: I really like the idea of Beeware, native GUIs and packaging are both two areas where Python is lagging behind.

**Comment by freakboy3742** [comment]
This was added by #777.
