### ISSUE TITLE
Visit homepage disabled!

### ISSUE THREAD

**Issue by danielgis** [beeware/toga#843]
The option "Visit home page" is always disabled.

https://github.com/beeware/toga/blob/b2934d3fc8a67af9e2d16ee95909062939cf9f8f/src/winforms/toga_winforms/app.py#L60

I solved it with "import os" and adding the following anonymous function

    toga.Command(lambda s: os.startfile(self.interface._home_page), 'Visit homepage', group=toga.Group.HELP) 

But I need to know if it's possible from Toga without having to edit the source code.

Excuse my English, I'm from Peru!

**Comment by freakboy3742** [comment]
@danielgis It's not currently possible - but only because the pieces needed to provide an implementation haven't been there - and then we need a volunteer to implement this specific feature.

However- the good news is that we *are* now in a position to do so - as you've noticed, the app now tracks it's home page.

If you're interested, we'd love to see a patch that adds your change to Toga itself. Two small tweaks:
1. You should probably invoke `webbrowser.open` rather than `os.startfile`; that's a slightly more reliable mechanism for opening web pages
2. You'll need to add handling for the "home_page is None" case - which will fall back to the historical behavior where the menu item is disabled.

**Comment by gauraws** [comment]
Hi, I am beginner, how can I work on this issue?

**Comment by freakboy3742** [comment]
@gauraws Submit a pull request! If you need help getting a development environment set up, our [contribution guide](https://toga.readthedocs.io/en/latest/how-to/contribute.html) can provide some pointers. The ticket description gives you some broad direction of what is required; turn that into a pull request, and we'll review your work for inclusion.

**Comment by gauraws** [comment]
Thanks @freakboy3742 , I will try my best.

**Comment by saroad2** [comment]
This issue was fixed in #1064
