### ISSUE TITLE
tests.test_image.ImageTests cannot pass

### ISSUE THREAD

**Issue by elelay** [beeware/toga#862]
## Expected Behavior

all tests pass

## Current Behavior

```
======================================================================
ERROR: test_object_created (tests.test_image.ImageTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/elelay/devel/gpodder-toga/toga/src/core/tests/test_image.py", line 20, in test_object_created
    self.image.bind(factory=toga_dummy.factory)
  File "/home/elelay/devel/gpodder-toga/toga/src/core/toga/images.py", line 29, in bind
    full_path = factory.paths.app / factory.paths.Path(self.path)
  File "/home/elelay/devel/gpodder-toga/toga/src/dummy/toga_dummy/paths.py", line 14, in app
    return Path(sys.modules[App.app.module_name].__file__).parent
AttributeError: 'NoneType' object has no attribute 'module_name'
```

## Steps to reproduce
follow contribute steps

## Your Environment

* Python 3.8.2

* Operating System and Version 

  - [ ] macOS - version:
  - [x] Linux - ArchLinux
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
c940d61c

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [x] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

## Resolution

This testcase doesn't create an App, so `paths.Paths.app()` allways encounters a None in `App.app.module_name` in [toga_dummy/paths.py](https://github.com/beeware/toga/blob/master/src/dummy/toga_dummy/paths.py#L14).

This could be fixed in different ways:

 - change `Paths.app()` in dummy/paths.py to return `Path.cwd()` when not `App.app`

 - or change toga/images.py for bind to not go for `Paths.app` if the image's path is absolute.
   Also change the test case to use an absolute path (won't exist anyway)

**Comment by freakboy3742** [comment]
It's highly unusual that you're seeing this failure, because CI runs the full test suite multiple times, on multiple platforms before we merge any patch, and we haven't see any test failures of the kind you describe.

That said, the bug you're reporting *is* familiar to me. We saw an analogous failure in the icon tests a while back; the fix is to [introduce a dummy app](https://github.com/beeware/toga/commit/0c2696169641bbf8769dd215aec5025f9303996a).

I'm going to close this on the basis that the tests *are* passing in CI, so from the perspective of Toga as a project, this is a local configuration issue. However, if you want to submit a PR that introduces a dummy app to avoid this issue, we'll gladly merge it.

**Comment by elelay** [comment]
This is because tests don't execute in the same order on my machine than on the CI.

[latest test logs](https://pipelines.actions.githubusercontent.com/tEgstvUbS2DYVNlCvpfqvj5VfmCbllQsp1A9LUgyMYyYMlTat4/_apis/pipelines/1/runs/301/signedlogcontent/3?urlExpires=2020-04-26T09%3A11%3A28.3397243Z&urlSigningMethod=HMACV1&urlSignature=Vy75Z1tmKkGBUKh%2BJu9IYZ5u06YgrNzU9%2FmwxDonRkw%3D):

1. test_font
2. test_window **instantiates an app**
3. test_image

On my machine

1. test_source
2. test_accessors
3. test_list_source
4. test_tree_source
5. test_value_source
6. test_image

I'll submit a PR creating an app in test_image as you recommend.
