### ISSUE TITLE
Slider ticks in Windows

### ISSUE THREAD

**Issue by saroad2** [beeware/toga#893]
## Expected Behavior
The `Slider` widget in Mac is *continuous*. In Windows, the slider is *discrete*, which means it has *ticks*. This creates a different behavior for Windows and Mac.

## Possible Solution 1
Add a new input parameter to `Slider` named `tick_delta`. if `tick_delta` is `None`, sets the `Slider` to be continuous. Otherwise, sets the ticks delta as defined.
Under the hood, in Windows when the user set `tick_delta=None` we'll set the actual tick delta to a very small value (0.01 for example), which will make it seem like a continuous slider.

API code examples:

```python
default_slider = toga.Slider(range=(0,1))  # Creates a continuous slider by default
continous_slider = toga.Slider(range=(0,1), ticks_delta=None)  # Creates a continuous slider
discrete_slider = toga.Slider(range=(0,1), ticks_delta=0.1)  # Creates a slider with 10 ticks
```

## Possible Solution 2
In Windows, implement the underlying `TrackBar` with range between 0 to 100, but toga will return:
```real_value / 100 * (max - min) + min```
In that way Windows TrackBar will look like it is continuous.

## Steps to reproduce
Run the slider example in Windows and see that the `Slider` between 0 and 1 can only get a value which is 0 or 1 and not the values in between.

## Your Environment

* Python Version (list the specific version number) - 3.7

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version:
  - [ ] Linux - distro:   - version:
  - [X] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash) - latest

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [X] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
Agreed that adding a "tick" behavior makes sense. On platforms that are continuous-only, we can round the actual value to be compliant with ticks; on platforms that are tick-only, we can make the number of ticks large enough that it's largely indistinguishable. 

It might be desirable to specify the ticks in terms of "how many ticks" rather than a specific step size. That way we don't end up doing odd math to work out an "appropriate" size for the tick (0.01 is a fine tick size if you're running from 0 to 1, but would be absurd for 0-100). In contrast "use 100 ticks" will give the same fidelity regardless (and on tick-only Windows, a 100 tick default would work regardless of the range)

**Comment by saroad2** [comment]
That's exactly what I did in #898.
I added a "number_of_ticks" property to `Slider`.
