### ISSUE TITLE
PasswordInput not working

### ISSUE THREAD

**Issue by MMartin09** [beeware/toga#895]
## Expected Behavior

The PasswordInput is not working.

## Current Behavior

I tried to use the "initial" flag. For example `toga.PasswordInput(inital="test")` and get the following error: AttributeError: 'PasswordInput' object has no attribute '_on_change'

## Steps to reproduce

1. Create a class containing a toga.MainWindow()

2. Create a toga.Box() and add a PasswordInput

3. Run the MainLoop()

## Your Environment

Toga 0.3.0dev19

* Python Version (list the specific version number)
Python 3.7

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version:
  - [ ] Linux - distro:   - version:
  - [x] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by saroad2** [comment]
After a little research, it seems like the problem is caused because Windows `PasswordInput` implementation inherits from `TextInput`, **but** `TextInput` has `on_change` handling while `PasswordInput` doesn't. 

There are 2 possible solutions:
1. Add the `on_change` handling to  `PasswordInput` **in all platforms**. The question is: is this functionality really needed for `PasswordInput`? I don't know
2. A more simple solution would be to make a small patch in `PasswordInput` windows implementation to avoid calling `on_change`. This is a one-line fix that I can easily do.

@freakboy3742 , what do you think is the right solution in this case?

**Comment by freakboy3742** [comment]
@saroad2 My inclination would be to make on_change work on all platforms. The obvious use case I can think of would be validating passwords before submission - confirming whether the user has typed a "good" password, or if two password entries are consistent.

Aside from that, consistency is always a good thing.
