### ISSUE TITLE
Why do you do what you do?

### ISSUE THREAD

**Issue by guettli** [beeware/toga#902]
# Why do you do what you do?

Progressive Web Apps are the future.

I don't want to create a native app.

I want get rid of this useless language called JavaScript.

Then I can use Python everywhere: on the server and on the client (chrome).

Do you really think native apps are the future?

**Comment by MMartin09** [comment]
I think PWA's are the future but I also think they will not replace all native apps (in the next years).

**Comment by freakboy3742** [comment]
Yes, I believe native apps are are part of the future. "Progressive Web Apps" have been declared to be "the future" for several years, but I'm yet to see a single one that provides a user experience even remotely comparable to a native application.

That said - the web is still an important platform. And that's why BeeWare as a project, and Toga as a library, has demonstrated support for web as a deployment target. That support is definitely lagging - but that is a matter of resources.

Fundamentally, my argument is this: An app is a a way of specifying an API that meat can use to control a computer. That API is independent of the computer itself. "I want a button. The button will be Red, and will say "RECEIVE BACON". When I push the button, I want to place an order of bacon". No part of that description mentioned "mobile phone" or "web browser".

High level APIs exist to abstract implementation details. To my mind, the web browser is nothing more than a low level way to render a user interface. A mobile phone provides it's own APIs for rendering a user interface. So does a desktop OS. BeeWare is my attempt to provide a way to control that low level interface using a programming language that I like, and use a common high level API to target multiple low level platforms.

**Comment by guettli** [comment]
Thank you for explaining your idea.

At the moment Python has a great market share (at least on stackoverflow): 

![image](https://user-images.githubusercontent.com/414336/81713038-a7788780-9475-11ea-9984-53148fef5264.png)

Source: http://sotagtrends.com/?tags=python+typescript+javascript

I really don't like JavaScript. But at the moment you can't avoid it.
I feel fear that Python will loose the battle. V8 (JS engine of Node.js and Chrome) is very
good. It would be great if you could do frontend development (in the browser) via web-assembly in python.
