### ISSUE TITLE
Input validator

### ISSUE THREAD

**Issue by MMartin09** [beeware/toga#909]
## Expected Behavior

To distribute an application one of the most important things is the validation of inputs. Due to this 
most GUI/Web frameworks provide some validator functions. 

I think validators are really missing in Toga. Currently I use the on_change attribute to call a
function which validates the input and do something based on the truth value. (https://gist.github.com/MMartin09/481bb0a5b1126c5616837bad316f7230) 
But I think there are better ways. 

For example a is_valid attribute which is the return value of a provided validate function. So I think
this could look something like this:

```python
self.text_input = toga.TextInput(validate_command=self.input_validator)

if self.text_input.is_valid:
  # do soemthing
```

Maybe there are other better ways but I think input validators are quite useful.

**Comment by freakboy3742** [comment]
I agree this is an interesting use case; however, I don't think it's as simple as you suggest.

Consider the case of a TextInput widget with an "email address" validator. 

When does the "on_change" message fire? It would currently file after every keystroke... but should it still fire if the content isn't valid? Typing `me@` is a necessary precursor to typing `me@example.com` - and there have definitely been keystrokes... but should the event fire? 

Also - when the user has typed `me@` - what does `input.value` return? It doesn't seem sensible that you should be able to retrieve an *invalid* value from a widget.

There's a couple of possible changes that could be made to support these problems; e.g.,
* `on_change` notifications include a boolean flag that indicates if the content is valid according to the validators.
* `on_change` notifications only fire *if* the content is valid.
* `widget.value` raises a `ValueError` if the current value isn't valid.

However, I can easily imagine that any of these changes would be surprising to at least *some* users. 

Another possible approach is to leverage the "source" idea that is used by Table and Tree widgets. Table and Tree widgets currently use "sources" as a way to abstract their representations of lists and heirarchies of data, respectively. I've long wanted to add a "single value" source that can be used for TextInput (and other single-value widgets). Maybe this is also the point at which validation occurs. That way, the value of the *widget* is whatever is currently on the screen, but the "source" isn't updated until the data is "valid"; if you want to be notified when a *valid* change has been made, you subscribe to the *source* events, rather than the widget.

Thoughts?

**Comment by MMartin09** [comment]
I think it depends on usage. If the validator is called after every keystroke and only updates the `is_valid` attribute there will be no problem. So when you type `me@` the code 

```
print(self.text_input.is_valid)
```

will print `False`. So I would test the valid state in a button event handler. 

For example if I have three text inputs (First name, last name, and email) and a submit button then I would create a submit function like this:

```
def submit(self, event):
  if not self.first_name.is_valid:
    # don't submit and show a warning

  if not self.last_name.is_valid:
    # don't submit and show a warning
```

So the `value` will always return the value of the widget. My idea wouldn't change anything of the current behavior it would add an `is_valid` attribute which will be updated after every_keystroke. But it will not trigger any action. If I want to know if the current input is valid I have to test it with the `is_valid` attribute.

**Comment by freakboy3742** [comment]
The problem I've got with that sort of "minimalist" proposal is that there's absolutely nothing about it that needs to be done in the widget

The validation scheme you've described that has no interaction with the actual widget, other than the fact that the validation logic is stored on and executed by with widget. Your "is_valid" property could just as easily be a function entirely external to the widget; it requires no knowledge of internal state, and has no impact on the operation of the widget. So - we'd be making the widget implementation more complicated, but not actually gaining anything from that complication (at least - nothing that couldn't be gained *without* the extra complication).

However, the manner in which you suggest this validation scheme would be used is tied to a "submission" handler (which is presumably a button handler). That hints towards a better approach: a "forms" framework that leverages Toga widgets. 

The use case you describe isn't just about the text input - it's a mechanism for rendering and submitting inputs. It involves a "submission" workflow and the display of error messages. In the same way that a web framework can simplify the process of rendering HTML forms, I can easily imagine a wrapper around Toga widgets that:
 * simplifies the process of building a "Form" UI in your application; 
 * validates as you enter data, displaying error messages;
 * differentiates between validation that can be done locally, and validation that requires a server round trip or is otherwise slow;
 * A "submit" button that does final validation and submission.
 * A default layout/rendering based on best UX practices, but flexibility to manually manage layout yourself if you wanted to.

Does that sound potentially useful?

**Comment by MMartin09** [comment]
So you think there should be an input form similar to HTML forms. So you would create a new object of the form and add the input widgets. For example

```
self.input_form = toga.InputForm()

self.first_name = toga.TextInput()
self.last_name = toga.TextInput()
self.submit_button = toga.Button()

self.input_form.add(self.first_name)
# ...
```

The input form will then take care of the formatting (for example place all widgets among themselves). And when you hit submit a function will validate every input widget and the submission will only be done if every input is valid. So there is a way required how a validator could be added. Maybe something like this

```
def first_name_validator(value) -> bool:
  # validate the value

self.input_form.add_validator(self.first_name, first_name_validator)
```

Then the input form requires a label to display the error. Maybe this could be done automatically so if you add a widget to the input form it will create a hidden label below (or right?) the widget. If the validator returns false this label gets displayed and shows the error message.

I hope that's what you imagined.

**Comment by freakboy3742** [comment]
I was actually thinking something higher level - closer to Django Forms (or simliar), where you describe a class; form elements are attributes of the class description; validation and other workflows become functions of the class, or are overridden by subclassing.

**Comment by MMartin09** [comment]
Okay, now I understand what you mean. I will create a small example in the next days.

**Comment by MMartin09** [comment]
Since I have never used Django I looked into the documentation (https://docs.djangoproject.com/en/3.0/topics/forms/) and created a small example based on this inspiration. 

I think it is a good idea to create a form that returns a toga.Box. So I can use my form as a normal box in my application. This looks like this:

```
self.main_window = toga.MainWindow(title=self.name, size=(400, 200))
input_form = toga.TogaForm()

box = toga.Box(
            children=[
                input_form.get_form()
            ]

self.main_window.content = box
```

So I create a TogaForm object and add it to my main box (if no other widgets are used I can also set the form as main_window.content)

Next, I would add some example fields. I have created an input field and a submit button.

```
input_form.InputField("Username", required=True)
input_form.InputField("Password", required=True)
input_form.Submit("Login")
```

For me, an input field is created with three things. A label (left), an input field and a hidden label to display an error. For example if I hit the submit button and the login field is empty an assertion will be thrown and the hidden label will be displayed and show the error. 
The required flag is something like a validator I think So this could be extended. For example, an EmailInput could be a subclass of an InputField with a pre-defined email validator. So on submit the value will be validated. If the email format is not correct an assertion will be thrown and the error displayed. 

A further step would be that a user defines his own Inputfield with his own validation function. Or maybe just define his own validation function and pass it to the field. 

The form will also set the length of the label so that all input fields are exactly among themselves. I think this could be done by using the maximal length of a label. 

There are a lot of things which could be added. For example maximal or minimal length of a text. Allow only ascii letters, etc. 

The things I tested are really basic. But I think this would be very useful since input forms are used very often. I really thought about this idea and hope it is what you was thinking of.

**Comment by freakboy3742** [comment]
So... I'm not sure how you look at the Django Form API and arrive at the API you've proposed here. 

The documentation you like gives examples like this one:
```
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)
```
I'm afraid I don't see any connection between *that* syntax, and what you've proposed here.

I can't even work out how you imagine your proposed syntax *could* work. What does `input_form.InputField("Username")` syntax *do*? Is it a function call? In which case, what state is it changing, and why is it capitalized? Is it an instance instantiation? In which case... why are you discarding the return value? What does the "instance" of the input form represent? 

The only part of what you've described that makes any kind of sense is using the `get_form()` call to embed the form "widget" in the layout. However, from an API design perspective, I'd question why the instance itself can't act as a widget (i.e., just adding `input_form` to the layout, rather than needing to invoke something separate).

I feel like you need to spend a lot more time playing around with Django - and looking into the implementation of it's forms - before you start making API proposals for a form API. I'd also recommend at least *prototyping* an implementation - not just writing usage examples - to see what will and won't work.

**Comment by MMartin09** [comment]
So, now I had looked into the code of Danjo and created a working code. Similar to Django I created a class which I called "TogaForm" it subclasses a base form and a meta class. So it would be possible to create a custom form if you want. For me, a form is just a ``toga.Box`` as I think this is the best way to implement it into an application. My example looks something like this:

```
class ExampleForm(TogaForm):
    # code

class ExampleApp(toga.App):
    def startup(self):
        self.main_window = toga.MainWindow(title=self.name)

        self.form = ExampleForm()

        self.box = toga.Box()
        self.box.add(self.form.get_form())

        self.main_window.content = self.box
        self.main_window.show()

def main():
      app = Example('Example App', 'org.beeware')
      app.main_loop()
```

So to create a form I create a class ``ExampleForm`` and subclass the TogaForm class. Then I create a very minimalistic toga app and add the form as a child to the "main"-box of that app. 
The more interesting thing (as I think) are the input fields. 
As I already mentioned a default input field should have a label and the widget. So I created a ``Field`` class which is my base class. This field is a box that contains a ``toga.label`` and a widget. I created two example fields. The first one is an input field so a "normal" ``toga.TextInput`` field without special limitations (I have implemented a min and max length). I think this ``InputField`` could be the base class for example an email field etc. The other example I created is a selection field. It contains the toga selection widget. Created a new field is very easy since it only has to subclass the bases ``Field`` class and call the ``super().__init__`` with the target toga widget. Additionally, it requires to define the validators.

Adding a field to the class is also very similar to Django and could be done like so:

```
class ExampleForm(TogaForm):
    first_name = InputField("First name", min_length=1, max_length=20)
    last_name = InputField("Last name", min_length=1, max_length=20)
```

This is really just a small example. For the layout, I defined rows and columns. So the label and the field are in one row and the next field is in the row below. For a good formating, I thought it would be simple to save the length of the longest label and use that to give them all the same size so all widgets are among themselves. But maybe there is a better way. 

I created the whole code and tested if it is easy to use and I think this is really helpful to create input forms. I really hope that now this is what you meant. I only implemented very basic functions just to test if all this work but if you like this way I think it isn't really much work to implement a few fields like email, name, number, .... and create some validators for that. The most complicated part (as I think) is the layout. To provide the ability to change it as it is required.

**Comment by freakboy3742** [comment]
That's definitely makes a lot more sense. I would question whether the `get_form()` invocation is actually required -  Why can the form instance actually *be* a Box (or at behave like one)?

There's still lots of detail to be fleshed out, though:
* How/when is the form validated?
* How do validation errors manifest in the rendered form?
* How do you handle "multi widget" inputs? e.g., a credit card "field" could be 4 text inputs. 

As for the layout question - I agree that's one of the big outstanding questions; but I'm not sure I see how you're proposing that would work. How are you planning to determine "the length of the longest label"? It seems like what you need to make that sort of layout work is a CSS-style grid layout - getting that sort of layout to work with Toga's Pack is going to be difficult. 

However, more importantly, *customizing* the layout is going to be important. *You* might want to have horizontal lines of form elements; but *I* might want "labels above text inputs"; someone else might want to take full control of the widget layout process. How do you propose to accomodate *those* use cases?

**Comment by freakboy3742** [comment]
(and - to be clear: the answers to many of these questions have prior art in Django's Forms, and other form layout libraries)
