### ISSUE TITLE
Rendering issues with tutorial apps on macOS

### ISSUE THREAD

**Issue by freakboy3742** [beeware/toga#937]
## Expected Behavior

The button from Tutorial 0 should span the entire width of the window.

The buttons and inputs from Tutorial 1 should span the width of the window, in three rows

The buttons on the right panel from Tutorial 2 should be stacked vertically in the scroll box.

## Current Behavior

All widgets in the affected tutorials appear at minimum size, top left of the window.

Some tutorials and demos are not affected. Most notably, the layout works correctly.

## Steps to reproduce

Present in the current HEAD.

Appears to have been introduced by 9067c61b9e535a069d16c6b01096fd7b2854a6b8.

If you restore the `if self.interface.window:` check removed by that commit, the tutorial apps restore correct behavior; however, the layout demo fails to display the initial labels.

## Your Environment

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [x] macOS - version:
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version HEAD (579bd668756f37bcbe69fccdb8375503320fff47)

**Comment by freakboy3742** [comment]
@SamSchott Drawing your attention to this since it appears to be related to your patch to support adding/removing content. No pressure if you don't have time or inclination; but if you do, the assist would be appreciated.

The layout is being computed correctly in both cases; I *think* the problem is that if the widget is added to the container before the window exists, the constraints aren't being set correctly.

**Comment by SamSchott** [comment]
Is it possible that the examples which subclass `toga.App` and override `startup` are working while those that provide a startup method in the constructor are not?

**Comment by freakboy3742** [comment]
That was my first thought too - but converting Tutorial 0 to be "class based" didn't change the behavior.

**Comment by SamSchott** [comment]
Very strange. The issue seems to occur when adding a child when there already is an implementation but no app or window. In this case, setting the container will be called twice (once when adding the child and once when setting the window content).

I'm not sure why this is a problem with some examples and works for others.

**Comment by SamSchott** [comment]
I think the culprit is indeed the following:

https://github.com/beeware/toga/blob/b11687443518793a382f01eb80db59b0649eeaac/src/cocoa/toga_cocoa/widgets/base.py#L73-L74

Setting the container to `self` was supposed to handle the case where a widget does not have a container because it already is the container. This is typically not necessary when children are given in the constructor of a box because the `set_content` methods of Window and Scrollcontainer both iterate over the children to set their containers, for instance:

https://github.com/beeware/toga/blob/b11687443518793a382f01eb80db59b0649eeaac/src/cocoa/toga_cocoa/widgets/scrollcontainer.py#L23-L28

This won't work if the child is added later. Therefore my "fix". For this fix to work when adding a child *after* the Box has become content (for instance of a Scrollcontainer) but *before* it has a window, the IF clause checking for a window needed to be removed.

However, the fix introduced the new issue where the container could be set twice, resulting in the layout problems.

****

I have created a hackish workaround here https://github.com/SamSchott/toga/tree/layout-fixes. Could you try if it also works for you? The better solution however would be for a widget to know that it has become "content" and set its children's containers accordingly.

**Comment by SamSchott** [comment]
I have cleaned up the branch and removed view container hack. Instead, one can check for a viewport to see if the widget is top-level.

Sorry about the mess. I had thought that the layout example already included tests for adding children at different stages of the initialisation - however I apparently missed one important case.

**Comment by freakboy3742** [comment]
No problem at all - this sort of thing is going to keep happening until we get an automated unit test suite that we can run on visual output. Thanks for the fast turnaround on a fix.

I completely agree that there is a need for some cleanup here. There's a lot of convolution around containers, viewports, and their interaction with interface/impl/native. One of the things on my todo list is to sit down and develop some internal documentation around exactly what is happening between all these layers, and see if there's any opportunity for clean up. At the very least, I'd like to get a clearer definition of what a "container" is, because it's currently quite fragmented between different platforms.

**Comment by freakboy3742** [comment]
Fixed by #939

**Comment by SamSchott** [comment]
Agreed, a unit test suite for visual output seems to be increasingly necessary to prevent such issues. Running through all the examples manually is a bit cumbersome.

I also agree on documenting and potentially simplifying the layer structure. At the interface level, the structure is relatively clean with parents and children, only somewhat obfuscated by the inheritance from `travertino.Node`. However, in the implementation layer I was initially very confused about the role of a container and viewport, especially since I have very little experience with UI framkeworks.

Something I noticed: `toga.Box` seems to be the only widget where the concept of "children" is used (for now). Nevertheless, the infrastructure for such hierarchies is inherited by all widgets. This potentially adds to the confusion.
