### ISSUE TITLE
Gtk: Changing Widget colors

### ISSUE THREAD

**Issue by kontsaki** [beeware/toga#949]
Gtk since v3.16 has deprecated explicit functions for setting background/foreground colors like 
`Gtk.Widget.modify_bg`  `Gtk.Widget.modify_fg` or 
`Gtk.Widget.override_background_color` `Gtk.Widget.override_color`

They've instead added an API to CSS styling through the
`Gtk.StyleContext` and `Gtk.CssProvider` (`Gtk.StyleProvider`) objects.
This is great if you know how to style your widgets at application launch
but it becomes ugly when someone wants to change the color of a widget on the fly.
It involves adding a new CSS class with the requested color with `Gtk.CssProvider.load_from_data`
then adding the CSS class on the widget with `Widget.get_style_context().add_class`.
(there might also be an issue with overwriting previously defined CSS styles)

The alternative approach to changing the color of a Widget is described at 
https://python-gtk-3-tutorial.readthedocs.io/en/latest/layout.html#flowbox
which uses the 'draw' gtk signal.

Which approach should toga_gtk take about implementing this?

**Comment by freakboy3742** [comment]
API suggestions welcome. My immediate guess would be a mechanism that maps Pack's style terms to CSS style terms, and then setting the style on individual widgets (i.e. the Toga api to "set background color" will map to "construct new style context and add apply". However I haven't gone looking to see how viable that is as a proposal.

The one piece of related detail that I'll add - targetting CSS *is* broadly in the mandate of Toga, because of the intention to target the Web as a platform. So adding high level APIs to map to CSS are "in scope"; and the end goal is that Pack will be replaced with Colosseum, a full CSS3 implementation (where the mapping to CSS will be a pass through operation).

**Comment by freakboy3742** [comment]
We've recently added better CSS support for GTK widgets, so I'm going to close this feature request. If there's a different (or more specific) feature request behind this, feel free to open a new ticket.
