### ISSUE TITLE
'App' object has no attribute 'app_context' [Windows 10]

### ISSUE THREAD

**Issue by robinsiebler** [beeware/toga#953]
## Expected Behavior
Everything should work.

## Current Behavior
When I run the attached app, I get an error:
Traceback (most recent call last):
  File "D:\\anaconda3\\lib\\site-packages\\toga\\app.py", line 362, in main_window
    self._impl.set_main_window(window)
  File "D:\\anaconda3\\lib\\site-packages\\toga_winforms\\app.py", line 166, in set_main_window
    self.app_context.MainForm = window._impl.native
AttributeError : 'App' object has no attribute 'app_context'

## Steps to reproduce
1. Run the sample app
[bug.zip](https://github.com/beeware/toga/files/4839682/bug.zip)

## Your Environment

* Python Version (list the specific version number): 3.7.6

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ ] macOS - version:
  - [ ] Linux - distro:   - version:
  - [x] Windows - version: 10.0.18363 Build 18363
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
  0.2.15

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [ ] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [x] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by saroad2** [comment]
Hello @robinsiebler ,

In your example, it seems like your trying to create multiple `App` instances dynamically. I think what you meant to do is creating multiple `Window` instances, and that's why it fails.

Try make `TableViewer` inherit from `toga.Window` instead of `toga.App` and work it out from there.
Closing the issue for now as it seems like *Toga* works as designed. If you have further questions, please feel free to reopen the issue.
