### ISSUE TITLE
Android layout seems to ignore top header

### ISSUE THREAD

**Issue by paulproteus** [beeware/toga#968]
**Describe the bug**

Android layout seems to ignore top header

**To Reproduce**
1. Create an app with a widget containing an `at_least(...)` specification in its height (see sample code below for a `MultilineTextInput` example), and one item below it (e.g. a button)
2. Notice that lower-most item is missing visually (in our case, the button)

**Expected behavior**

All widgets should be laid out on the screen successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/25457/87275791-be4a5300-c493-11ea-9a65-d1ce7a24bf93.png)

**Environment:**
 - Operating System: Android
 - Python version: 3.7
 - Software versions:
   - Briefcase: git
   - Toga: git

**Additional context**

Sample code (`app.py`)

```
"""
My first application
"""
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW


class HelloWorld(toga.App):
    def startup(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))

        name_label = toga.Label("Your name: ", style=Pack(padding=(0, 5)))
        self.name_input = toga.MultilineTextInput(style=Pack(flex=1))

        name_box = toga.Box(style=Pack(direction=ROW, padding=5))
        name_box.add(name_label)
        name_box.add(self.name_input)

        button = toga.Button(
            "Say Hello!", on_press=self.say_hello, style=Pack(padding=5)
        )
        self.button = button

        main_box.add(name_box)
        main_box.add(button)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

    def say_hello(self, widget):
        self.button.label = "Hello back atcha"


def main():
    return HelloWorld()
```

**Comment by sarthaksharma058439** [comment]
Check this video .....he make calculator in beeware and deploy to android device

https://youtu.be/RllR6FRdG6w

**Comment by freakboy3742** [comment]
@sarthaksharma058439 You've posted the same comment, advertising the same YouTube video, on five separate tickets. The video is unrelated to the issue being discussed.

This is extremely disrespectful behavior. Please *do not* post like this again. If you do, we will report your account to Github and block your access to comment on BeeWare repositories.

**Comment by mhsmith** [comment]
This issue isn't specific to Android, and it's nothing to do with the title bar, it's just a coincidence that it happens to be about the same height as the button. Here's a minimal example:

```
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW, LEFT, CENTER, RIGHT, TOP, BOTTOM


class Hello(toga.App):
    def startup(self):
        main_box = toga.Box(
            style=Pack(direction=COLUMN),
            children=[
                toga.Box(
                    style=Pack(direction=ROW),
                    children=[
                        toga.MultilineTextInput(style=Pack(flex=1))
                    ]
                ),
                toga.Button("Say Hello!")
            ]
        )

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()


def main():
    return Hello()
```

![flex-0](https://user-images.githubusercontent.com/166954/173955535-ba38d7c6-5558-4cd7-87a8-614d4b9094be.png)

Because the inner Box doesn't have an explicit height an intrinsic height, or a flex value, the Pack algorithm is giving it all the remaining height, even if that means pushing its later siblings off the screen.

However, if I add `flex=1` to the inner Box, then the layout works correctly:

![flex-1](https://user-images.githubusercontent.com/166954/173955926-f74ac1d2-74f8-4b3f-ac39-8a254a34aa08.png)

**Comment by mhsmith** [comment]
Here's an even simpler example:

```
import toga
from toga.style import Pack
from toga.style.pack import COLUMN, ROW, LEFT, CENTER, RIGHT, TOP, BOTTOM


class Hello(toga.App):
    def startup(self):
        main_box = toga.Box(
            style=Pack(direction=COLUMN),
            children=[
                toga.Box(style=Pack(background_color="cyan")),
                toga.Box(style=Pack(background_color="yellow")),
            ]
        )

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()


def main():
    return Hello()
```

This results in a window which is entirely cyan. Adding `flex=1` to the cyan box causes it to disappear completely, and the window becomes entirely yellow. 

I don't know if this behavior is intentional, but I certainly found it confusing.

**Comment by freakboy3742** [comment]
You're not alone in finding this confusing :-)

I believe the issue is related to how Windows and Android report the size of their window, and how that interacts with Toga's layout of the main box. Windows and Android are similar in that they report the size of their window *inclusive* of the menubar/header; GTK/cocoa/iOS (IIRC) report the drawable area. When the menubar/header is included in the drawable space, Pack *should* be subtracting the size of the header/menubar from the available window size, but for some reason is getting that calculation wrong, and the window is being laid out as if it is "1 header height" taller than it should be. A button is about the same height as the header, so if a widget is at the bottom of the page, it *is* being rendered, but just off the bottom of the page. If you put a couple of buttons at the bottom of the column of widgets, those buttons should be visible.

You can debug the math around this by uncommenting the debug lines in [toga/style/applicator.py](https://github.com/beeware/toga/blob/main/src/core/toga/style/applicator.py#L8); that outputs the x,y/w,h of each widget that is drawn. 

This is part of a family of bugs related to the core window layout, and ensuring that all the widgets are visible. What we really need is a good set of edge case tests that exercise these extremes.

**Comment by mhsmith** [comment]
> If you put a couple of buttons at the bottom of the column of widgets, those buttons should be visible.

No matter how many buttons I add, none of them are visible unless I add `flex=1` to the inner Box. So I don't think this is caused by the header, but by the handling of widgets with no intrinsic height. Please see the "even simpler example" above,

However, there is a difference between the platforms: it looks like on Windows and Android, a box with no `flex` defaults to using as much space as possible, while on GTK, it defaults to using as little as possible. This is probably because GTK overrides `rehint` in the base `Widget` class to set an intrinsic size, but Windows and Android don't.

**Comment by mhsmith** [comment]
The first screenshot in https://github.com/beeware/briefcase-android-gradle-template/pull/50 shows that the window size is being calculated correctly on Android. It can go wrong once you start rotating the screen, but that's a separate issue.

**Comment by mhsmith** [comment]
See #1656 for a related example.
